/*
 * Decompiled with CFR 0.152.
 */
package necesse.engine.registries;

import java.awt.Color;
import java.util.List;
import java.util.NoSuchElementException;
import java.util.stream.Collectors;
import necesse.engine.GameLoadingScreen;
import necesse.engine.localization.Localization;
import necesse.engine.modLoader.LoadedMod;
import necesse.engine.modifiers.ModifierUpgradeValue;
import necesse.engine.modifiers.ModifierValue;
import necesse.engine.registries.GameRegistry;
import necesse.engine.registries.IDData;
import necesse.engine.registries.IDDataContainer;
import necesse.entity.mobs.buffs.BuffModifiers;
import necesse.entity.mobs.buffs.CryoImmunityBuff;
import necesse.entity.mobs.buffs.NecroticPoisonBuff;
import necesse.entity.mobs.buffs.NecroticSlowBuff;
import necesse.entity.mobs.buffs.PharaohManaSpentBuff;
import necesse.entity.mobs.buffs.staticBuffs.AblazeBuff;
import necesse.entity.mobs.buffs.staticBuffs.AgedChampionProwessBuff;
import necesse.entity.mobs.buffs.staticBuffs.ArcanicHoodActiveBuff;
import necesse.entity.mobs.buffs.staticBuffs.AscendedDarknessBuff;
import necesse.entity.mobs.buffs.staticBuffs.AscendedDashBuff;
import necesse.entity.mobs.buffs.staticBuffs.BannerOfDamageBuff;
import necesse.entity.mobs.buffs.staticBuffs.BannerOfDefenseBuff;
import necesse.entity.mobs.buffs.staticBuffs.BannerOfPeaceBuff;
import necesse.entity.mobs.buffs.staticBuffs.BannerOfSpeedBuff;
import necesse.entity.mobs.buffs.staticBuffs.BannerOfSummonSpeedBuff;
import necesse.entity.mobs.buffs.staticBuffs.BannerOfWarMobBuff;
import necesse.entity.mobs.buffs.staticBuffs.BarkBladeEnhancedBuff;
import necesse.entity.mobs.buffs.staticBuffs.BarkskinBuff;
import necesse.entity.mobs.buffs.staticBuffs.BashyBushFrenzyBuff;
import necesse.entity.mobs.buffs.staticBuffs.BloodClawStacksBuff;
import necesse.entity.mobs.buffs.staticBuffs.BloodGrimoireMarkedBuff;
import necesse.entity.mobs.buffs.staticBuffs.BloodplateCowlActiveBuff;
import necesse.entity.mobs.buffs.staticBuffs.BossNearbyBuff;
import necesse.entity.mobs.buffs.staticBuffs.BounceGlyphBuff;
import necesse.entity.mobs.buffs.staticBuffs.BrokenArmorBuff;
import necesse.entity.mobs.buffs.staticBuffs.Buff;
import necesse.entity.mobs.buffs.staticBuffs.BullseyeBuff;
import necesse.entity.mobs.buffs.staticBuffs.CampfireBuff;
import necesse.entity.mobs.buffs.staticBuffs.CantCancelSummonedCountBuff;
import necesse.entity.mobs.buffs.staticBuffs.ChilledBuff;
import necesse.entity.mobs.buffs.staticBuffs.CrushingDarknessBuff;
import necesse.entity.mobs.buffs.staticBuffs.CrystallizeBuff;
import necesse.entity.mobs.buffs.staticBuffs.DebugBuff;
import necesse.entity.mobs.buffs.staticBuffs.DebugInvisibilityBuff;
import necesse.entity.mobs.buffs.staticBuffs.DebugSpeedBuff;
import necesse.entity.mobs.buffs.staticBuffs.DemonicRageActiveBuff;
import necesse.entity.mobs.buffs.staticBuffs.DryadHauntedBuff;
import necesse.entity.mobs.buffs.staticBuffs.DryadPossessedBuff;
import necesse.entity.mobs.buffs.staticBuffs.EmeraldPoisonBuff;
import necesse.entity.mobs.buffs.staticBuffs.FlourCoveredSlowBuff;
import necesse.entity.mobs.buffs.staticBuffs.FoodBuff;
import necesse.entity.mobs.buffs.staticBuffs.ForceOfWindActiveBuff;
import necesse.entity.mobs.buffs.staticBuffs.FreezingBuff;
import necesse.entity.mobs.buffs.staticBuffs.FrostSlowBuff;
import necesse.entity.mobs.buffs.staticBuffs.FrostburnBuff;
import necesse.entity.mobs.buffs.staticBuffs.FrozenMobBuff;
import necesse.entity.mobs.buffs.staticBuffs.FrozenMobImmuneBuff;
import necesse.entity.mobs.buffs.staticBuffs.GhostBootsActiveBuff;
import necesse.entity.mobs.buffs.staticBuffs.GhostDashActiveBuff;
import necesse.entity.mobs.buffs.staticBuffs.GodmodeBuff;
import necesse.entity.mobs.buffs.staticBuffs.GuardianBraceletBuff;
import necesse.entity.mobs.buffs.staticBuffs.GuardianShellActiveBuff;
import necesse.entity.mobs.buffs.staticBuffs.HauntedBuff;
import necesse.entity.mobs.buffs.staticBuffs.HealthPotionFatigueBuff;
import necesse.entity.mobs.buffs.staticBuffs.HiddenCooldownBuff;
import necesse.entity.mobs.buffs.staticBuffs.HoldItemBuff;
import necesse.entity.mobs.buffs.staticBuffs.HoverBootsActiveBuff;
import necesse.entity.mobs.buffs.staticBuffs.HumanAngryBuff;
import necesse.entity.mobs.buffs.staticBuffs.HungryBuff;
import necesse.entity.mobs.buffs.staticBuffs.InvulnerableActiveBuff;
import necesse.entity.mobs.buffs.staticBuffs.IvyPoisonBuff;
import necesse.entity.mobs.buffs.staticBuffs.KatanaDashStacksBuff;
import necesse.entity.mobs.buffs.staticBuffs.KineticBootsActiveBuff;
import necesse.entity.mobs.buffs.staticBuffs.LeatherDashersActiveBuff;
import necesse.entity.mobs.buffs.staticBuffs.LifeEssenceStacksBuff;
import necesse.entity.mobs.buffs.staticBuffs.LifelineCooldownBuff;
import necesse.entity.mobs.buffs.staticBuffs.ManaExhaustionBuff;
import necesse.entity.mobs.buffs.staticBuffs.ManaPotionFatigueBuff;
import necesse.entity.mobs.buffs.staticBuffs.MoveSpeedBurstBuff;
import necesse.entity.mobs.buffs.staticBuffs.MyceliumHoodActiveBuff;
import necesse.entity.mobs.buffs.staticBuffs.MyceliumScarfActiveBuff;
import necesse.entity.mobs.buffs.staticBuffs.NettedBuff;
import necesse.entity.mobs.buffs.staticBuffs.NightsteelActiveBuff;
import necesse.entity.mobs.buffs.staticBuffs.OnFireBuff;
import necesse.entity.mobs.buffs.staticBuffs.OverchargedManaBuff;
import necesse.entity.mobs.buffs.staticBuffs.ParryBucklerParriedBuff;
import necesse.entity.mobs.buffs.staticBuffs.PerfectBlockBuff;
import necesse.entity.mobs.buffs.staticBuffs.PerfectStormBuff;
import necesse.entity.mobs.buffs.staticBuffs.PirateEscapeBuff;
import necesse.entity.mobs.buffs.staticBuffs.PiratePassiveBuff;
import necesse.entity.mobs.buffs.staticBuffs.QuadrupleChaseRangeBuff;
import necesse.entity.mobs.buffs.staticBuffs.QuicksandStacksBuff;
import necesse.entity.mobs.buffs.staticBuffs.ReverseDamageGlyphBuff;
import necesse.entity.mobs.buffs.staticBuffs.RunicEmpowermentActiveBuff;
import necesse.entity.mobs.buffs.staticBuffs.SandKnifeWoundBuff;
import necesse.entity.mobs.buffs.staticBuffs.SapphireSetActiveBuff;
import necesse.entity.mobs.buffs.staticBuffs.SecondBossWatchingBuff;
import necesse.entity.mobs.buffs.staticBuffs.SecondLifePerkBuff;
import necesse.entity.mobs.buffs.staticBuffs.SettlementFlagBuff;
import necesse.entity.mobs.buffs.staticBuffs.SettlerSprintBuff;
import necesse.entity.mobs.buffs.staticBuffs.ShadowHoodSetBuff;
import necesse.entity.mobs.buffs.staticBuffs.ShieldActiveBuff;
import necesse.entity.mobs.buffs.staticBuffs.ShownCooldownBuff;
import necesse.entity.mobs.buffs.staticBuffs.ShownItemCooldownBuff;
import necesse.entity.mobs.buffs.staticBuffs.SimpleDebuff;
import necesse.entity.mobs.buffs.staticBuffs.SimpleModifierBuff;
import necesse.entity.mobs.buffs.staticBuffs.SimplePotionBuff;
import necesse.entity.mobs.buffs.staticBuffs.SleepingBuff;
import necesse.entity.mobs.buffs.staticBuffs.SlimeDomeActiveBuff;
import necesse.entity.mobs.buffs.staticBuffs.SlimeGreatbowSlowTargetBuff;
import necesse.entity.mobs.buffs.staticBuffs.SlimePoisonBuff;
import necesse.entity.mobs.buffs.staticBuffs.SnowCoveredBuff;
import necesse.entity.mobs.buffs.staticBuffs.SnowCoveredSlowBuff;
import necesse.entity.mobs.buffs.staticBuffs.SoldierFrenzyBuff;
import necesse.entity.mobs.buffs.staticBuffs.SoulseedConsecutiveExplosionsBuff;
import necesse.entity.mobs.buffs.staticBuffs.SoulstormSoulStacksBuff;
import necesse.entity.mobs.buffs.staticBuffs.SpawnInvincibilityBuff;
import necesse.entity.mobs.buffs.staticBuffs.SpiderCharmPoisonBuff;
import necesse.entity.mobs.buffs.staticBuffs.SpiderVenomBuff;
import necesse.entity.mobs.buffs.staticBuffs.SpiderWebSlowBuff;
import necesse.entity.mobs.buffs.staticBuffs.SpiritCorruptedBuff;
import necesse.entity.mobs.buffs.staticBuffs.SpiritHauntedBuff;
import necesse.entity.mobs.buffs.staticBuffs.SpiritPossessedBuff;
import necesse.entity.mobs.buffs.staticBuffs.StabbyBushFrenzyBuff;
import necesse.entity.mobs.buffs.staticBuffs.StaminaBuff;
import necesse.entity.mobs.buffs.staticBuffs.StarBarrierBuff;
import necesse.entity.mobs.buffs.staticBuffs.StarvingBuff;
import necesse.entity.mobs.buffs.staticBuffs.StatsBuff;
import necesse.entity.mobs.buffs.staticBuffs.StinkFlaskBuff;
import necesse.entity.mobs.buffs.staticBuffs.StunnedDamageTakenIncreassedBuff;
import necesse.entity.mobs.buffs.staticBuffs.SummonedMobBuff;
import necesse.entity.mobs.buffs.staticBuffs.SummonedMountBuff;
import necesse.entity.mobs.buffs.staticBuffs.SummonedPetBuff;
import necesse.entity.mobs.buffs.staticBuffs.SummonersBestiaryBuff;
import necesse.entity.mobs.buffs.staticBuffs.SwampSporesBuff;
import necesse.entity.mobs.buffs.staticBuffs.TeleportSicknessBuff;
import necesse.entity.mobs.buffs.staticBuffs.ThornsPotionBuff;
import necesse.entity.mobs.buffs.staticBuffs.WebPotionBuff;
import necesse.entity.mobs.buffs.staticBuffs.WebPotionSlowBuff;
import necesse.entity.mobs.buffs.staticBuffs.WidowPoisonBuff;
import necesse.entity.mobs.buffs.staticBuffs.WindBootsActiveBuff;
import necesse.entity.mobs.buffs.staticBuffs.ZephyrBootsActiveBuff;
import necesse.entity.mobs.buffs.staticBuffs.armorBuffs.setBonusBuffs.AgedChampionSetBonusBuff;
import necesse.entity.mobs.buffs.staticBuffs.armorBuffs.setBonusBuffs.AmethystSetBonusBuff;
import necesse.entity.mobs.buffs.staticBuffs.armorBuffs.setBonusBuffs.AncestorSetBonusBuff;
import necesse.entity.mobs.buffs.staticBuffs.armorBuffs.setBonusBuffs.AncientFossilHelmetSetBonusBuff;
import necesse.entity.mobs.buffs.staticBuffs.armorBuffs.setBonusBuffs.AncientFossilMaskSetBonusBuff;
import necesse.entity.mobs.buffs.staticBuffs.armorBuffs.setBonusBuffs.ArachnidSetBonusBuff;
import necesse.entity.mobs.buffs.staticBuffs.armorBuffs.setBonusBuffs.ArcanicHelmetSetBonusBuff;
import necesse.entity.mobs.buffs.staticBuffs.armorBuffs.setBonusBuffs.BattleChefSetBonusBuff;
import necesse.entity.mobs.buffs.staticBuffs.armorBuffs.setBonusBuffs.BloodplateCowlSetBonusBuff;
import necesse.entity.mobs.buffs.staticBuffs.armorBuffs.setBonusBuffs.CryoWitchSetBonusBuff;
import necesse.entity.mobs.buffs.staticBuffs.armorBuffs.setBonusBuffs.DawnSetBonusBuff;
import necesse.entity.mobs.buffs.staticBuffs.armorBuffs.setBonusBuffs.DeepfrostSetBonusBuff;
import necesse.entity.mobs.buffs.staticBuffs.armorBuffs.setBonusBuffs.DemonicSetBonusBuff;
import necesse.entity.mobs.buffs.staticBuffs.armorBuffs.setBonusBuffs.DryadCrownSetBonusBuff;
import necesse.entity.mobs.buffs.staticBuffs.armorBuffs.setBonusBuffs.DryadHatSetBonusBuff;
import necesse.entity.mobs.buffs.staticBuffs.armorBuffs.setBonusBuffs.DryadHelmetSetBonusBuff;
import necesse.entity.mobs.buffs.staticBuffs.armorBuffs.setBonusBuffs.DryadScarfSetBonusBuff;
import necesse.entity.mobs.buffs.staticBuffs.armorBuffs.setBonusBuffs.DuskSetBonusBuff;
import necesse.entity.mobs.buffs.staticBuffs.armorBuffs.setBonusBuffs.EmeraldSetBonusBuff;
import necesse.entity.mobs.buffs.staticBuffs.armorBuffs.setBonusBuffs.FrostSetBonusBuff;
import necesse.entity.mobs.buffs.staticBuffs.armorBuffs.setBonusBuffs.GlacialCircletBonusBuff;
import necesse.entity.mobs.buffs.staticBuffs.armorBuffs.setBonusBuffs.GlacialHelmetBonusBuff;
import necesse.entity.mobs.buffs.staticBuffs.armorBuffs.setBonusBuffs.GunslingerSetBonusBuff;
import necesse.entity.mobs.buffs.staticBuffs.armorBuffs.setBonusBuffs.IvyCircletSetBonusBuff;
import necesse.entity.mobs.buffs.staticBuffs.armorBuffs.setBonusBuffs.IvyHatSetBonusBuff;
import necesse.entity.mobs.buffs.staticBuffs.armorBuffs.setBonusBuffs.IvyHelmetSetBonusBuff;
import necesse.entity.mobs.buffs.staticBuffs.armorBuffs.setBonusBuffs.IvyHoodSetBonusBuff;
import necesse.entity.mobs.buffs.staticBuffs.armorBuffs.setBonusBuffs.MyceliumHoodSetBonusBuff;
import necesse.entity.mobs.buffs.staticBuffs.armorBuffs.setBonusBuffs.MyceliumScarfSetBonusBuff;
import necesse.entity.mobs.buffs.staticBuffs.armorBuffs.setBonusBuffs.NightSteelCircletSetBonusBuff;
import necesse.entity.mobs.buffs.staticBuffs.armorBuffs.setBonusBuffs.NightSteelHelmetSetBonusBuff;
import necesse.entity.mobs.buffs.staticBuffs.armorBuffs.setBonusBuffs.NightSteelSetBonusBuff;
import necesse.entity.mobs.buffs.staticBuffs.armorBuffs.setBonusBuffs.NightSteelVeilSetBonusBuff;
import necesse.entity.mobs.buffs.staticBuffs.armorBuffs.setBonusBuffs.NinjaSetBonusBuff;
import necesse.entity.mobs.buffs.staticBuffs.armorBuffs.setBonusBuffs.PharaohsSetBonusBuff;
import necesse.entity.mobs.buffs.staticBuffs.armorBuffs.setBonusBuffs.QuartzCrownSetBonusBuff;
import necesse.entity.mobs.buffs.staticBuffs.armorBuffs.setBonusBuffs.QuartzHelmetSetBonusBuff;
import necesse.entity.mobs.buffs.staticBuffs.armorBuffs.setBonusBuffs.RavenlordsHeaddressSetBonusBuff;
import necesse.entity.mobs.buffs.staticBuffs.armorBuffs.setBonusBuffs.RubySetBonusBuff;
import necesse.entity.mobs.buffs.staticBuffs.armorBuffs.setBonusBuffs.RunicHatSetBonusBuff;
import necesse.entity.mobs.buffs.staticBuffs.armorBuffs.setBonusBuffs.RunicSetBonusBuff;
import necesse.entity.mobs.buffs.staticBuffs.armorBuffs.setBonusBuffs.SapphireSetBonusBuff;
import necesse.entity.mobs.buffs.staticBuffs.armorBuffs.setBonusBuffs.SetBonusBuff;
import necesse.entity.mobs.buffs.staticBuffs.armorBuffs.setBonusBuffs.ShadowHatSetBonusBuff;
import necesse.entity.mobs.buffs.staticBuffs.armorBuffs.setBonusBuffs.ShadowHoodSetBonusBuff;
import necesse.entity.mobs.buffs.staticBuffs.armorBuffs.setBonusBuffs.SharpshooterSetBonusBuff;
import necesse.entity.mobs.buffs.staticBuffs.armorBuffs.setBonusBuffs.SimpleUpgradeSetBonusBuff;
import necesse.entity.mobs.buffs.staticBuffs.armorBuffs.setBonusBuffs.SlimeHatSetBonusBuff;
import necesse.entity.mobs.buffs.staticBuffs.armorBuffs.setBonusBuffs.SlimeHelmetSetBonusBuff;
import necesse.entity.mobs.buffs.staticBuffs.armorBuffs.setBonusBuffs.SoldierCapSetBonusBuff;
import necesse.entity.mobs.buffs.staticBuffs.armorBuffs.setBonusBuffs.SoldierHelmetSetBonusBuff;
import necesse.entity.mobs.buffs.staticBuffs.armorBuffs.setBonusBuffs.SoulseedCrownSetBonusBuff;
import necesse.entity.mobs.buffs.staticBuffs.armorBuffs.setBonusBuffs.SpiderSetBonusBuff;
import necesse.entity.mobs.buffs.staticBuffs.armorBuffs.setBonusBuffs.SpideriteCrownSetBonusBuff;
import necesse.entity.mobs.buffs.staticBuffs.armorBuffs.setBonusBuffs.SpideriteHatSetBonusBuff;
import necesse.entity.mobs.buffs.staticBuffs.armorBuffs.setBonusBuffs.SpideriteHelmetSetBonusBuff;
import necesse.entity.mobs.buffs.staticBuffs.armorBuffs.setBonusBuffs.SpideriteSetBonusBuff;
import necesse.entity.mobs.buffs.staticBuffs.armorBuffs.setBonusBuffs.SupporterSetBonusBuff;
import necesse.entity.mobs.buffs.staticBuffs.armorBuffs.setBonusBuffs.ThiefSetBonusBuff;
import necesse.entity.mobs.buffs.staticBuffs.armorBuffs.setBonusBuffs.TungstenSetBonusBuff;
import necesse.entity.mobs.buffs.staticBuffs.armorBuffs.setBonusBuffs.VoidHatSetBonusBuff;
import necesse.entity.mobs.buffs.staticBuffs.armorBuffs.setBonusBuffs.VoidMaskSetBonusBuff;
import necesse.entity.mobs.buffs.staticBuffs.armorBuffs.setBonusBuffs.WidowSetBonusBuff;
import necesse.entity.mobs.buffs.staticBuffs.armorBuffs.setBonusBuffs.WitchRobesSetBonusBuff;
import necesse.entity.mobs.buffs.staticBuffs.armorBuffs.trinketBuffs.AgedChampionScabbardBuff;
import necesse.entity.mobs.buffs.staticBuffs.armorBuffs.trinketBuffs.AmethystGlyphBuff;
import necesse.entity.mobs.buffs.staticBuffs.armorBuffs.trinketBuffs.BalancedFociBuff;
import necesse.entity.mobs.buffs.staticBuffs.armorBuffs.trinketBuffs.BlinkScepterTrinketBuff;
import necesse.entity.mobs.buffs.staticBuffs.armorBuffs.trinketBuffs.BloodstoneRingBuff;
import necesse.entity.mobs.buffs.staticBuffs.armorBuffs.trinketBuffs.BloodstoneRingRegenActiveBuff;
import necesse.entity.mobs.buffs.staticBuffs.armorBuffs.trinketBuffs.CavelingsCollectionBuff;
import necesse.entity.mobs.buffs.staticBuffs.armorBuffs.trinketBuffs.CavelingsFootBuff;
import necesse.entity.mobs.buffs.staticBuffs.armorBuffs.trinketBuffs.ChallengersPauldronBuff;
import necesse.entity.mobs.buffs.staticBuffs.armorBuffs.trinketBuffs.ClockworkHeartBuff;
import necesse.entity.mobs.buffs.staticBuffs.armorBuffs.trinketBuffs.CompanionLocketBuff;
import necesse.entity.mobs.buffs.staticBuffs.armorBuffs.trinketBuffs.DebugInvincibilityBuff;
import necesse.entity.mobs.buffs.staticBuffs.armorBuffs.trinketBuffs.EmeraldGlyphBuff;
import necesse.entity.mobs.buffs.staticBuffs.armorBuffs.trinketBuffs.ExplorerCloakBuff;
import necesse.entity.mobs.buffs.staticBuffs.armorBuffs.trinketBuffs.FinsBuff;
import necesse.entity.mobs.buffs.staticBuffs.armorBuffs.trinketBuffs.FireStoneBuff;
import necesse.entity.mobs.buffs.staticBuffs.armorBuffs.trinketBuffs.FoolsGambitTrinketBuff;
import necesse.entity.mobs.buffs.staticBuffs.armorBuffs.trinketBuffs.ForceOfWindTrinketBuff;
import necesse.entity.mobs.buffs.staticBuffs.armorBuffs.trinketBuffs.FrenzyOrbBuff;
import necesse.entity.mobs.buffs.staticBuffs.armorBuffs.trinketBuffs.FrostFlameBuff;
import necesse.entity.mobs.buffs.staticBuffs.armorBuffs.trinketBuffs.FrostStoneBuff;
import necesse.entity.mobs.buffs.staticBuffs.armorBuffs.trinketBuffs.GhostBootsTrinketBuff;
import necesse.entity.mobs.buffs.staticBuffs.armorBuffs.trinketBuffs.GuardianBraceletTrinketBuff;
import necesse.entity.mobs.buffs.staticBuffs.armorBuffs.trinketBuffs.GuardianShellTrinketBuff;
import necesse.entity.mobs.buffs.staticBuffs.armorBuffs.trinketBuffs.HoverBootsTrinketBuff;
import necesse.entity.mobs.buffs.staticBuffs.armorBuffs.trinketBuffs.IncursionEmpowermentAttackSpeedBuff;
import necesse.entity.mobs.buffs.staticBuffs.armorBuffs.trinketBuffs.IncursionEmpowermentCritChanceBuff;
import necesse.entity.mobs.buffs.staticBuffs.armorBuffs.trinketBuffs.IncursionEmpowermentRegenBuff;
import necesse.entity.mobs.buffs.staticBuffs.armorBuffs.trinketBuffs.KineticBootsTrinketBuff;
import necesse.entity.mobs.buffs.staticBuffs.armorBuffs.trinketBuffs.LeatherDashersTrinketBuff;
import necesse.entity.mobs.buffs.staticBuffs.armorBuffs.trinketBuffs.LifelineBuff;
import necesse.entity.mobs.buffs.staticBuffs.armorBuffs.trinketBuffs.MagicFociBuff;
import necesse.entity.mobs.buffs.staticBuffs.armorBuffs.trinketBuffs.MeleeFociBuff;
import necesse.entity.mobs.buffs.staticBuffs.armorBuffs.trinketBuffs.MinersProstheticTrinketBuff;
import necesse.entity.mobs.buffs.staticBuffs.armorBuffs.trinketBuffs.MobilityCloakBuff;
import necesse.entity.mobs.buffs.staticBuffs.armorBuffs.trinketBuffs.NecroticSoulSkullTrinketBuff;
import necesse.entity.mobs.buffs.staticBuffs.armorBuffs.trinketBuffs.NinjasMarkBuff;
import necesse.entity.mobs.buffs.staticBuffs.armorBuffs.trinketBuffs.PolarClawBuff;
import necesse.entity.mobs.buffs.staticBuffs.armorBuffs.trinketBuffs.RangeFociBuff;
import necesse.entity.mobs.buffs.staticBuffs.armorBuffs.trinketBuffs.RubyGlyphBuff;
import necesse.entity.mobs.buffs.staticBuffs.armorBuffs.trinketBuffs.SapphireGlyphBuff;
import necesse.entity.mobs.buffs.staticBuffs.armorBuffs.trinketBuffs.SecondWindTrinketBuff;
import necesse.entity.mobs.buffs.staticBuffs.armorBuffs.trinketBuffs.ShieldTrinketBuff;
import necesse.entity.mobs.buffs.staticBuffs.armorBuffs.trinketBuffs.ShineBeltBuff;
import necesse.entity.mobs.buffs.staticBuffs.armorBuffs.trinketBuffs.SimpleTrinketBuff;
import necesse.entity.mobs.buffs.staticBuffs.armorBuffs.trinketBuffs.SpiderCharmBuff;
import necesse.entity.mobs.buffs.staticBuffs.armorBuffs.trinketBuffs.SpiritBoardTrinketBuff;
import necesse.entity.mobs.buffs.staticBuffs.armorBuffs.trinketBuffs.SpiritGreavesTrinketBuff;
import necesse.entity.mobs.buffs.staticBuffs.armorBuffs.trinketBuffs.SummonFociBuff;
import necesse.entity.mobs.buffs.staticBuffs.armorBuffs.trinketBuffs.SummonersBestiaryTrinketBuff;
import necesse.entity.mobs.buffs.staticBuffs.armorBuffs.trinketBuffs.TopazGlyphBuff;
import necesse.entity.mobs.buffs.staticBuffs.armorBuffs.trinketBuffs.TravelerCloakBuff;
import necesse.entity.mobs.buffs.staticBuffs.armorBuffs.trinketBuffs.VoidPhasingStaffTrinketBuff;
import necesse.entity.mobs.buffs.staticBuffs.armorBuffs.trinketBuffs.VoodooShieldTrinketBuff;
import necesse.entity.mobs.buffs.staticBuffs.armorBuffs.trinketBuffs.WillOWispLanternBuff;
import necesse.entity.mobs.buffs.staticBuffs.armorBuffs.trinketBuffs.WindBootsTrinketBuff;
import necesse.entity.mobs.buffs.staticBuffs.armorBuffs.trinketBuffs.ZephyrBootsTrinketBuff;
import necesse.entity.mobs.buffs.staticBuffs.incursionBuffs.AlchemicalInterferenceBuff;
import necesse.entity.mobs.buffs.staticBuffs.incursionBuffs.FrenzyBuff;
import necesse.entity.mobs.buffs.staticBuffs.incursionBuffs.PerkFlamelingsCanDieBuff;
import necesse.entity.mobs.buffs.staticBuffs.incursionBuffs.TremorHappeningBuff;
import necesse.entity.mobs.buffs.staticBuffs.incursionBuffs.TremorsIncomingBuff;
import necesse.entity.mobs.buffs.staticBuffs.polymorph.PolymorphBuff;
import necesse.inventory.item.upgradeUtils.FloatUpgradeValue;
import necesse.inventory.item.upgradeUtils.IntUpgradeValue;

public class BuffRegistry
extends GameRegistry<BuffRegistryElement<?>> {
    public static Buff FRENZY;
    public static Buff TREMORS_INCOMING;
    public static Buff TREMOR_HAPPENING;
    public static Buff ALCHEMICAL_INTERFERENCE;
    public static Buff PERK_FLAMELINGS_CAN_DIE;
    public static Buff SECOND_LIFE_PERK;
    public static Buff DEBUG_BUFF;
    public static Buff SHADOWHOOD_SET;
    public static Buff DEBUG_INVIS;
    public static Buff DEBUG_INVINCIBILITY;
    public static Buff DEBUG_SPEED;
    public static Buff PIRATE_ESCAPE;
    public static Buff PIRATE_PASSIVE;
    public static Buff SUMMONED_PET;
    public static Buff SUMMONED_MOUNT;
    public static Buff SUMMONED_MOB;
    public static Buff HUMAN_ANGRY;
    public static Buff MOVE_SPEED_BURST;
    public static Buff BOSS_NEARBY;
    public static Buff SETTLEMENT_FLAG;
    public static Buff CAMPFIRE;
    public static Buff ANCIENT_FOSSIL_ACTIVE;
    public static Buff SPIDER_CHARGE;
    public static Buff BLOODPLATE_COWL_ACTIVE;
    public static Buff BLOOD_CLAW_STACKS_BUFF;
    public static Buff BLOODSTONE_RING_REGEN_ACTIVE_BUFF;
    public static Buff STAR_BARRIER_BUFF;
    public static Buff STABBY_BUSH_FRENZY_BUFF;
    public static Buff BASHY_BUSH_FRENZY_BUFF;
    public static Buff BANNER_OF_WAR_MOB;
    public static Buff OVERCHARGED_MANA;
    public static Buff ARCANIC_HOOD_ACTIVE;
    public static Buff LIFE_ESSENCE;
    public static Buff SAPPHIRE_GLYPH;
    public static Buff AMETHYST_GLYPH;
    public static Buff RUBY_GLYPH;
    public static Buff EMERALD_GLYPH;
    public static Buff TOPAZ_GLYPH;
    public static Buff QUADRUPLE_CHASE_RANGE;
    public static Buff SUMMONED_WILL_O_WISP;
    public static Buff QUICKSAND_STACKS;
    public static Buff BARK_SKIN;
    public static Buff AGED_CHAMPION_PROWESS;
    public static Buff BULLSEYE;
    public static Buff SUMMONERS_BESTIARY;
    public static Buff GUARDIAN_BRACELET;
    public static Buff BARKBLADE_ENHANCED;
    public static Buff PARRY_BUCKLER_PARRIED;
    public static Buff SOULSTORM_SOULS;
    public static Buff BOUNCE_GLYPH;
    public static Buff REVERSE_DAMAGE_GLYPH;
    public static Buff SOULSEED_CONSECUTIVE;
    public static Buff SUMMONED_GHOSTLYBOW;
    public static Buff SOLDIER_FRENZY;
    public static Buff SUMMONED_LOCUST;
    public static Buff PHARAOH_MANA_SPENT;
    public static Buff CRYO_IMMUNTY;
    public static Buff ASCENDED_DASH;
    public static Buff SPAWN_INVINCIBILITY;
    public static Buff HARDENED;
    public static Buff SETTLER_SPRINT;
    public static Buff FROZEN_MOB_IMMUNE;
    public static Buff FROZEN_MOB;
    public static Buff THAWED_ENEMY;
    public static Buff INCURSION_EMPOWERMENT_CRIT_CHANCE;
    public static Buff INCURSION_EMPOWERMENT_ATTACK_SPEED;
    public static Buff INCURSION_EMPOWERMENT_REGEN;
    public static Buff LEATHER_DASHERS_ACTIVE;
    public static Buff ZEPHYR_BOOTS_ACTIVE;
    public static Buff WIND_BOOTS_ACTIVE;
    public static Buff HOVER_BOOTS_ACTIVE;
    public static Buff GHOST_BOOTS_ACTIVE;
    public static Buff KINETIC_BOOTS_ACTIVE;
    public static Buff FOW_ACTIVE;
    public static Buff INVULNERABLE_ACTIVE;
    public static Buff GHOST_DASH_ACTIVE;
    public static Buff KATANA_DASH_STACKS;
    public static Buff GUARDIAN_SHELL_ACTIVE;
    public static Buff MYCELIUM_HOOD_ACTIVE;
    public static Buff MYCELIUM_SCARF_ACTIVE;
    public static Buff NIGHTSTEEL_ACTIVE;
    public static Buff SLIME_DOME_ACTIVE;
    public static Buff RUNIC_EMPOWERMENT;
    public static Buff SAPPHIRE_SET_ACTIVE;
    public static Buff SHIELD_ACTIVE;
    public static Buff PERFECT_BLOCK;
    public static Buff SLEEPING;
    public static Buff SWAMP_SPORES;
    public static Buff DEMONIC_RAGE;
    public static Buff PERFECT_STORM;
    public static StatsBuff EQUIPMENT_BUFF;
    public static FoodBuff[] FOOD_BUFFS;
    public static FoodBuff FOOD_DEBUFF;
    public static Buff HUNGRY_BUFF;
    public static Buff STARVING_BUFF;
    public static Buff STAMINA_BUFF;
    public static Buff HOLD_ITEM_BUFF;
    public static Buff GODMODE_BUFF;
    public static final BuffRegistry instance;
    private static int totalSetBonuses;

    private BuffRegistry() {
        super("Buff", 32762);
    }

    @Override
    public void registerCore() {
        GameLoadingScreen.drawLoadingString(Localization.translate("loading", "buffs"));
        DEBUG_BUFF = BuffRegistry.registerBuff("debugbuff", new DebugBuff());
        DEBUG_INVIS = BuffRegistry.registerBuff("debuginvisibility", new DebugInvisibilityBuff());
        DEBUG_INVINCIBILITY = BuffRegistry.registerBuff("debuginvincibility", new DebugInvincibilityBuff());
        DEBUG_SPEED = BuffRegistry.registerBuff("debugspeed", new DebugSpeedBuff());
        GODMODE_BUFF = BuffRegistry.registerBuff("godmode", new GodmodeBuff());
        BuffRegistry.registerBuff("speedpotion", new SimplePotionBuff(new ModifierValue<Float>(BuffModifiers.SPEED, Float.valueOf(0.2f))));
        BuffRegistry.registerBuff("greaterspeedpotion", new SimplePotionBuff(new ModifierValue<Float>(BuffModifiers.SPEED, Float.valueOf(0.3f))));
        BuffRegistry.registerBuff("healthregenpotion", new SimplePotionBuff(new ModifierValue<Float>(BuffModifiers.COMBAT_HEALTH_REGEN_FLAT, Float.valueOf(0.5f))));
        BuffRegistry.registerBuff("greaterhealthregenpotion", new SimplePotionBuff(new ModifierValue<Float>(BuffModifiers.COMBAT_HEALTH_REGEN_FLAT, Float.valueOf(1.0f))));
        BuffRegistry.registerBuff("manaregenpotion", new SimplePotionBuff(new ModifierValue<Float>(BuffModifiers.COMBAT_MANA_REGEN, Float.valueOf(3.0f))));
        BuffRegistry.registerBuff("greatermanaregenpotion", new SimplePotionBuff(new ModifierValue<Float>(BuffModifiers.COMBAT_MANA_REGEN, Float.valueOf(5.0f))));
        BuffRegistry.registerBuff("attackspeedpotion", new SimplePotionBuff(new ModifierValue<Float>(BuffModifiers.ATTACK_SPEED, Float.valueOf(0.15f))));
        BuffRegistry.registerBuff("greaterattackspeedpotion", new SimplePotionBuff(new ModifierValue<Float>(BuffModifiers.ATTACK_SPEED, Float.valueOf(0.3f))));
        BuffRegistry.registerBuff("invisibilitypotion", new SimplePotionBuff(new ModifierValue<Boolean>(BuffModifiers.INVISIBILITY, true)));
        BuffRegistry.registerBuff("fireresistancepotion", new SimplePotionBuff(new ModifierValue<Float>(BuffModifiers.FIRE_DAMAGE, Float.valueOf(0.0f)).max(Float.valueOf(0.0f))));
        BuffRegistry.registerBuff("fishingpotion", new SimplePotionBuff(new ModifierValue<Integer>(BuffModifiers.FISHING_POWER, 20), new ModifierValue<Integer>(BuffModifiers.FISHING_LINES, 1)));
        BuffRegistry.registerBuff("greaterfishingpotion", new SimplePotionBuff(new ModifierValue<Integer>(BuffModifiers.FISHING_POWER, 30), new ModifierValue<Integer>(BuffModifiers.FISHING_LINES, 2)));
        BuffRegistry.registerBuff("battlepotion", new SimplePotionBuff(new ModifierValue<Float>(BuffModifiers.ALL_DAMAGE, Float.valueOf(0.1f))));
        BuffRegistry.registerBuff("greaterbattlepotion", new SimplePotionBuff(new ModifierValue<Float>(BuffModifiers.ALL_DAMAGE, Float.valueOf(0.15f))));
        BuffRegistry.registerBuff("resistancepotion", new SimplePotionBuff(new ModifierValue<Integer>(BuffModifiers.ARMOR_FLAT, 8)));
        BuffRegistry.registerBuff("greaterresistancepotion", new SimplePotionBuff(new ModifierValue<Integer>(BuffModifiers.ARMOR_FLAT, 12)));
        BuffRegistry.registerBuff("spelunkerpotion", new SimplePotionBuff(new ModifierValue<Boolean>(BuffModifiers.SPELUNKER, true)));
        BuffRegistry.registerBuff("treasurepotion", new SimplePotionBuff(new ModifierValue<Boolean>(BuffModifiers.TREASURE_HUNTER, true)));
        BuffRegistry.registerBuff("passivepotion", new SimplePotionBuff(new ModifierValue<Float>(BuffModifiers.MOB_SPAWN_RATE, Float.valueOf(0.0f)).max(Float.valueOf(0.1f))));
        BuffRegistry.registerBuff("buildingpotion", new SimplePotionBuff(new ModifierValue<Float>(BuffModifiers.BUILDING_SPEED, Float.valueOf(0.5f))));
        BuffRegistry.registerBuff("greaterbuildingpotion", new SimplePotionBuff(new ModifierValue<Float>(BuffModifiers.BUILDING_SPEED, Float.valueOf(1.0f))));
        BuffRegistry.registerBuff("miningpotion", new SimplePotionBuff(new ModifierValue<Float>(BuffModifiers.MINING_SPEED, Float.valueOf(0.4f))));
        BuffRegistry.registerBuff("greaterminingpotion", new SimplePotionBuff(new ModifierValue<Float>(BuffModifiers.MINING_SPEED, Float.valueOf(0.8f))));
        BuffRegistry.registerBuff("thornspotion", new ThornsPotionBuff());
        BuffRegistry.registerBuff("knockbackpotion", new SimplePotionBuff(new ModifierValue<Float>(BuffModifiers.KNOCKBACK_OUT, Float.valueOf(0.5f))));
        BuffRegistry.registerBuff("rapidpotion", new SimplePotionBuff(new ModifierValue<Float>(BuffModifiers.PROJECTILE_VELOCITY, Float.valueOf(0.5f))));
        BuffRegistry.registerBuff("greaterrapidpotion", new SimplePotionBuff(new ModifierValue<Float>(BuffModifiers.PROJECTILE_VELOCITY, Float.valueOf(1.0f))));
        BuffRegistry.registerBuff("accuracypotion", new SimplePotionBuff(new ModifierValue<Float>(BuffModifiers.CRIT_CHANCE, Float.valueOf(0.1f))));
        BuffRegistry.registerBuff("greateraccuracypotion", new SimplePotionBuff(new ModifierValue<Float>(BuffModifiers.CRIT_CHANCE, Float.valueOf(0.2f))));
        BuffRegistry.registerBuff("webpotion", new WebPotionBuff());
        BuffRegistry.registerBuff("strengthpotion", new SimplePotionBuff(new ModifierValue<Float>(BuffModifiers.MELEE_DAMAGE, Float.valueOf(0.1f))));
        BuffRegistry.registerBuff("rangerpotion", new SimplePotionBuff(new ModifierValue<Float>(BuffModifiers.RANGED_DAMAGE, Float.valueOf(0.1f))));
        BuffRegistry.registerBuff("wisdompotion", new SimplePotionBuff(new ModifierValue<Float>(BuffModifiers.MAGIC_DAMAGE, Float.valueOf(0.1f))));
        BuffRegistry.registerBuff("minionpotion", new SimplePotionBuff(new ModifierValue<Integer>(BuffModifiers.MAX_SUMMONS, 1)));
        Potions.STINKFLASK = BuffRegistry.registerBuff("stinkflask", new StinkFlaskBuff());
        Debuffs.HEALTH_POT_FATIGUE = BuffRegistry.registerBuff("healthpotionfatigue", new HealthPotionFatigueBuff());
        Debuffs.MANA_POT_FATIGUE = BuffRegistry.registerBuff("manapotionfatigue", new ManaPotionFatigueBuff());
        Debuffs.MANA_EXHAUSTION = BuffRegistry.registerBuff("manaexhaustion", new ManaExhaustionBuff());
        Debuffs.ON_FIRE = BuffRegistry.registerBuff("onfire", new OnFireBuff());
        Debuffs.ABLAZE = BuffRegistry.registerBuff("ablaze", new AblazeBuff());
        Debuffs.BROKEN_ARMOR = BuffRegistry.registerBuff("brokenarmor", new BrokenArmorBuff());
        Debuffs.TELEPORT_SICKNESS = BuffRegistry.registerBuff("teleportsickness", new TeleportSicknessBuff());
        Debuffs.LIFELINE_COOLDOWN = BuffRegistry.registerBuff("lifelinecooldown", new LifelineCooldownBuff());
        Debuffs.QUARTZ_SET_COOLDOWN = BuffRegistry.registerBuff("quartzsetcooldown", new ShownCooldownBuff());
        Debuffs.GUNSLINGER_SET_COOLDOWN = BuffRegistry.registerBuff("gunslingersetcooldown", new ShownCooldownBuff());
        Debuffs.VOID_SET_COOLDOWN = BuffRegistry.registerBuff("voidsetcooldown", new ShownCooldownBuff());
        Debuffs.DASH_COOLDOWN = BuffRegistry.registerBuff("dashcooldown", new ShownCooldownBuff(250, true));
        Debuffs.SPIDER_WEB_SLOW = BuffRegistry.registerBuff("spiderwebslow", new SpiderWebSlowBuff());
        Debuffs.WEB_POTION_SLOW = BuffRegistry.registerBuff("webpotionslow", new WebPotionSlowBuff());
        Debuffs.SPIDER_VENOM = BuffRegistry.registerBuff("spidervenom", new SpiderVenomBuff());
        Debuffs.NECROTIC_POISON = BuffRegistry.registerBuff("necroticpoison", new NecroticPoisonBuff());
        Debuffs.NECROTIC_SLOW = BuffRegistry.registerBuff("necroticslow", new NecroticSlowBuff());
        Debuffs.IVY_POISON = BuffRegistry.registerBuff("ivypoison", new IvyPoisonBuff());
        Debuffs.WIDOW_POISON = BuffRegistry.registerBuff("widowpoison", new WidowPoisonBuff());
        Debuffs.CHILLED = BuffRegistry.registerBuff("chilled", new ChilledBuff());
        Debuffs.FREEZING = BuffRegistry.registerBuff("freezing", new FreezingBuff());
        Debuffs.FROSTBURN = BuffRegistry.registerBuff("frostburn", new FrostburnBuff());
        Debuffs.FROSTSLOW = BuffRegistry.registerBuff("frostslow", new FrostSlowBuff());
        Debuffs.SNOW_COVERED_DEBUFF = BuffRegistry.registerBuff("snowcovered", new SnowCoveredBuff());
        Debuffs.SNOW_COVERED_SLOW_DEBUFF = BuffRegistry.registerBuff("snowcoveredslow", new SnowCoveredSlowBuff());
        Debuffs.FLOUR_COVERED_SLOW_DEBUFF = BuffRegistry.registerBuff("flourcoveredslow", new FlourCoveredSlowBuff());
        Debuffs.HAUNTED = BuffRegistry.registerBuff("haunted", new HauntedBuff());
        Debuffs.EMERALD_POISON = BuffRegistry.registerBuff("emeraldpoison", new EmeraldPoisonBuff());
        Debuffs.RUNIC_HAT_COOLDOWN = BuffRegistry.registerBuff("runichatcooldown", new ShownCooldownBuff());
        Debuffs.GUARDIAN_SHELL_COOLDOWN = BuffRegistry.registerBuff("guardianshellcooldown", new ShownCooldownBuff());
        Debuffs.NECROTIC_SOUL_SKULL_COOLDOWN = BuffRegistry.registerBuff("necroticsoulskullcooldown", new ShownCooldownBuff());
        Debuffs.ANCESTOR_SET_COOLDOWN = BuffRegistry.registerBuff("ancestorsetcooldown", new ShownCooldownBuff());
        Debuffs.ANCIENT_FOSSIL_SET_COOLDOWN = BuffRegistry.registerBuff("ancientfossilsetcooldown", new ShownCooldownBuff());
        Debuffs.SLIME_SET_COOLDOWN = BuffRegistry.registerBuff("slimesetcooldown", new ShownCooldownBuff());
        Debuffs.NIGHTSTEEL_SET_COOLDOWN = BuffRegistry.registerBuff("nightsteelsetcooldown", new ShownCooldownBuff());
        Debuffs.SPIDERITE_SET_COOLDOWN = BuffRegistry.registerBuff("spideritesetcooldown", new ShownCooldownBuff());
        Debuffs.SAPPHIRE_SET_COOLDOWN = BuffRegistry.registerBuff("sapphiresetcooldown", new ShownCooldownBuff());
        Debuffs.SPIDER_CHARM_POISON = BuffRegistry.registerBuff("spidercharmpoison", new SpiderCharmPoisonBuff());
        Debuffs.SLIME_POISON = BuffRegistry.registerBuff("slimepoison", new SlimePoisonBuff());
        Debuffs.SAND_KNIFE_WOUND_BUFF = BuffRegistry.registerBuff("sandknifewound", new SandKnifeWoundBuff());
        Debuffs.CRYSTALLIZE_BUFF = BuffRegistry.registerBuff("crystallize", new CrystallizeBuff());
        Debuffs.BLOOD_GRIMOIRE_MARKED_DEBUFF = BuffRegistry.registerBuff("bloodgrimoiredebuff", new BloodGrimoireMarkedBuff());
        Debuffs.SLIME_GREATBOW_SLOW_TARGET_DEBUFF = BuffRegistry.registerBuff("slimegreatbowdebuff", new SlimeGreatbowSlowTargetBuff());
        Debuffs.BLOOD_GRIMOIRE_COOLDOWN = BuffRegistry.registerBuff("bloodgrimoirecooldown", new ShownItemCooldownBuff(1, true, "items/bloodgrimoire"));
        Debuffs.THE_CRIMSON_SKY_COOLDOWN = BuffRegistry.registerBuff("thecrimsonskycooldown", new ShownItemCooldownBuff(1, true, "items/thecrimsonsky"));
        Debuffs.RAVENBEAK_SPEAR_COOLDOWN = BuffRegistry.registerBuff("ravenbeakspearcooldown", new ShownItemCooldownBuff(1, true, "items/ravenbeakspear"));
        Debuffs.CRUSHING_DARKNESS = BuffRegistry.registerBuff("crushingdarkness", new CrushingDarknessBuff());
        Debuffs.KATANA_DASH_COOLDOWN = BuffRegistry.registerBuff("katanadashcooldown", new ShownCooldownBuff());
        Debuffs.RUNEBOUND_SCEPTER_COOLDOWN = BuffRegistry.registerBuff("runeboundsceptercooldown", new ShownCooldownBuff());
        Debuffs.CAPTORS_SHORTBOW_COOLDOWN = BuffRegistry.registerBuff("captorsshortbowcooldown", new ShownItemCooldownBuff(1, true, "items/captorsshortbow"));
        Debuffs.NETTED_DEBUFF = BuffRegistry.registerBuff("netted", new NettedBuff());
        Debuffs.DRYAD_HAUNTED = BuffRegistry.registerBuff("dryadhaunted", new DryadHauntedBuff());
        Debuffs.DRYAD_POSSESSED = BuffRegistry.registerBuff("dryadpossessed", new DryadPossessedBuff());
        Debuffs.SPIRIT_HAUNTED = BuffRegistry.registerBuff("spirithaunted", new SpiritHauntedBuff());
        Debuffs.SPIRIT_POSSESSED = BuffRegistry.registerBuff("spiritpossessed", new SpiritPossessedBuff());
        Debuffs.STUNNED_DAMAGE_TAKEN_INCREASED = BuffRegistry.registerBuff("stunneddamagetakenincreased", new StunnedDamageTakenIncreassedBuff());
        Debuffs.SPIRIT_CORRUPTED = BuffRegistry.registerBuff("spiritcorrupted", new SpiritCorruptedBuff());
        Debuffs.DEMONIC_SET_COOLDOWN = BuffRegistry.registerBuff("demonicsetcooldown", new ShownCooldownBuff());
        Debuffs.SOULSEED_COOLDOWN = BuffRegistry.registerBuff("soulseedcooldown", new ShownCooldownBuff());
        Debuffs.THIEF_THROW_COOLDOWN = BuffRegistry.registerBuff("thiefthrowcooldown", new ShownCooldownBuff());
        Debuffs.THIEF_STEAL_COOLDOWN = BuffRegistry.registerBuff("thiefstealcooldown", new HiddenCooldownBuff());
        Debuffs.PERFECT_STORM_ONHIT_COOLDOWN = BuffRegistry.registerBuff("perfectstormonhitcooldown", new HiddenCooldownBuff());
        Debuffs.PERFECT_STORM_ABILITY_COOLDOWN = BuffRegistry.registerBuff("perfectstormabilitycooldown", new ShownCooldownBuff());
        Debuffs.CRYOWITCH_COOLDOWN = BuffRegistry.registerBuff("cryowitchcooldown", new ShownCooldownBuff());
        Debuffs.CRYOWITCH_COOLDOWN_ONHIT = BuffRegistry.registerBuff("cryowitchcooldownonhit", new HiddenCooldownBuff());
        Debuffs.ASCENDED_DARKNESS = BuffRegistry.registerBuff("ascendeddarkness", new AscendedDarknessBuff());
        Debuffs.GENERIC_ICE_SLOW = BuffRegistry.registerBuff("genericiceslowdebuff", new SimpleDebuff(new Color(111, 246, 246), "genericiceslowdebuff", new ModifierValue<Float>(BuffModifiers.SLOW, Float.valueOf(0.3f))));
        Debuffs.GENERIC_ONFIRE = BuffRegistry.registerBuff("genericonfiredebuff", new SimpleDebuff(new Color(227, 72, 13), "genericonfiredebuff", new ModifierValue<Float>(BuffModifiers.FIRE_DAMAGE_FLAT, Float.valueOf(5.0f))));
        Debuffs.GENERIC_POISON = BuffRegistry.registerBuff("genericpoisondebuff", new SimpleDebuff(new Color(111, 67, 187), "genericpoisondebuff", new ModifierValue<Float>(BuffModifiers.POISON_DAMAGE_FLAT, Float.valueOf(5.0f))));
        Debuffs.GENERIC_DAMAGE_DEBUFF = BuffRegistry.registerBuff("genericdamagedebuff", new SimpleDebuff(new Color(150, 150, 150), "genericdamagedebuff", new ModifierValue<Float>(BuffModifiers.ALL_DAMAGE, Float.valueOf(-0.2f))));
        Debuffs.GENERIC_WEAKNESS = BuffRegistry.registerBuff("genericweaknessdebuff", new SimpleDebuff(new Color(150, 150, 150), "genericweaknessdebuff", new ModifierValue<Float>(BuffModifiers.INCOMING_DAMAGE_MOD, Float.valueOf(0.2f))));
        Debuffs.GENERIC_ATTACKSPEED_SLOW = BuffRegistry.registerBuff("genericattackspeeddebuff", new SimpleDebuff(new Color(194, 242, 246), "genericattackspeeddebuff", new ModifierValue<Float>(BuffModifiers.ATTACK_SPEED, Float.valueOf(-0.3f))));
        Debuffs.POLYMORPH_CHICKEN = BuffRegistry.registerBuff("chickenpolymorph", new PolymorphBuff("chickenpolymorph"));
        Debuffs.POLYMORPH_FROG = BuffRegistry.registerBuff("frogpolymorph", new PolymorphBuff("frogpolymorph"));
        Debuffs.POLYMORPH_RABBIT = BuffRegistry.registerBuff("rabbitpolymorph", new PolymorphBuff("rabbitpolymorph"));
        Debuffs.POLYMORPH_DUCK = BuffRegistry.registerBuff("duckpolymorph", new PolymorphBuff("duckpolymorph"));
        Debuffs.POLYMORPH_TURTLE = BuffRegistry.registerBuff("turtlepolymorph", new PolymorphBuff("turtlepolymorph"));
        Debuffs.POLYMORPH_ROOSTER = BuffRegistry.registerBuff("roosterpolymorph", new PolymorphBuff("roosterpolymorph"));
        Debuffs.POLYMORPH_SQUIRREL = BuffRegistry.registerBuff("squirrelpolymorph", new PolymorphBuff("squirrelpolymorph"));
        Debuffs.SECOND_BOSS_WATCHING = BuffRegistry.registerBuff("secondbosswatching", new SecondBossWatchingBuff());
        SetBonuses.LEATHER = BuffRegistry.registerBuff("leathersetbonus", new SimpleUpgradeSetBonusBuff(new ModifierUpgradeValue<Float>(BuffModifiers.ATTACK_SPEED, new FloatUpgradeValue().setBaseValue(0.1f).setUpgradedValue(1.0f, 0.25f))));
        SetBonuses.CLOTH_ROBE = BuffRegistry.registerBuff("clothrobesetbonus", new SimpleUpgradeSetBonusBuff(new ModifierUpgradeValue<Float>(BuffModifiers.MAGIC_DAMAGE, new FloatUpgradeValue().setBaseValue(0.15f).setUpgradedValue(1.0f, 0.25f)), new ModifierUpgradeValue<Integer>(BuffModifiers.MAX_MANA_FLAT, new IntUpgradeValue(0, 0.1f).setBaseValue(30).setUpgradedValue(1.0f, 250))));
        SetBonuses.COPPER = BuffRegistry.registerBuff("coppersetbonus", new SimpleUpgradeSetBonusBuff(new ModifierUpgradeValue<Integer>(BuffModifiers.ARMOR_FLAT, new IntUpgradeValue().setBaseValue(1).setUpgradedValue(1.0f, 6))));
        SetBonuses.IRON = BuffRegistry.registerBuff("ironsetbonus", new SimpleUpgradeSetBonusBuff(new ModifierUpgradeValue<Integer>(BuffModifiers.ARMOR_FLAT, new IntUpgradeValue().setBaseValue(1).setUpgradedValue(1.0f, 6))));
        SetBonuses.GOLD_CROWN = BuffRegistry.registerBuff("goldcrownsetbonus", new SimpleUpgradeSetBonusBuff(new ModifierUpgradeValue<Integer>(BuffModifiers.MAX_SUMMONS, new IntUpgradeValue().setBaseValue(1).setUpgradedValue(1.0f, 2))));
        SetBonuses.GOLD = BuffRegistry.registerBuff("goldsetbonus", new SimpleUpgradeSetBonusBuff(new ModifierUpgradeValue<Integer>(BuffModifiers.ARMOR_FLAT, new IntUpgradeValue().setBaseValue(2).setUpgradedValue(1.0f, 6))));
        SetBonuses.SPIDER = BuffRegistry.registerBuff("spidersetbonus", new SpiderSetBonusBuff());
        SetBonuses.FROST_HELMET = BuffRegistry.registerBuff("frostsetbonus", new FrostSetBonusBuff());
        SetBonuses.FROST_HOOD = BuffRegistry.registerBuff("frosthoodsetbonus", new SimpleUpgradeSetBonusBuff(new ModifierUpgradeValue<Float>(BuffModifiers.CRIT_CHANCE, new FloatUpgradeValue().setBaseValue(0.1f).setUpgradedValue(1.0f, 0.2f)), new ModifierUpgradeValue<Float>(BuffModifiers.PROJECTILE_VELOCITY, new FloatUpgradeValue().setBaseValue(0.5f).setUpgradedValue(1.0f, 1.0f))));
        SetBonuses.FROST_HAT = BuffRegistry.registerBuff("frosthatsetbonus", new SimpleUpgradeSetBonusBuff(new ModifierUpgradeValue<Float>(BuffModifiers.MAGIC_CRIT_CHANCE, new FloatUpgradeValue().setBaseValue(0.1f).setUpgradedValue(1.0f, 0.2f)), new ModifierUpgradeValue<Integer>(BuffModifiers.MAX_MANA_FLAT, new IntUpgradeValue(0, 0.1f).setBaseValue(60).setUpgradedValue(1.0f, 250))));
        SetBonuses.DEMONIC = BuffRegistry.registerBuff("demonicsetbonus", new DemonicSetBonusBuff());
        SetBonuses.VOIDMASK = BuffRegistry.registerBuff("voidmasksetbonus", new VoidMaskSetBonusBuff());
        SetBonuses.VOIDHAT = BuffRegistry.registerBuff("voidhatsetbonus", new VoidHatSetBonusBuff());
        SetBonuses.NINJA = BuffRegistry.registerBuff("ninjasetbonus", new NinjaSetBonusBuff());
        SetBonuses.WITCH_ROBES = BuffRegistry.registerBuff("witchrobessetbonus", new WitchRobesSetBonusBuff());
        SetBonuses.CRYOWITCH = BuffRegistry.registerBuff("cryowitchsetbonus", new CryoWitchSetBonusBuff());
        SetBonuses.RUNIC = BuffRegistry.registerBuff("runicsetbonus", new RunicSetBonusBuff());
        SetBonuses.RUNICHAT = BuffRegistry.registerBuff("runichatsetbonus", new RunicHatSetBonusBuff());
        SetBonuses.IVYHELMET = BuffRegistry.registerBuff("ivyhelmetsetbonus", new IvyHelmetSetBonusBuff());
        SetBonuses.IVYHOOD = BuffRegistry.registerBuff("ivyhoodsetbonus", new IvyHoodSetBonusBuff());
        SetBonuses.IVYHAT = BuffRegistry.registerBuff("ivyhatsetbonus", new IvyHatSetBonusBuff());
        SetBonuses.IVYCIRCLET = BuffRegistry.registerBuff("ivycircletsetbonus", new IvyCircletSetBonusBuff());
        SetBonuses.QUARTZHELMET = BuffRegistry.registerBuff("quartzhelmetsetbonus", new QuartzHelmetSetBonusBuff());
        SetBonuses.QUARTZCROWN = BuffRegistry.registerBuff("quartzcrownsetbonus", new QuartzCrownSetBonusBuff());
        SetBonuses.GUNSLINGER = BuffRegistry.registerBuff("gunslingersetbonus", new GunslingerSetBonusBuff());
        SetBonuses.TUNGSTEN = BuffRegistry.registerBuff("tungstensetbonus", new TungstenSetBonusBuff());
        SetBonuses.SHADOWHOOD = BuffRegistry.registerBuff("shadowhoodsetbonus", new ShadowHoodSetBonusBuff());
        SetBonuses.SHADOWHAT = BuffRegistry.registerBuff("shadowhatsetbonus", new ShadowHatSetBonusBuff());
        SetBonuses.GLACIALHELMET = BuffRegistry.registerBuff("glacialhelmetsetbonus", new GlacialHelmetBonusBuff());
        SetBonuses.GLACIALCIRCLET = BuffRegistry.registerBuff("glacialcircletsetbonus", new GlacialCircletBonusBuff());
        SetBonuses.DRYAD_HELMET = BuffRegistry.registerBuff("dryadhelmetsetbonus", new DryadHelmetSetBonusBuff());
        SetBonuses.DRYAD_SCARF = BuffRegistry.registerBuff("dryadscarfsetbonus", new DryadScarfSetBonusBuff());
        SetBonuses.DRYAD_HAT = BuffRegistry.registerBuff("dryadhatsetbonus", new DryadHatSetBonusBuff());
        SetBonuses.DRYAD_CROWN = BuffRegistry.registerBuff("dryadcrownsetbonus", new DryadCrownSetBonusBuff());
        SetBonuses.MYCELIUMHOOD = BuffRegistry.registerBuff("myceliumhoodsetbonus", new MyceliumHoodSetBonusBuff());
        SetBonuses.MYCELIUMSCARF = BuffRegistry.registerBuff("myceliumscarfsetbonus", new MyceliumScarfSetBonusBuff());
        SetBonuses.WIDOW = BuffRegistry.registerBuff("widowsetbonus", new WidowSetBonusBuff());
        SetBonuses.AGED_CHAMPION = BuffRegistry.registerBuff("agedchampionsetbonus", new AgedChampionSetBonusBuff());
        SetBonuses.ANCESTOR = BuffRegistry.registerBuff("ancestorsetbonus", new AncestorSetBonusBuff());
        SetBonuses.ANCIENT_FOSSIL_HELMET = BuffRegistry.registerBuff("ancientfossilhelmetsetbonus", new AncientFossilHelmetSetBonusBuff());
        SetBonuses.ANCIENT_FOSSIL_MASK = BuffRegistry.registerBuff("ancientfossilmasksetbonus", new AncientFossilMaskSetBonusBuff());
        SetBonuses.SHARPSHOOTER = BuffRegistry.registerBuff("sharpshootersetbonus", new SharpshooterSetBonusBuff());
        SetBonuses.SLIMEHELMET = BuffRegistry.registerBuff("slimehelmetsetbonus", new SlimeHelmetSetBonusBuff());
        SetBonuses.SLIMEHAT = BuffRegistry.registerBuff("slimehatsetbonus", new SlimeHatSetBonusBuff());
        SetBonuses.NIGHTSTEEL = BuffRegistry.registerBuff("nightsteelsetbonus", new NightSteelSetBonusBuff());
        SetBonuses.NIGHTSTEEL_HELMET = BuffRegistry.registerBuff("nightsteelhelmetsetbonus", new NightSteelHelmetSetBonusBuff());
        SetBonuses.NIGHTSTEEL_VEIL = BuffRegistry.registerBuff("nightsteelveilsetbonus", new NightSteelVeilSetBonusBuff());
        SetBonuses.NIGHTSTEEL_CIRCLET = BuffRegistry.registerBuff("nightsteelcircletsetbonus", new NightSteelCircletSetBonusBuff());
        SetBonuses.BLOODPLATE_COWL = BuffRegistry.registerBuff("bloodplatecowlsetbonus", new BloodplateCowlSetBonusBuff());
        SetBonuses.SPIDERITE = BuffRegistry.registerBuff("spideritesetbonus", new SpideriteSetBonusBuff());
        SetBonuses.BATTLE_CHEF = BuffRegistry.registerBuff("battlechefsetbonus", new BattleChefSetBonusBuff());
        SetBonuses.SPIDERITE_HELMET = BuffRegistry.registerBuff("spideritehelmetsetbonus", new SpideriteHelmetSetBonusBuff());
        SetBonuses.SPIDERITE_HAT = BuffRegistry.registerBuff("spideritehatsetbonus", new SpideriteHatSetBonusBuff());
        SetBonuses.SPIDERITE_CROWN = BuffRegistry.registerBuff("spideritecrownsetbonus", new SpideriteCrownSetBonusBuff());
        SetBonuses.RAVENLORDS_HEADDRESS = BuffRegistry.registerBuff("ravenlordsheaddresssetbonus", new RavenlordsHeaddressSetBonusBuff());
        SetBonuses.DAWN = BuffRegistry.registerBuff("dawnsetbonus", new DawnSetBonusBuff());
        SetBonuses.DUSK = BuffRegistry.registerBuff("dusksetbonus", new DuskSetBonusBuff());
        SetBonuses.AMETHYST = BuffRegistry.registerBuff("amethystsetbonus", new AmethystSetBonusBuff());
        SetBonuses.SAPPHIRE = BuffRegistry.registerBuff("sapphiresetbonus", new SapphireSetBonusBuff());
        SetBonuses.EMERALD = BuffRegistry.registerBuff("emeraldsetbonus", new EmeraldSetBonusBuff());
        SetBonuses.RUBY = BuffRegistry.registerBuff("rubysetbonus", new RubySetBonusBuff());
        SetBonuses.ARCANIC_HOOD = BuffRegistry.registerBuff("arcanichelmetsetbonus", new ArcanicHelmetSetBonusBuff());
        SetBonuses.ARACHNID = BuffRegistry.registerBuff("arachnidsetbonus", new ArachnidSetBonusBuff());
        SetBonuses.GHOSTLY_ARCHER = BuffRegistry.registerBuff("deepfrostsetbonus", new DeepfrostSetBonusBuff());
        SetBonuses.SOULSEED = BuffRegistry.registerBuff("soulseedcrownsetbonus", new SoulseedCrownSetBonusBuff());
        SetBonuses.SOLDIERHELMET = BuffRegistry.registerBuff("soldierhelmetsetbonus", new SoldierHelmetSetBonusBuff());
        SetBonuses.SOLDIERCAP = BuffRegistry.registerBuff("soldiercapsetbonus", new SoldierCapSetBonusBuff());
        SetBonuses.THIEF = BuffRegistry.registerBuff("thiefsetbonus", new ThiefSetBonusBuff());
        SetBonuses.PHARAOH = BuffRegistry.registerBuff("pharaohssetbonus", new PharaohsSetBonusBuff());
        SetBonuses.SUPPORTER = BuffRegistry.registerBuff("supportersetbonus", new SupporterSetBonusBuff());
        BuffRegistry.registerBuff("ninjasmarktrinket", new NinjasMarkBuff());
        BuffRegistry.registerBuff("leatherglovetrinket", new SimpleTrinketBuff("leatherglovetip", new ModifierValue<Float>(BuffModifiers.ATTACK_SPEED, Float.valueOf(0.1f))));
        BuffRegistry.registerBuff("trackerboottrinket", new SimpleTrinketBuff("trackerboottip", new ModifierValue<Float>(BuffModifiers.SPEED, Float.valueOf(0.1f))));
        BuffRegistry.registerBuff("shinebelttrinket", new ShineBeltBuff());
        BuffRegistry.registerBuff("vampiresgifttrinket", new SimpleTrinketBuff("vampiresgift", new ModifierValue<Float>(BuffModifiers.SPEED, Float.valueOf(0.15f))));
        BuffRegistry.registerBuff("zephyrcharmtrinket", new SimpleTrinketBuff("zephyrcharmtip", new ModifierValue<Float>(BuffModifiers.STAMINA_CAPACITY, Float.valueOf(0.5f))));
        BuffRegistry.registerBuff("demonclawtrinket", new SimpleTrinketBuff("demonclawtip", new ModifierValue<Float>(BuffModifiers.KNOCKBACK_INCOMING_MOD).max(Float.valueOf(0.0f))));
        BuffRegistry.registerBuff("polarclawtrinket", new PolarClawBuff());
        BuffRegistry.registerBuff("finstrinket", new FinsBuff());
        BuffRegistry.registerBuff("piratetelescopetrinket", new SimpleTrinketBuff("piratetelescopemap", new ModifierValue<Boolean>(BuffModifiers.EXTENDED_MAP_DISCOVER_RANGE, true)));
        BuffRegistry.registerBuff("regenpendanttrinket", new SimpleTrinketBuff("regenpendant", new ModifierValue<Float>(BuffModifiers.COMBAT_HEALTH_REGEN_FLAT, Float.valueOf(0.5f))));
        BuffRegistry.registerBuff("mobilitycloaktrinket", new MobilityCloakBuff());
        BuffRegistry.registerBuff("travelercloaktrinket", new TravelerCloakBuff());
        BuffRegistry.registerBuff("explorercloaktrinket", new ExplorerCloakBuff());
        BuffRegistry.registerBuff("mesmertablettrinket", new SimpleTrinketBuff(new ModifierValue<Integer>(BuffModifiers.MAX_SUMMONS, 1)));
        BuffRegistry.registerBuff("inducingamulettrinket", new SimpleTrinketBuff(new ModifierValue<Float>(BuffModifiers.SUMMONS_SPEED, Float.valueOf(0.3f))));
        BuffRegistry.registerBuff("lifelinettrinket", new LifelineBuff());
        BuffRegistry.registerBuff("magicfocitrinket", new MagicFociBuff());
        BuffRegistry.registerBuff("rangefocitrinket", new RangeFociBuff());
        BuffRegistry.registerBuff("meleefocitrinket", new MeleeFociBuff());
        BuffRegistry.registerBuff("summonfocitrinket", new SummonFociBuff());
        BuffRegistry.registerBuff("balancedfocitrinket", new BalancedFociBuff());
        BuffRegistry.registerBuff("ancientfeathertrinket", new SimpleTrinketBuff("ancientfeather", new ModifierValue<Float>(BuffModifiers.PROJECTILE_VELOCITY, Float.valueOf(0.5f))));
        BuffRegistry.registerBuff("airvesseltrinket", new SimpleTrinketBuff("airvesseltip", new ModifierValue<Integer>(BuffModifiers.DASH_STACKS, 2)));
        BuffRegistry.registerBuff("miningcharmtrinket", new SimpleTrinketBuff("miningcharm", new ModifierValue<Float>(BuffModifiers.TOOL_DAMAGE, Float.valueOf(0.4f))));
        BuffRegistry.registerBuff("minersbouquettrinket", new SimpleTrinketBuff(new String[]{"miningcharm", "minersbouquettip"}, new ModifierValue<Float>(BuffModifiers.TOOL_DAMAGE, Float.valueOf(0.4f)), new ModifierValue<Float>(BuffModifiers.MINING_SPEED, Float.valueOf(0.25f))));
        BuffRegistry.registerBuff("calmingminersbouquettrinket", new SimpleTrinketBuff(new String[]{"miningcharm", "minersbouquettip", "calmingrose"}, new ModifierValue<Float>(BuffModifiers.TOOL_DAMAGE, Float.valueOf(0.4f)), new ModifierValue<Float>(BuffModifiers.MINING_SPEED, Float.valueOf(0.25f)), new ModifierValue<Float>(BuffModifiers.MOB_SPAWN_RATE).max(Float.valueOf(0.4f))));
        BuffRegistry.registerBuff("magicalquivertrinket", new SimpleTrinketBuff("magicalquiver", new ModifierValue<Float>(BuffModifiers.ARROW_USAGE, Float.valueOf(-0.75f))));
        BuffRegistry.registerBuff("ammoboxtrinket", new SimpleTrinketBuff("ammobox", new ModifierValue<Float>(BuffModifiers.BULLET_USAGE, Float.valueOf(-0.75f))));
        BuffRegistry.registerBuff("bonehilttrinket", new SimpleTrinketBuff("bonehilt", new ModifierValue<Integer>(BuffModifiers.ARMOR_PEN_FLAT, 20)));
        BuffRegistry.registerBuff("firestonetrinket", new FireStoneBuff());
        BuffRegistry.registerBuff("lifependanttrinket", new SimpleTrinketBuff("lifependant", new ModifierValue<Float>(BuffModifiers.COMBAT_HEALTH_REGEN_FLAT, Float.valueOf(1.0f))));
        BuffRegistry.registerBuff("constructionhammertrinket", new SimpleTrinketBuff("constructionhammer", new ModifierValue<Float>(BuffModifiers.BUILDING_SPEED, Float.valueOf(0.5f))));
        BuffRegistry.registerBuff("telescopicladdertrinket", new SimpleTrinketBuff("telescopicladder", new ModifierValue<Float>(BuffModifiers.BUILD_RANGE, Float.valueOf(1.0f))));
        BuffRegistry.registerBuff("toolextendertrinket", new SimpleTrinketBuff("toolextender", new ModifierValue<Float>(BuffModifiers.MINING_RANGE, Float.valueOf(1.0f))));
        BuffRegistry.registerBuff("itemattractortrinket", new SimpleTrinketBuff("itemattractortip", new ModifierValue<Float>(BuffModifiers.ITEM_PICKUP_RANGE, Float.valueOf(5.0f))));
        BuffRegistry.registerBuff("minersprosthetictrinket", new MinersProstheticTrinketBuff());
        BuffRegistry.registerBuff("leatherdasherstrinket", new LeatherDashersTrinketBuff());
        BuffRegistry.registerBuff("zephyrbootstrinket", new ZephyrBootsTrinketBuff());
        BuffRegistry.registerBuff("windbootstrinket", new WindBootsTrinketBuff());
        BuffRegistry.registerBuff("hoverbootstrinket", new HoverBootsTrinketBuff());
        BuffRegistry.registerBuff("ghostbootstrinket", new GhostBootsTrinketBuff());
        BuffRegistry.registerBuff("kineticbootstrinket", new KineticBootsTrinketBuff());
        BuffRegistry.registerBuff("forceofwindtrinket", new ForceOfWindTrinketBuff());
        BuffRegistry.registerBuff("shieldtrinket", new ShieldTrinketBuff());
        BuffRegistry.registerBuff("blinksceptertrinket", new BlinkScepterTrinketBuff());
        BuffRegistry.registerBuff("spikedbootstrinket", new SimpleTrinketBuff("spikedboots", new ModifierValue<Float>(BuffModifiers.FRICTION, Float.valueOf(0.0f)).min(Float.valueOf(1.0f)), new ModifierValue<Float>(BuffModifiers.SPEED, Float.valueOf(0.15f))));
        BuffRegistry.registerBuff("spikedbatbootstrinket", new SimpleTrinketBuff("spikedbatboots", new ModifierValue<Float>(BuffModifiers.FRICTION, Float.valueOf(0.0f)).min(Float.valueOf(1.0f)), new ModifierValue<Float>(BuffModifiers.SPEED, Float.valueOf(0.25f))));
        BuffRegistry.registerBuff("froststonetrinket", new FrostStoneBuff());
        BuffRegistry.registerBuff("frostflametrinket", new FrostFlameBuff());
        BuffRegistry.registerBuff("calmingrosetrinket", new SimpleTrinketBuff("calmingrose", new ModifierValue<Float>(BuffModifiers.MOB_SPAWN_RATE).max(Float.valueOf(0.4f))));
        BuffRegistry.registerBuff("hysteriatablettrinket", new SimpleTrinketBuff(new ModifierValue<Integer>(BuffModifiers.MAX_SUMMONS, 2), new ModifierValue<Float>(BuffModifiers.SUMMONS_SPEED, Float.valueOf(0.3f))));
        BuffRegistry.registerBuff("frenzyorbtrinket", new FrenzyOrbBuff());
        BuffRegistry.registerBuff("frozenhearttrinket", new SimpleTrinketBuff("frozenhearttip", new ModifierValue<Integer>(BuffModifiers.MAX_HEALTH_FLAT, 50)));
        BuffRegistry.registerBuff("frozenwavetrinket", new SimpleTrinketBuff("frozenwavetip", new ModifierValue<Float>(BuffModifiers.CRIT_DAMAGE, Float.valueOf(0.25f))));
        BuffRegistry.registerBuff("fuzzydicetrinket", new SimpleTrinketBuff("fuzzydicetip", new ModifierValue<Float>(BuffModifiers.CRIT_CHANCE, Float.valueOf(0.05f))));
        BuffRegistry.registerBuff("noblehorseshoetrinket", new SimpleTrinketBuff("noblehorseshoetip", new ModifierValue<Float>(BuffModifiers.CRIT_CHANCE, Float.valueOf(0.05f))));
        BuffRegistry.registerBuff("luckycapetrinket", new SimpleTrinketBuff("luckycapetip", new ModifierValue<Float>(BuffModifiers.CRIT_CHANCE, Float.valueOf(0.1f))));
        BuffRegistry.registerBuff("guardianshelltrinket", new GuardianShellTrinketBuff());
        BuffRegistry.registerBuff("necroticsoulskull", new NecroticSoulSkullTrinketBuff());
        BuffRegistry.registerBuff("scryingmirrortrinket", new SimpleTrinketBuff(new ModifierValue<Integer>(BuffModifiers.MAX_SUMMONS, 1)));
        BuffRegistry.registerBuff("diggingclawtrinket", new SimpleTrinketBuff(new ModifierValue<Float>(BuffModifiers.TOOL_DAMAGE, Float.valueOf(0.5f)), new ModifierValue<Float>(BuffModifiers.MINING_SPEED, Float.valueOf(0.5f)), new ModifierValue<Float>(BuffModifiers.MINING_RANGE, Float.valueOf(-2.0f))));
        BuffRegistry.registerBuff("spidercharmtrinket", new SpiderCharmBuff());
        BuffRegistry.registerBuff("templependanttrinket", new SimpleTrinketBuff("templependanttip", new ModifierValue<Float>(BuffModifiers.DASH_COOLDOWN, Float.valueOf(-0.25f))));
        BuffRegistry.registerBuff("gelatincasingstrinket", new SimpleTrinketBuff("gelatincasingstip", new ModifierValue<Integer>(BuffModifiers.PROJECTILE_BOUNCES, 10)));
        BuffRegistry.registerBuff("ancientrelicstrinket", new SimpleTrinketBuff(new String[]{"airvesseltip", "templependanttip"}, new ModifierValue<Integer>(BuffModifiers.DASH_STACKS, 2), new ModifierValue<Float>(BuffModifiers.DASH_COOLDOWN, Float.valueOf(-0.25f))));
        BuffRegistry.registerBuff("sparegemstonestrinket", new SimpleTrinketBuff("sparegemstonestip", new ModifierValue<Float>(BuffModifiers.MAX_MANA, Float.valueOf(0.2f))));
        BuffRegistry.registerBuff("spellstonetrinket", new SimpleTrinketBuff("spellstonetip", new ModifierValue<Float>(BuffModifiers.MAX_MANA, Float.valueOf(0.5f))));
        BuffRegistry.registerBuff("companionlockettrinket", new CompanionLocketBuff());
        BuffRegistry.registerBuff("willowisplanterntrinket", new WillOWispLanternBuff());
        BuffRegistry.registerBuff("essenceofperspectivetrinket", new SimpleTrinketBuff("essenceofperspectivetip", new ModifierValue<Float>(BuffModifiers.LIFE_ESSENCE_GAIN, Float.valueOf(0.5f))));
        BuffRegistry.registerBuff("essenceofprolongingtrinket", new SimpleTrinketBuff("essenceofprolongingtip", new ModifierValue<Float>(BuffModifiers.LIFE_ESSENCE_DURATION, Float.valueOf(1.0f))));
        BuffRegistry.registerBuff("essenceofrebirthtrinket", new SimpleTrinketBuff("essenceofrebirthtip", new ModifierValue<Float>(BuffModifiers.LIFE_ESSENCE_GAIN, Float.valueOf(1.0f)), new ModifierValue<Float>(BuffModifiers.LIFE_ESSENCE_DURATION, Float.valueOf(1.0f))));
        BuffRegistry.registerBuff("dreamcatchertrinket", new SimpleTrinketBuff("dreamcatchertip", new ModifierValue<Float>(BuffModifiers.COMBAT_MANA_REGEN, Float.valueOf(1.0f))));
        BuffRegistry.registerBuff("nightmaretalismantrinket", new SimpleTrinketBuff("nightmaretalismantip", new ModifierValue<Float>(BuffModifiers.COMBAT_MANA_REGEN, Float.valueOf(2.5f))));
        BuffRegistry.registerBuff("prophecyslabtrinket", new SimpleTrinketBuff("prophecyslabtip", new ModifierValue<Float>(BuffModifiers.COMBAT_MANA_REGEN, Float.valueOf(1.0f))));
        BuffRegistry.registerBuff("magicmanualtrinket", new SimpleTrinketBuff("magicmanualtip", new ModifierValue<Float>(BuffModifiers.COMBAT_MANA_REGEN, Float.valueOf(1.0f))));
        BuffRegistry.registerBuff("scryingcardstrinket", new SimpleTrinketBuff("scryingcardstip", new ModifierValue<Float>(BuffModifiers.COMBAT_MANA_REGEN, Float.valueOf(2.5f))));
        BuffRegistry.registerBuff("forbiddenspellbooktrinket", new SimpleTrinketBuff("forbiddenspellbooktip", new ModifierValue<Float>(BuffModifiers.MAGIC_DAMAGE, Float.valueOf(0.5f)), new ModifierValue<Float>(BuffModifiers.MANA_USAGE, Float.valueOf(1.0f))));
        BuffRegistry.registerBuff("bloodstoneringtrinket", new BloodstoneRingBuff());
        BuffRegistry.registerBuff("cavelingsfoottrinket", new CavelingsFootBuff());
        BuffRegistry.registerBuff("cavelingscollectiontrinket", new CavelingsCollectionBuff());
        BuffRegistry.registerBuff("claygauntlettrinket", new SimpleTrinketBuff("claygauntlettip", new ModifierValue<Integer>(BuffModifiers.MAX_RESILIENCE_FLAT, 10), new ModifierValue<Float>(BuffModifiers.RESILIENCE_DECAY, Float.valueOf(-0.75f))));
        BuffRegistry.registerBuff("vambracetrinket", new SimpleTrinketBuff("vambracetip", new ModifierValue<Float>(BuffModifiers.RESILIENCE_GAIN, Float.valueOf(0.5f))));
        BuffRegistry.registerBuff("chainshirttrinket", new SimpleTrinketBuff("chainshirttip", new ModifierValue<Integer>(BuffModifiers.MAX_RESILIENCE_FLAT, 30)));
        BuffRegistry.registerBuff("manicatrinket", new SimpleTrinketBuff("manicatip", new ModifierValue<Integer>(BuffModifiers.MAX_RESILIENCE_FLAT, 50), new ModifierValue<Float>(BuffModifiers.RESILIENCE_GAIN, Float.valueOf(0.5f))));
        BuffRegistry.registerBuff("clockworkhearttrinket", new ClockworkHeartBuff());
        BuffRegistry.registerBuff("agedchampionscabbardtrinket", new AgedChampionScabbardBuff());
        BuffRegistry.registerBuff("challengerspauldrontrinket", new ChallengersPauldronBuff());
        BuffRegistry.registerBuff("foolsgambittrinket", new FoolsGambitTrinketBuff());
        BuffRegistry.registerBuff("spiritboardtrinket", new SpiritBoardTrinketBuff());
        BuffRegistry.registerBuff("guardianbracelettrinket", new GuardianBraceletTrinketBuff());
        BuffRegistry.registerBuff("secondwindcharmtrinket", new SecondWindTrinketBuff());
        BuffRegistry.registerBuff("summonersbestiarytrinket", new SummonersBestiaryTrinketBuff());
        BuffRegistry.registerBuff("spiritgreavestrinket", new SpiritGreavesTrinketBuff());
        BuffRegistry.registerBuff("voodooshieldtrinket", new VoodooShieldTrinketBuff());
        BuffRegistry.registerBuff("voidphasingstafftrinket", new VoidPhasingStaffTrinketBuff());
        Banners.SPEED = BuffRegistry.registerBuff("bannerofspeed", new BannerOfSpeedBuff());
        Banners.DAMAGE = BuffRegistry.registerBuff("bannerofdamage", new BannerOfDamageBuff());
        Banners.SUMMON_SPEED = BuffRegistry.registerBuff("bannerofsummonspeed", new BannerOfSummonSpeedBuff());
        Banners.DEFENSE = BuffRegistry.registerBuff("bannerofdefense", new BannerOfDefenseBuff());
        Banners.PEACE = BuffRegistry.registerBuff("bannerofpeace", new BannerOfPeaceBuff());
        FRENZY = BuffRegistry.registerBuff("frenzy", new FrenzyBuff());
        TREMORS_INCOMING = BuffRegistry.registerBuff("tremorincoming", new TremorsIncomingBuff());
        TREMOR_HAPPENING = BuffRegistry.registerBuff("tremorhappening", new TremorHappeningBuff());
        ALCHEMICAL_INTERFERENCE = BuffRegistry.registerBuff("alchemicalinterference", new AlchemicalInterferenceBuff());
        PERK_FLAMELINGS_CAN_DIE = BuffRegistry.registerBuff("perkflamelingscandie", new PerkFlamelingsCanDieBuff());
        SECOND_LIFE_PERK = BuffRegistry.registerBuff("secondlifeperk", new SecondLifePerkBuff());
        PIRATE_ESCAPE = BuffRegistry.registerBuff("pirateescape", new PirateEscapeBuff());
        PIRATE_PASSIVE = BuffRegistry.registerBuff("piratepassive", new PiratePassiveBuff());
        SUMMONED_PET = BuffRegistry.registerBuff("summonedpet", new SummonedPetBuff());
        SUMMONED_MOUNT = BuffRegistry.registerBuff("summonedmount", new SummonedMountBuff());
        SUMMONED_MOB = BuffRegistry.registerBuff("summonedmob", new SummonedMobBuff());
        HUMAN_ANGRY = BuffRegistry.registerBuff("humanangry", new HumanAngryBuff());
        MOVE_SPEED_BURST = BuffRegistry.registerBuff("movespeedburst", new MoveSpeedBurstBuff());
        BOSS_NEARBY = BuffRegistry.registerBuff("bossnearby", new BossNearbyBuff());
        SETTLEMENT_FLAG = BuffRegistry.registerBuff("settlementflag", new SettlementFlagBuff());
        CAMPFIRE = BuffRegistry.registerBuff("campfire", new CampfireBuff());
        SHADOWHOOD_SET = BuffRegistry.registerBuff("shadowhoodset", new ShadowHoodSetBuff());
        SPIDER_CHARGE = BuffRegistry.registerBuff("spidercharge", new SimpleModifierBuff(false, true, false, true, new ModifierValue<Float>(BuffModifiers.SPEED, Float.valueOf(0.75f))));
        HARDENED = BuffRegistry.registerBuff("hardened", new SimpleModifierBuff(false, true, false, true, new ModifierValue<Float>(BuffModifiers.INCOMING_DAMAGE_MOD, Float.valueOf(0.1f))));
        ANCIENT_FOSSIL_ACTIVE = BuffRegistry.registerBuff("ancientfossilactive", new SimpleModifierBuff(true, true, true, true, new ModifierValue<Float>(BuffModifiers.CRIT_CHANCE, Float.valueOf(1.0f))));
        SETTLER_SPRINT = BuffRegistry.registerBuff("settlersprint", new SettlerSprintBuff());
        FROZEN_MOB_IMMUNE = BuffRegistry.registerBuff("frozenmobimmune", new FrozenMobImmuneBuff());
        FROZEN_MOB = BuffRegistry.registerBuff("frozenmob", new FrozenMobBuff());
        THAWED_ENEMY = BuffRegistry.registerBuff("thawedenemy", new SimpleModifierBuff(false, true, false, true, new ModifierValue<Float>(BuffModifiers.CHASER_RANGE, Float.valueOf(3.0f))));
        LEATHER_DASHERS_ACTIVE = BuffRegistry.registerBuff("leatherdashersactive", new LeatherDashersActiveBuff());
        ZEPHYR_BOOTS_ACTIVE = BuffRegistry.registerBuff("zephyrbootsactive", new ZephyrBootsActiveBuff());
        WIND_BOOTS_ACTIVE = BuffRegistry.registerBuff("windbootsactive", new WindBootsActiveBuff());
        HOVER_BOOTS_ACTIVE = BuffRegistry.registerBuff("hoverbootsactive", new HoverBootsActiveBuff());
        GHOST_BOOTS_ACTIVE = BuffRegistry.registerBuff("ghostbootsactive", new GhostBootsActiveBuff());
        KINETIC_BOOTS_ACTIVE = BuffRegistry.registerBuff("kineticbootsactive", new KineticBootsActiveBuff());
        FOW_ACTIVE = BuffRegistry.registerBuff("fowactive", new ForceOfWindActiveBuff());
        INVULNERABLE_ACTIVE = BuffRegistry.registerBuff("ivulnerableactive", new InvulnerableActiveBuff());
        KATANA_DASH_STACKS = BuffRegistry.registerBuff("katanadashstacks", new KatanaDashStacksBuff());
        GHOST_DASH_ACTIVE = BuffRegistry.registerBuff("ghostdashactive", new GhostDashActiveBuff());
        RUNIC_EMPOWERMENT = BuffRegistry.registerBuff("runicempowerment", new RunicEmpowermentActiveBuff());
        GUARDIAN_SHELL_ACTIVE = BuffRegistry.registerBuff("guardianshellactive", new GuardianShellActiveBuff());
        SLIME_DOME_ACTIVE = BuffRegistry.registerBuff("slimedomeactive", new SlimeDomeActiveBuff());
        MYCELIUM_HOOD_ACTIVE = BuffRegistry.registerBuff("myceliumhoodactive", new MyceliumHoodActiveBuff());
        MYCELIUM_SCARF_ACTIVE = BuffRegistry.registerBuff("myceliumscarfactive", new MyceliumScarfActiveBuff());
        NIGHTSTEEL_ACTIVE = BuffRegistry.registerBuff("nightsteelactive", new NightsteelActiveBuff());
        SAPPHIRE_SET_ACTIVE = BuffRegistry.registerBuff("sapphireactive", new SapphireSetActiveBuff());
        SHIELD_ACTIVE = BuffRegistry.registerBuff("shieldActive", new ShieldActiveBuff());
        PERFECT_BLOCK = BuffRegistry.registerBuff("perfectblock", new PerfectBlockBuff());
        SLEEPING = BuffRegistry.registerBuff("sleeping", new SleepingBuff());
        SWAMP_SPORES = BuffRegistry.registerBuff("swampspores", new SwampSporesBuff());
        EQUIPMENT_BUFF = BuffRegistry.registerBuff("equipmentbuff", new StatsBuff());
        FOOD_BUFFS = new FoodBuff[10];
        for (int i = 0; i < FOOD_BUFFS.length; ++i) {
            BuffRegistry.FOOD_BUFFS[i] = BuffRegistry.registerBuff("foodbuff" + i, new FoodBuff(true));
        }
        FOOD_DEBUFF = BuffRegistry.registerBuff("fooddebuff", new FoodBuff(false));
        HUNGRY_BUFF = BuffRegistry.registerBuff("hungry", new HungryBuff());
        STARVING_BUFF = BuffRegistry.registerBuff("starving", new StarvingBuff());
        STAMINA_BUFF = BuffRegistry.registerBuff("stamina", new StaminaBuff());
        HOLD_ITEM_BUFF = BuffRegistry.registerBuff("holditem", new HoldItemBuff());
        BLOODPLATE_COWL_ACTIVE = BuffRegistry.registerBuff("bloodplatecowlactive", new BloodplateCowlActiveBuff());
        BLOOD_CLAW_STACKS_BUFF = BuffRegistry.registerBuff("bloodclaw", new BloodClawStacksBuff());
        BLOODSTONE_RING_REGEN_ACTIVE_BUFF = BuffRegistry.registerBuff("bloodstonering", new BloodstoneRingRegenActiveBuff());
        STAR_BARRIER_BUFF = BuffRegistry.registerBuff("starbarrier", new StarBarrierBuff());
        STABBY_BUSH_FRENZY_BUFF = BuffRegistry.registerBuff("stabbybushfrenzy", new StabbyBushFrenzyBuff());
        BASHY_BUSH_FRENZY_BUFF = BuffRegistry.registerBuff("bashybushfrenzy", new BashyBushFrenzyBuff());
        BANNER_OF_WAR_MOB = BuffRegistry.registerBuff("bannerofwarmob", new BannerOfWarMobBuff());
        ARCANIC_HOOD_ACTIVE = BuffRegistry.registerBuff("arcanichoodactive", new ArcanicHoodActiveBuff());
        OVERCHARGED_MANA = BuffRegistry.registerBuff("overchargedmana", new OverchargedManaBuff());
        QUICKSAND_STACKS = BuffRegistry.registerBuff("quicksandstacks", new QuicksandStacksBuff());
        LIFE_ESSENCE = BuffRegistry.registerBuff("lifeessence", new LifeEssenceStacksBuff());
        SAPPHIRE_GLYPH = BuffRegistry.registerBuff("sapphireglyph", new SapphireGlyphBuff());
        AMETHYST_GLYPH = BuffRegistry.registerBuff("amethystglyph", new AmethystGlyphBuff());
        RUBY_GLYPH = BuffRegistry.registerBuff("rubyglyph", new RubyGlyphBuff());
        EMERALD_GLYPH = BuffRegistry.registerBuff("emeraldglyph", new EmeraldGlyphBuff());
        TOPAZ_GLYPH = BuffRegistry.registerBuff("topazglyph", new TopazGlyphBuff());
        QUADRUPLE_CHASE_RANGE = BuffRegistry.registerBuff("quadruplechaserange", new QuadrupleChaseRangeBuff());
        SUMMONED_WILL_O_WISP = BuffRegistry.registerBuff("summonedwillothewisp", new CantCancelSummonedCountBuff());
        BARK_SKIN = BuffRegistry.registerBuff("barkskin", new BarkskinBuff());
        AGED_CHAMPION_PROWESS = BuffRegistry.registerBuff("agedchampionprowess", new AgedChampionProwessBuff());
        BULLSEYE = BuffRegistry.registerBuff("bullseye", new BullseyeBuff());
        SUMMONERS_BESTIARY = BuffRegistry.registerBuff("summonersbestiary", new SummonersBestiaryBuff());
        GUARDIAN_BRACELET = BuffRegistry.registerBuff("guardianbracelet", new GuardianBraceletBuff());
        BARKBLADE_ENHANCED = BuffRegistry.registerBuff("barkbladeenhanced", new BarkBladeEnhancedBuff());
        PARRY_BUCKLER_PARRIED = BuffRegistry.registerBuff("parrybucklerparried", new ParryBucklerParriedBuff());
        SOULSTORM_SOULS = BuffRegistry.registerBuff("soulstormsouls", new SoulstormSoulStacksBuff());
        BOUNCE_GLYPH = BuffRegistry.registerBuff("bounceglyph", new BounceGlyphBuff());
        REVERSE_DAMAGE_GLYPH = BuffRegistry.registerBuff("reversedamageglyph", new ReverseDamageGlyphBuff());
        DEMONIC_RAGE = BuffRegistry.registerBuff("demonicrage", new DemonicRageActiveBuff());
        SOULSEED_CONSECUTIVE = BuffRegistry.registerBuff("soulseedconsecutive", new SoulseedConsecutiveExplosionsBuff());
        PERFECT_STORM = BuffRegistry.registerBuff("perfectstorm", new PerfectStormBuff());
        SOLDIER_FRENZY = BuffRegistry.registerBuff("soldierfrenzy", new SoldierFrenzyBuff());
        SUMMONED_GHOSTLYBOW = BuffRegistry.registerBuff("summonedghostlybow", new CantCancelSummonedCountBuff());
        SUMMONED_LOCUST = BuffRegistry.registerBuff("summonedlocust", new CantCancelSummonedCountBuff());
        PHARAOH_MANA_SPENT = BuffRegistry.registerBuff("pharaohmanaspent", new PharaohManaSpentBuff());
        CRYO_IMMUNTY = BuffRegistry.registerBuff("cryoimmunity", new CryoImmunityBuff());
        INCURSION_EMPOWERMENT_CRIT_CHANCE = BuffRegistry.registerBuff("incursionempowermentcritchance", new IncursionEmpowermentCritChanceBuff());
        INCURSION_EMPOWERMENT_ATTACK_SPEED = BuffRegistry.registerBuff("incursionempowermentattackspeed", new IncursionEmpowermentAttackSpeedBuff());
        INCURSION_EMPOWERMENT_REGEN = BuffRegistry.registerBuff("incursionempowermentregen", new IncursionEmpowermentRegenBuff());
        ASCENDED_DASH = BuffRegistry.registerBuff("ascendeddash", new AscendedDashBuff());
        SPAWN_INVINCIBILITY = BuffRegistry.registerBuff("spawninvincibility", new SpawnInvincibilityBuff());
    }

    @Override
    protected void onRegister(BuffRegistryElement<?> object, int id, String stringID, boolean isReplace) {
        if (object.buff instanceof SetBonusBuff) {
            ++totalSetBonuses;
        }
    }

    @Override
    protected void onRegistryClose() {
        instance.streamElements().map(e -> e.buff).forEach(Buff::updateLocalDisplayName);
        for (BuffRegistryElement element : this.getElements()) {
            ((Buff)element.buff).onBuffRegistryClosed();
        }
    }

    public static <T extends Buff> T registerBuff(String stringID, T buff) {
        if (LoadedMod.isRunningModClientSide()) {
            throw new IllegalStateException("Client/server only mods cannot register buffs");
        }
        return BuffRegistry.instance.registerObj((String)stringID, new BuffRegistryElement<T>(buff)).buff;
    }

    public static List<Buff> getBuffs() {
        return instance.streamElements().map(e -> e.buff).collect(Collectors.toList());
    }

    public static Buff getBuff(int id) {
        return ((BuffRegistryElement)BuffRegistry.instance.getElement((int)id)).buff;
    }

    public static Buff getBuff(String stringID) {
        BuffRegistryElement element = (BuffRegistryElement)instance.getElement(stringID);
        return element == null ? null : (Buff)element.buff;
    }

    public static int getBuffID(String stringID) {
        return instance.getElementID(stringID);
    }

    public static int getBuffIDRaw(String stringID) throws NoSuchElementException {
        return instance.getElementIDRaw(stringID);
    }

    public static String getBuffStringID(int id) {
        return instance.getElementStringID(id);
    }

    public static int getTotalSetBonuses() {
        return totalSetBonuses;
    }

    static {
        instance = new BuffRegistry();
        totalSetBonuses = 0;
    }

    public static class Potions {
        public static Buff STINKFLASK;
    }

    public static class Debuffs {
        public static Buff HEALTH_POT_FATIGUE;
        public static Buff MANA_POT_FATIGUE;
        public static Buff MANA_EXHAUSTION;
        public static Buff ON_FIRE;
        public static Buff ABLAZE;
        public static Buff POLYMORPH;
        public static Buff BROKEN_ARMOR;
        public static Buff TELEPORT_SICKNESS;
        public static Buff LIFELINE_COOLDOWN;
        public static Buff QUARTZ_SET_COOLDOWN;
        public static Buff GUNSLINGER_SET_COOLDOWN;
        public static Buff VOID_SET_COOLDOWN;
        public static Buff DASH_COOLDOWN;
        public static Buff SPIDER_WEB_SLOW;
        public static Buff WEB_POTION_SLOW;
        public static Buff SPIDER_VENOM;
        public static Buff NECROTIC_POISON;
        public static Buff NECROTIC_SLOW;
        public static Buff IVY_POISON;
        public static Buff WIDOW_POISON;
        public static Buff CHILLED;
        public static Buff FREEZING;
        public static Buff FROSTBURN;
        public static Buff FROSTSLOW;
        public static Buff HAUNTED;
        public static Buff EMERALD_POISON;
        public static Buff RUNIC_HAT_COOLDOWN;
        public static Buff GUARDIAN_SHELL_COOLDOWN;
        public static Buff ANCESTOR_SET_COOLDOWN;
        public static Buff ANCIENT_FOSSIL_SET_COOLDOWN;
        public static Buff SLIME_SET_COOLDOWN;
        public static Buff NECROTIC_SOUL_SKULL_COOLDOWN;
        public static Buff NIGHTSTEEL_SET_COOLDOWN;
        public static Buff SPIDERITE_SET_COOLDOWN;
        public static Buff SAPPHIRE_SET_COOLDOWN;
        public static Buff SPIDER_CHARM_POISON;
        public static Buff SLIME_POISON;
        public static Buff SAND_KNIFE_WOUND_BUFF;
        public static Buff CRYSTALLIZE_BUFF;
        public static Buff BLOOD_GRIMOIRE_MARKED_DEBUFF;
        public static Buff SLIME_GREATBOW_SLOW_TARGET_DEBUFF;
        public static Buff BLOOD_GRIMOIRE_COOLDOWN;
        public static Buff THE_CRIMSON_SKY_COOLDOWN;
        public static Buff RAVENBEAK_SPEAR_COOLDOWN;
        public static Buff CRUSHING_DARKNESS;
        public static Buff SNOW_COVERED_DEBUFF;
        public static Buff SNOW_COVERED_SLOW_DEBUFF;
        public static Buff FLOUR_COVERED_SLOW_DEBUFF;
        public static Buff NECROBOW_ROOT_DEBUFF;
        public static Buff KATANA_DASH_COOLDOWN;
        public static Buff RUNEBOUND_SCEPTER_COOLDOWN;
        public static Buff CAPTORS_SHORTBOW_COOLDOWN;
        public static Buff NETTED_DEBUFF;
        public static Buff DRYAD_HAUNTED;
        public static Buff DRYAD_POSSESSED;
        public static Buff SPIRIT_HAUNTED;
        public static Buff SPIRIT_POSSESSED;
        public static Buff STUNNED_DAMAGE_TAKEN_INCREASED;
        public static Buff SPIRIT_CORRUPTED;
        public static Buff DEMONIC_SET_COOLDOWN;
        public static Buff SOULSEED_COOLDOWN;
        public static Buff THIEF_THROW_COOLDOWN;
        public static Buff THIEF_STEAL_COOLDOWN;
        public static Buff PERFECT_STORM_ABILITY_COOLDOWN;
        public static Buff PERFECT_STORM_ONHIT_COOLDOWN;
        public static Buff CRYOWITCH_COOLDOWN;
        public static Buff CRYOWITCH_COOLDOWN_ONHIT;
        public static Buff ASCENDED_DARKNESS;
        public static Buff GENERIC_ONFIRE;
        public static Buff GENERIC_ICE_SLOW;
        public static Buff GENERIC_POISON;
        public static Buff GENERIC_DAMAGE_DEBUFF;
        public static Buff GENERIC_WEAKNESS;
        public static Buff GENERIC_ATTACKSPEED_SLOW;
        public static Buff POLYMORPH_CHICKEN;
        public static Buff POLYMORPH_FROG;
        public static Buff POLYMORPH_SQUIRREL;
        public static Buff POLYMORPH_DUCK;
        public static Buff POLYMORPH_RABBIT;
        public static Buff POLYMORPH_TURTLE;
        public static Buff POLYMORPH_ROOSTER;
        public static Buff SECOND_BOSS_WATCHING;
    }

    public static class SetBonuses {
        public static SetBonusBuff LEATHER;
        public static SetBonusBuff CLOTH_ROBE;
        public static SetBonusBuff COPPER;
        public static SetBonusBuff IRON;
        public static SetBonusBuff GOLD_CROWN;
        public static SetBonusBuff GOLD;
        public static SetBonusBuff SPIDER;
        public static SetBonusBuff FROST_HELMET;
        public static SetBonusBuff FROST_HOOD;
        public static SetBonusBuff FROST_HAT;
        public static SetBonusBuff DEMONIC;
        public static SetBonusBuff VOIDHAT;
        public static SetBonusBuff VOIDMASK;
        public static SetBonusBuff NINJA;
        public static SetBonusBuff WITCH_ROBES;
        public static SetBonusBuff CRYOWITCH;
        public static SetBonusBuff RUNIC;
        public static SetBonusBuff RUNICHAT;
        public static SetBonusBuff IVYHELMET;
        public static SetBonusBuff IVYHOOD;
        public static SetBonusBuff IVYHAT;
        public static SetBonusBuff IVYCIRCLET;
        public static SetBonusBuff QUARTZHELMET;
        public static SetBonusBuff QUARTZCROWN;
        public static SetBonusBuff GUNSLINGER;
        public static SetBonusBuff TUNGSTEN;
        public static SetBonusBuff SHADOWHOOD;
        public static SetBonusBuff SHADOWHAT;
        public static SetBonusBuff GLACIALHELMET;
        public static SetBonusBuff GLACIALCIRCLET;
        public static SetBonusBuff DRYAD_HELMET;
        public static SetBonusBuff DRYAD_SCARF;
        public static SetBonusBuff DRYAD_HAT;
        public static SetBonusBuff DRYAD_CROWN;
        public static SetBonusBuff MYCELIUMHOOD;
        public static SetBonusBuff MYCELIUMSCARF;
        public static SetBonusBuff AGED_CHAMPION;
        public static SetBonusBuff WIDOW;
        public static SetBonusBuff ANCESTOR;
        public static SetBonusBuff ANCIENT_FOSSIL_HELMET;
        public static SetBonusBuff ANCIENT_FOSSIL_MASK;
        public static SetBonusBuff SHARPSHOOTER;
        public static SetBonusBuff SLIMEHELMET;
        public static SetBonusBuff SLIMEHAT;
        public static SetBonusBuff NIGHTSTEEL;
        public static SetBonusBuff NIGHTSTEEL_HELMET;
        public static SetBonusBuff NIGHTSTEEL_VEIL;
        public static SetBonusBuff NIGHTSTEEL_CIRCLET;
        public static SetBonusBuff BLOODPLATE_COWL;
        public static SetBonusBuff SPIDERITE;
        public static SetBonusBuff BATTLE_CHEF;
        public static SetBonusBuff SPIDERITE_HELMET;
        public static SetBonusBuff SPIDERITE_HAT;
        public static SetBonusBuff SPIDERITE_CROWN;
        public static SetBonusBuff RAVENLORDS_HEADDRESS;
        public static SetBonusBuff DAWN;
        public static SetBonusBuff DUSK;
        public static SetBonusBuff AMETHYST;
        public static SetBonusBuff SAPPHIRE;
        public static SetBonusBuff EMERALD;
        public static SetBonusBuff RUBY;
        public static SetBonusBuff ARCANIC_HOOD;
        public static SetBonusBuff ARACHNID;
        public static SetBonusBuff GHOSTLY_ARCHER;
        public static SetBonusBuff SOULSEED;
        public static SetBonusBuff SOLDIERHELMET;
        public static SetBonusBuff SOLDIERCAP;
        public static SetBonusBuff THIEF;
        public static SetBonusBuff PHARAOH;
        public static SetBonusBuff SUPPORTER;
    }

    public static class Banners {
        public static Buff SPEED;
        public static Buff DAMAGE;
        public static Buff SUMMON_SPEED;
        public static Buff DEFENSE;
        public static Buff PEACE;
    }

    protected static class BuffRegistryElement<T extends Buff>
    implements IDDataContainer {
        public final T buff;

        public BuffRegistryElement(T buff) {
            this.buff = buff;
        }

        @Override
        public IDData getIDData() {
            return ((Buff)this.buff).idData;
        }
    }
}

