/*
 * Decompiled with CFR 0.152.
 */
package necesse.gfx.credits;

import java.util.ArrayList;
import java.util.Arrays;
import java.util.HashSet;
import java.util.Iterator;
import necesse.engine.Settings;
import necesse.engine.localization.Language;
import necesse.engine.localization.Localization;
import necesse.engine.localization.message.GameMessage;
import necesse.engine.localization.message.GameMessageBuilder;
import necesse.engine.localization.message.LocalMessage;
import necesse.engine.localization.message.StaticMessage;
import necesse.gfx.GameResources;
import necesse.gfx.credits.FadeWrapperCreditsDisplay;
import necesse.gfx.credits.GameCreditsDisplay;
import necesse.gfx.credits.GameCreditsHorizontalList;
import necesse.gfx.credits.GameCreditsSinglesList;
import necesse.gfx.credits.GameCreditsTopToBotList;
import necesse.gfx.credits.GameSpriteCreditsDisplay;
import necesse.gfx.credits.TextFadeCreditsDisplay;
import necesse.gfx.credits.WaitCreditsDisplay;
import necesse.gfx.fairType.FairGameSpriteGlyph;
import necesse.gfx.fairType.FairSpacerGlyph;

public class FinalGamesCredits
extends GameCreditsSinglesList {
    public HashSet<String> presetSubmitters = new HashSet();
    public ArrayList<GameMessage> specialThanks;

    public FinalGamesCredits(boolean centerText) {
        super(centerText, centerText);
        Language[] languages;
        this.presetSubmitters.addAll(Arrays.asList("Kromarth", "herbin45", "Regalia776", "Balinha Azeda", "Molivious", "Dafri", "Vireyar", "Gizola", "Cipher Stormwolf", "The Acorn Aristocrat", "Speedyblabla", "Mesuen Cer\u00f3n", "Boomer boy", "Fukusa", "Familia Kindreds YT", "Jamster", "mx_lenore", "Misha279Ua", "Haydex Gaming", "RavenMightDie", "FrogJelly", "Jakapoa", "PrettyPinkPonyPrince", "kolakutusu", "b1rbert", "Jillardo"));
        this.specialThanks = new ArrayList<StaticMessage>(Arrays.asList(new StaticMessage("Filmbyen IdeasLab"), new StaticMessage("Kasper & Rasmus Skovgaard"), new StaticMessage("paulsoaresjr"), new StaticMessage("Rasmus Egerod Leth"), new StaticMessage("Future Friends"), new StaticMessage("Valve & Steam"), new StaticMessage("Chop Chop Games"), new StaticMessage("Hooded Horse"), new StaticMessage("Games Denmark"), new StaticMessage("Thea the Bear"), new StaticMessage("Elton Juul"), new StaticMessage("Emil Hansen")));
        int fadeInTime = 1000;
        int fadeOutTime = 1000;
        int nameTime = 1000;
        int nameTitleTime = 0;
        int nameTitleFadeInTime = 500;
        int namesWaitBaseTime = 5000;
        int namesWaitAdditionalTimePerName = 2000;
        int waitBetweenSectionsTime = 2000;
        int titleTextTime = 4000;
        GameCreditsHorizontalList title = new GameCreditsHorizontalList(centerText);
        GameCreditsTopToBotList subtitles = new GameCreditsTopToBotList(centerText, true);
        TextFadeCreditsDisplay thanksForPlaying = new TextFadeCreditsDisplay(fadeInTime, 2000, 0, new LocalMessage("credits", "thankyou"), 32, centerText);
        thanksForPlaying.endGlyphs.add(new FairSpacerGlyph(10.0f, 5.0f));
        thanksForPlaying.endGlyphs.add(new FairGameSpriteGlyph(Settings.UI.heart_fill, 0, -3));
        subtitles.add(thanksForPlaying);
        subtitles.add(new WaitCreditsDisplay(1, 0, 50));
        GameCreditsHorizontalList titleTeam = new GameCreditsHorizontalList(centerText);
        titleTeam.add(new TextFadeCreditsDisplay(fadeInTime, 5000, 0, new LocalMessage("credits", "createdby"), 32, 450, centerText));
        titleTeam.add(new WaitCreditsDisplay(5000));
        subtitles.add(titleTeam);
        title.add(new FadeWrapperCreditsDisplay(subtitles, 0, fadeOutTime));
        this.add(title);
        LocalMessage designer = new LocalMessage("credits", "gamedesigner");
        LocalMessage gameplayProgrammer = new LocalMessage("credits", "gameplayprogrammer");
        LocalMessage pixelArtist = new LocalMessage("credits", "pixelartist");
        LocalMessage artist2D = new LocalMessage("credits", "2dartist");
        LocalMessage technicalProgrammer = new LocalMessage("credits", "technicalprogrammer");
        LocalMessage systemsToolsPorting = new LocalMessage("credits", "systemstools");
        LocalMessage musicComposer = new LocalMessage("credits", "musiccomposer");
        LocalMessage soundDesigner = new LocalMessage("credits", "sounddesigner");
        LocalMessage studioOperations = new LocalMessage("credits", "studiooperations");
        LocalMessage businessDevelopment = new LocalMessage("credits", "businessdevelopment");
        LocalMessage publishingManagement = new LocalMessage("credits", "publishingmanagement");
        LocalMessage communityManagement = new LocalMessage("credits", "communitymanagement");
        LocalMessage contentCreation = new LocalMessage("credits", "contentcreation");
        LocalMessage publishingMarketing = new LocalMessage("credits", "publishingmarketing");
        LocalMessage videoEditor = new LocalMessage("credits", "videoeditor");
        LocalMessage humanResources = new LocalMessage("credits", "humanresources");
        GameCreditsHorizontalList names = new GameCreditsHorizontalList(centerText);
        GameCreditsTopToBotList mads = new GameCreditsTopToBotList(centerText, true);
        mads.add(new TextFadeCreditsDisplay(fadeInTime, nameTime, 0, new StaticMessage("Mads Skovgaard"), 32, centerText));
        mads.add(new WaitCreditsDisplay(1, 0, 5));
        mads.add(new TextFadeCreditsDisplay(nameTitleFadeInTime, nameTitleTime * 2, 0, new LocalMessage("credits", "creatorof"), 20, centerText));
        mads.add(new TextFadeCreditsDisplay(nameTitleFadeInTime, nameTitleTime, 0, new LocalMessage("credits", "gamedirector"), 20, centerText));
        mads.add(new TextFadeCreditsDisplay(nameTitleFadeInTime, nameTitleTime, 0, designer, 20, centerText));
        mads.add(new TextFadeCreditsDisplay(nameTitleFadeInTime, nameTitleTime, 0, new LocalMessage("credits", "leadprogrammer"), 20, centerText));
        names.add(mads);
        names.add(new WaitCreditsDisplay(namesWaitBaseTime + namesWaitAdditionalTimePerName));
        this.add(new FadeWrapperCreditsDisplay(names, 0, fadeOutTime));
        this.add(new WaitCreditsDisplay(waitBetweenSectionsTime));
        names = new GameCreditsHorizontalList(centerText);
        GameCreditsTopToBotList jonas = new GameCreditsTopToBotList(centerText, true);
        jonas.add(new TextFadeCreditsDisplay(fadeInTime, nameTime, 0, new StaticMessage("Jonas Maretti Gress"), 32, centerText));
        jonas.add(new WaitCreditsDisplay(1, 0, 5));
        jonas.add(new TextFadeCreditsDisplay(nameTitleFadeInTime, nameTitleTime, 0, new LocalMessage("credits", "gameproducer"), 20, centerText));
        jonas.add(new TextFadeCreditsDisplay(nameTitleFadeInTime, nameTitleTime, 0, designer, 20, centerText));
        jonas.add(new TextFadeCreditsDisplay(nameTitleFadeInTime, nameTitleTime, 0, gameplayProgrammer, 20, centerText));
        names.add(jonas);
        names.add(new WaitCreditsDisplay(1, 0, 50));
        GameCreditsTopToBotList simon = new GameCreditsTopToBotList(centerText, true);
        simon.add(new TextFadeCreditsDisplay(fadeInTime, nameTime, 0, new StaticMessage("Simon Stormes"), 32, centerText));
        simon.add(new WaitCreditsDisplay(1, 0, 5));
        simon.add(new TextFadeCreditsDisplay(nameTitleFadeInTime, nameTitleTime, 0, designer, 20, centerText));
        simon.add(new TextFadeCreditsDisplay(nameTitleFadeInTime, nameTitleTime, 0, gameplayProgrammer, 20, centerText));
        simon.add(new TextFadeCreditsDisplay(nameTitleFadeInTime, nameTitleTime, 0, pixelArtist, 20, centerText));
        names.add(simon);
        names.add(new WaitCreditsDisplay(namesWaitBaseTime + namesWaitAdditionalTimePerName * 2));
        this.add(new FadeWrapperCreditsDisplay(names, 0, fadeOutTime));
        this.add(new WaitCreditsDisplay(waitBetweenSectionsTime));
        names = new GameCreditsHorizontalList(centerText);
        GameCreditsTopToBotList bo = new GameCreditsTopToBotList(centerText, true);
        bo.add(new TextFadeCreditsDisplay(fadeInTime, nameTime, 0, new StaticMessage("Bo Michelsen"), 32, centerText));
        bo.add(new WaitCreditsDisplay(1, 0, 5));
        bo.add(new TextFadeCreditsDisplay(nameTitleFadeInTime, nameTitleTime, 0, artist2D, 20, centerText));
        bo.add(new TextFadeCreditsDisplay(nameTitleFadeInTime, nameTitleTime, 0, pixelArtist, 20, centerText));
        names.add(bo);
        names.add(new WaitCreditsDisplay(1, 0, 50));
        GameCreditsTopToBotList oliver = new GameCreditsTopToBotList(centerText, true);
        oliver.add(new TextFadeCreditsDisplay(fadeInTime, nameTime, 0, new StaticMessage("Oliver D. J. Christensen"), 32, centerText));
        oliver.add(new WaitCreditsDisplay(1, 0, 5));
        oliver.add(new TextFadeCreditsDisplay(nameTitleFadeInTime, nameTitleTime, 0, pixelArtist, 20, centerText));
        names.add(oliver);
        names.add(new WaitCreditsDisplay(namesWaitBaseTime + namesWaitAdditionalTimePerName * 2));
        this.add(new FadeWrapperCreditsDisplay(names, 0, fadeOutTime));
        this.add(new WaitCreditsDisplay(waitBetweenSectionsTime));
        names = new GameCreditsHorizontalList(centerText);
        GameCreditsTopToBotList jonathan = new GameCreditsTopToBotList(centerText, true);
        jonathan.add(new TextFadeCreditsDisplay(fadeInTime, nameTime, 0, new StaticMessage("Jonathan Buurgaard J\u00f8rgensen"), 32, centerText));
        jonathan.add(new WaitCreditsDisplay(1, 0, 5));
        jonathan.add(new TextFadeCreditsDisplay(nameTitleFadeInTime, nameTitleTime, 0, technicalProgrammer, 20, centerText));
        jonathan.add(new TextFadeCreditsDisplay(nameTitleFadeInTime, nameTitleTime, 0, systemsToolsPorting, 20, centerText));
        names.add(jonathan);
        names.add(new WaitCreditsDisplay(1, 0, 50));
        GameCreditsTopToBotList asbjorn = new GameCreditsTopToBotList(centerText, true);
        asbjorn.add(new TextFadeCreditsDisplay(fadeInTime, nameTime, 0, new StaticMessage("Asbj\u00f8rn \u00d8rts Johnsen"), 32, centerText));
        asbjorn.add(new WaitCreditsDisplay(1, 0, 5));
        asbjorn.add(new TextFadeCreditsDisplay(nameTitleFadeInTime, nameTitleTime, 0, gameplayProgrammer, 20, centerText));
        names.add(asbjorn);
        names.add(new WaitCreditsDisplay(namesWaitBaseTime + namesWaitAdditionalTimePerName * 2));
        this.add(new FadeWrapperCreditsDisplay(names, 0, fadeOutTime));
        this.add(new WaitCreditsDisplay(waitBetweenSectionsTime));
        names = new GameCreditsHorizontalList(centerText);
        GameCreditsTopToBotList rune = new GameCreditsTopToBotList(centerText, true);
        rune.add(new TextFadeCreditsDisplay(fadeInTime, nameTime, 0, new StaticMessage("Rune R. B. Eskildsen"), 32, centerText));
        rune.add(new WaitCreditsDisplay(1, 0, 5));
        rune.add(new TextFadeCreditsDisplay(nameTitleFadeInTime, nameTitleTime, 0, musicComposer, 20, centerText));
        rune.add(new TextFadeCreditsDisplay(nameTitleFadeInTime, nameTitleTime, 0, soundDesigner, 20, centerText));
        names.add(rune);
        names.add(new WaitCreditsDisplay(namesWaitBaseTime + namesWaitAdditionalTimePerName));
        this.add(new FadeWrapperCreditsDisplay(names, 0, fadeOutTime));
        this.add(new WaitCreditsDisplay(waitBetweenSectionsTime));
        GameCreditsHorizontalList publishingTitle = new GameCreditsHorizontalList(centerText);
        publishingTitle.add(new TextFadeCreditsDisplay(fadeInTime, titleTextTime, fadeOutTime, new LocalMessage("credits", "selfpublishing"), 32, 500, centerText));
        this.add(publishingTitle);
        GameCreditsHorizontalList names2 = new GameCreditsHorizontalList(centerText);
        GameCreditsTopToBotList christian = new GameCreditsTopToBotList(centerText, true);
        christian.add(new TextFadeCreditsDisplay(fadeInTime, nameTime, 0, new StaticMessage("Christian Nyhus"), 32, centerText));
        christian.add(new WaitCreditsDisplay(1, 0, 5));
        christian.add(new TextFadeCreditsDisplay(nameTitleFadeInTime, nameTitleTime, 0, studioOperations, 20, centerText));
        christian.add(new TextFadeCreditsDisplay(nameTitleFadeInTime, nameTitleTime, 0, businessDevelopment, 20, centerText));
        christian.add(new TextFadeCreditsDisplay(nameTitleFadeInTime, nameTitleTime, 0, publishingManagement, 20, centerText));
        names2.add(christian);
        names2.add(new WaitCreditsDisplay(1, 0, 30));
        GameCreditsTopToBotList jonas2 = new GameCreditsTopToBotList(centerText, true);
        jonas2.add(new TextFadeCreditsDisplay(fadeInTime, nameTime, 0, new StaticMessage("Jonas Maretti Gress"), 32, centerText));
        jonas2.add(new WaitCreditsDisplay(1, 0, 5));
        jonas2.add(new TextFadeCreditsDisplay(nameTitleFadeInTime, nameTitleTime, 0, publishingManagement, 20, centerText));
        jonas2.add(new TextFadeCreditsDisplay(nameTitleFadeInTime, nameTitleTime, 0, communityManagement, 20, centerText));
        jonas2.add(new TextFadeCreditsDisplay(nameTitleFadeInTime, nameTitleTime, 0, contentCreation, 20, centerText));
        names2.add(jonas2);
        names2.add(new WaitCreditsDisplay(1, 0, 30));
        GameCreditsTopToBotList rune2 = new GameCreditsTopToBotList(centerText, true);
        rune2.add(new TextFadeCreditsDisplay(fadeInTime, nameTime, 0, new StaticMessage("Rune R. B. Eskildsen"), 32, centerText));
        rune2.add(new WaitCreditsDisplay(1, 0, 5));
        rune2.add(new TextFadeCreditsDisplay(nameTitleFadeInTime, nameTitleTime, 0, publishingMarketing, 20, centerText));
        rune2.add(new TextFadeCreditsDisplay(nameTitleFadeInTime, nameTitleTime, 0, videoEditor, 20, centerText));
        names2.add(rune2);
        names2.add(new WaitCreditsDisplay(namesWaitBaseTime + namesWaitAdditionalTimePerName * 3));
        this.add(new FadeWrapperCreditsDisplay(names2, 0, fadeOutTime));
        this.add(new WaitCreditsDisplay(waitBetweenSectionsTime));
        names2 = new GameCreditsHorizontalList(centerText);
        GameCreditsTopToBotList zach = new GameCreditsTopToBotList(centerText, true);
        zach.add(new TextFadeCreditsDisplay(fadeInTime, nameTime, 0, new StaticMessage("Zachery Oss"), 32, centerText));
        zach.add(new WaitCreditsDisplay(1, 0, 5));
        zach.add(new TextFadeCreditsDisplay(nameTitleFadeInTime, nameTitleTime, 0, publishingMarketing, 20, centerText));
        zach.add(new TextFadeCreditsDisplay(nameTitleFadeInTime, nameTitleTime, 0, communityManagement, 20, centerText));
        zach.add(new TextFadeCreditsDisplay(nameTitleFadeInTime, nameTitleTime, 0, contentCreation, 20, centerText));
        names2.add(zach);
        names2.add(new WaitCreditsDisplay(1, 0, 30));
        GameCreditsTopToBotList marco = new GameCreditsTopToBotList(centerText, true);
        marco.add(new TextFadeCreditsDisplay(fadeInTime, nameTime, 0, new StaticMessage("Marco Pulido"), 32, centerText));
        marco.add(new WaitCreditsDisplay(1, 0, 5));
        marco.add(new TextFadeCreditsDisplay(nameTitleFadeInTime, nameTitleTime, 0, publishingMarketing, 20, centerText));
        marco.add(new TextFadeCreditsDisplay(nameTitleFadeInTime, nameTitleTime, 0, communityManagement, 20, centerText));
        marco.add(new TextFadeCreditsDisplay(nameTitleFadeInTime, nameTitleTime, 0, contentCreation, 20, centerText));
        names2.add(marco);
        names2.add(new WaitCreditsDisplay(1, 0, 30));
        GameCreditsTopToBotList mads2 = new GameCreditsTopToBotList(centerText, true);
        mads2.add(new TextFadeCreditsDisplay(fadeInTime, nameTime, 0, new StaticMessage("Mads Skovgaard"), 32, centerText));
        mads2.add(new WaitCreditsDisplay(1, 0, 5));
        mads2.add(new TextFadeCreditsDisplay(nameTitleFadeInTime, nameTitleTime, 0, publishingMarketing, 20, centerText));
        mads2.add(new TextFadeCreditsDisplay(nameTitleFadeInTime, nameTitleTime, 0, communityManagement, 20, centerText));
        names2.add(mads2);
        names2.add(new WaitCreditsDisplay(namesWaitBaseTime + namesWaitAdditionalTimePerName * 3));
        this.add(new FadeWrapperCreditsDisplay(names2, 0, fadeOutTime));
        this.add(new WaitCreditsDisplay(waitBetweenSectionsTime));
        names2 = new GameCreditsHorizontalList(centerText);
        GameCreditsTopToBotList neonNoroshi = new GameCreditsTopToBotList(centerText, true);
        neonNoroshi.add(new TextFadeCreditsDisplay(fadeInTime, nameTime, 0, new LocalMessage("credits", "andwithpartners"), 32, 500, centerText));
        neonNoroshi.add(new WaitCreditsDisplay(1, 0, 30));
        neonNoroshi.add(new TextFadeCreditsDisplay(fadeInTime, nameTime, 0, new StaticMessage("Neon Noroshi"), 32, centerText));
        neonNoroshi.add(new WaitCreditsDisplay(1, 0, 5));
        neonNoroshi.add(new TextFadeCreditsDisplay(nameTitleFadeInTime, nameTitleTime, 0, new GameMessageBuilder().append("Tang Zitong - ").append("credits", "chinesemarket"), 20, centerText));
        neonNoroshi.add(new TextFadeCreditsDisplay(nameTitleFadeInTime, nameTitleTime, 0, new GameMessageBuilder().append("Mainaru - ").append("credits", "japanesemarket"), 20, centerText));
        neonNoroshi.add(new TextFadeCreditsDisplay(nameTitleFadeInTime, nameTitleTime, 0, new GameMessageBuilder().append("Lee Young Chul - ").append("credits", "koreanmarket"), 20, centerText));
        neonNoroshi.add(new TextFadeCreditsDisplay(nameTitleFadeInTime, nameTitleTime, 0, new GameMessageBuilder().append("Tomoko Miya - ").append("credits", "projectmanager"), 20, centerText));
        names2.add(neonNoroshi);
        names2.add(new WaitCreditsDisplay(namesWaitBaseTime + nameTime * 2 + namesWaitAdditionalTimePerName));
        this.add(new FadeWrapperCreditsDisplay(names2, 0, fadeOutTime));
        this.add(new WaitCreditsDisplay(waitBetweenSectionsTime));
        GameCreditsHorizontalList internsTitle = new GameCreditsHorizontalList(centerText);
        internsTitle.add(new TextFadeCreditsDisplay(fadeInTime, titleTextTime, fadeOutTime, new LocalMessage("credits", "helpfulinterns"), 32, 500, centerText));
        this.add(internsTitle);
        GameCreditsTopToBotList names3 = new GameCreditsTopToBotList(centerText, true);
        GameCreditsHorizontalList jeanette = new GameCreditsHorizontalList(centerText);
        jeanette.add(new TextFadeCreditsDisplay(fadeInTime, 0, 0, new StaticMessage("Jeanette M. Vittrup"), 32, centerText));
        jeanette.add(new WaitCreditsDisplay(1, 0, 5));
        jeanette.add(new TextFadeCreditsDisplay(fadeInTime, 0, 0, humanResources, 20, centerText));
        names3.add(jeanette);
        names3.add(new WaitCreditsDisplay(1, 0, 25));
        GameCreditsHorizontalList peter = new GameCreditsHorizontalList(centerText);
        peter.add(new TextFadeCreditsDisplay(fadeInTime, 0, 0, new StaticMessage("Peter Toft Knudsen"), 32, centerText));
        peter.add(new WaitCreditsDisplay(1, 0, 5));
        peter.add(new TextFadeCreditsDisplay(fadeInTime, 0, 0, pixelArtist, 20, centerText));
        names3.add(peter);
        names3.add(new WaitCreditsDisplay(1, 0, 25));
        GameCreditsHorizontalList sebastian = new GameCreditsHorizontalList(centerText);
        sebastian.add(new TextFadeCreditsDisplay(fadeInTime, 0, 0, new StaticMessage("Sebastian Hilmer"), 32, centerText));
        sebastian.add(new WaitCreditsDisplay(1, 0, 5));
        sebastian.add(new TextFadeCreditsDisplay(fadeInTime, 0, 0, gameplayProgrammer, 20, centerText));
        names3.add(sebastian);
        names3.add(new WaitCreditsDisplay(1, 0, 25));
        GameCreditsHorizontalList fabian = new GameCreditsHorizontalList(centerText);
        fabian.add(new TextFadeCreditsDisplay(fadeInTime, 0, 0, new StaticMessage("Fabian Saxo"), 32, centerText));
        fabian.add(new WaitCreditsDisplay(1, 0, 5));
        fabian.add(new TextFadeCreditsDisplay(fadeInTime, 0, 0, soundDesigner, 20, centerText));
        names3.add(fabian);
        names3.add(new WaitCreditsDisplay(1, 0, 25));
        GameCreditsHorizontalList maria = new GameCreditsHorizontalList(centerText);
        maria.add(new TextFadeCreditsDisplay(fadeInTime, 0, 0, new StaticMessage("Maria O. Christensen"), 32, centerText));
        maria.add(new WaitCreditsDisplay(1, 0, 5));
        maria.add(new TextFadeCreditsDisplay(fadeInTime, 0, 0, artist2D, 20, centerText));
        names3.add(maria);
        names3.add(new WaitCreditsDisplay(namesWaitBaseTime));
        this.add(new FadeWrapperCreditsDisplay(names3, 0, fadeOutTime));
        this.add(new WaitCreditsDisplay(waitBetweenSectionsTime));
        GameCreditsTopToBotList officeDogs = new GameCreditsTopToBotList(centerText, true);
        officeDogs.add(new TextFadeCreditsDisplay(nameTitleFadeInTime, nameTitleFadeInTime, 0, new LocalMessage("credits", "playfuldogs"), 20, 300, centerText));
        officeDogs.add(new WaitCreditsDisplay(1, 0, 10));
        officeDogs.add(new TextFadeCreditsDisplay(nameTitleFadeInTime, nameTitleFadeInTime, 0, new StaticMessage("Freya"), 20, centerText));
        officeDogs.add(new TextFadeCreditsDisplay(nameTitleFadeInTime, nameTitleFadeInTime, 0, new StaticMessage("Zitha"), 20, centerText));
        officeDogs.add(new WaitCreditsDisplay(namesWaitBaseTime / 2));
        this.add(new FadeWrapperCreditsDisplay(officeDogs, 0, fadeOutTime));
        GameCreditsHorizontalList communityTitle = new GameCreditsHorizontalList(centerText);
        communityTitle.add(new TextFadeCreditsDisplay(fadeInTime, titleTextTime, fadeOutTime, new LocalMessage("credits", "amazingcommunity"), 32, 500, centerText));
        this.add(communityTitle);
        GameCreditsTopToBotList elders = new GameCreditsTopToBotList(centerText, true);
        elders.add(new TextFadeCreditsDisplay(nameTitleFadeInTime, 0, 0, new LocalMessage("credits", "moderatorselders"), 32, centerText));
        elders.add(new WaitCreditsDisplay(1, 0, 10));
        elders.add(new TextFadeCreditsDisplay(nameTitleFadeInTime, 0, 0, new StaticMessage("Kamikaze"), 20, centerText));
        elders.add(new TextFadeCreditsDisplay(nameTitleFadeInTime, 0, 0, new StaticMessage("Subject"), 20, centerText));
        elders.add(new TextFadeCreditsDisplay(nameTitleFadeInTime, 0, 0, new StaticMessage("Vireyar"), 20, centerText));
        elders.add(new TextFadeCreditsDisplay(nameTitleFadeInTime, 0, 0, new StaticMessage("Haydex_Gaming"), 20, centerText));
        elders.add(new TextFadeCreditsDisplay(nameTitleFadeInTime, 0, 0, new StaticMessage("Rainfury"), 20, centerText));
        elders.add(new TextFadeCreditsDisplay(nameTitleFadeInTime, 0, 0, new StaticMessage("Albcatmastercat"), 20, centerText));
        elders.add(new TextFadeCreditsDisplay(nameTitleFadeInTime, 0, 0, new StaticMessage("TsuKuSs"), 20, centerText));
        elders.add(new TextFadeCreditsDisplay(nameTitleFadeInTime, 0, 0, new StaticMessage("Diligo"), 20, centerText));
        elders.add(new TextFadeCreditsDisplay(nameTitleFadeInTime, 0, 0, new StaticMessage("Jakapoa"), 20, centerText));
        elders.add(new WaitCreditsDisplay(namesWaitBaseTime));
        this.add(new FadeWrapperCreditsDisplay(elders, 0, fadeOutTime));
        this.add(new WaitCreditsDisplay(waitBetweenSectionsTime / 2));
        GameCreditsTopToBotList wikiContributors = new GameCreditsTopToBotList(centerText, true);
        wikiContributors.add(new TextFadeCreditsDisplay(nameTitleFadeInTime, 0, 0, new LocalMessage("credits", "wikicontributors"), 32, centerText));
        wikiContributors.add(new WaitCreditsDisplay(1, 0, 10));
        wikiContributors.add(new TextFadeCreditsDisplay(nameTitleFadeInTime, 0, 0, new StaticMessage("Spiff"), 20, centerText));
        wikiContributors.add(new TextFadeCreditsDisplay(nameTitleFadeInTime, 0, 0, new StaticMessage("Rainfury"), 20, centerText));
        wikiContributors.add(new TextFadeCreditsDisplay(nameTitleFadeInTime, 0, 0, new StaticMessage("lachieben19"), 20, centerText));
        wikiContributors.add(new TextFadeCreditsDisplay(nameTitleFadeInTime, 0, 0, new StaticMessage("BaskB"), 20, centerText));
        wikiContributors.add(new TextFadeCreditsDisplay(nameTitleFadeInTime, 0, 0, new StaticMessage("direwolf420"), 20, centerText));
        wikiContributors.add(new TextFadeCreditsDisplay(nameTitleFadeInTime, 0, 0, new StaticMessage("Meefstick"), 20, centerText));
        wikiContributors.add(new WaitCreditsDisplay(500, 0, 10));
        wikiContributors.add(new TextFadeCreditsDisplay(fadeInTime, 0, 0, new LocalMessage("credits", "andmanyother"), 20, centerText));
        wikiContributors.add(new WaitCreditsDisplay(namesWaitBaseTime));
        this.add(new FadeWrapperCreditsDisplay(wikiContributors, 0, fadeOutTime));
        this.add(new WaitCreditsDisplay(waitBetweenSectionsTime / 2));
        GameCreditsTopToBotList modders = new GameCreditsTopToBotList(centerText, true);
        modders.add(new TextFadeCreditsDisplay(nameTitleFadeInTime, 0, 0, new LocalMessage("credits", "amazingmodder"), 32, centerText));
        modders.add(new WaitCreditsDisplay(1, 0, 10));
        modders.add(new TextFadeCreditsDisplay(nameTitleFadeInTime, 0, 0, new StaticMessage("Save"), 20, centerText));
        modders.add(new TextFadeCreditsDisplay(nameTitleFadeInTime, 0, 0, new StaticMessage("Jakapoa"), 20, centerText));
        modders.add(new TextFadeCreditsDisplay(nameTitleFadeInTime, 0, 0, new StaticMessage("Snoobinoob"), 20, centerText));
        modders.add(new TextFadeCreditsDisplay(nameTitleFadeInTime, 0, 0, new StaticMessage("Eryr"), 20, centerText));
        modders.add(new TextFadeCreditsDisplay(nameTitleFadeInTime, 0, 0, new StaticMessage("Pooper McFart"), 20, centerText));
        modders.add(new TextFadeCreditsDisplay(nameTitleFadeInTime, 0, 0, new StaticMessage("Player_GPT"), 20, centerText));
        modders.add(new WaitCreditsDisplay(500, 0, 10));
        modders.add(new TextFadeCreditsDisplay(fadeInTime, 0, 0, new LocalMessage("credits", "andmanyother"), 20, centerText));
        modders.add(new WaitCreditsDisplay(namesWaitBaseTime));
        this.add(new FadeWrapperCreditsDisplay(modders, 0, fadeOutTime));
        this.add(new WaitCreditsDisplay(waitBetweenSectionsTime / 2));
        GameCreditsHorizontalList translatorsTitle = new GameCreditsHorizontalList(centerText);
        translatorsTitle.add(new TextFadeCreditsDisplay(fadeInTime, titleTextTime, fadeOutTime, new LocalMessage("credits", "thoughtfultranslations"), 32, 500, centerText));
        this.add(translatorsTitle);
        GameCreditsHorizontalList languageCredits = new GameCreditsHorizontalList(centerText);
        int currentHeight = 0;
        for (Language language : languages = Localization.getLanguages()) {
            if (language.isDebugOnly() || Localization.isOfficial(language)) continue;
            if (currentHeight >= 400) {
                languageCredits = new GameCreditsHorizontalList(centerText);
                this.add(languageCredits);
                currentHeight = 0;
            }
            GameCreditsHorizontalList currentCredits = new GameCreditsHorizontalList(centerText);
            currentCredits.add(new TextFadeCreditsDisplay(nameTitleFadeInTime, nameTime, 0, new StaticMessage(language.englishDisplayName + " / " + language.localDisplayName), 32, centerText));
            currentCredits.add(new WaitCreditsDisplay(1, 0, 5));
            currentHeight += 37;
            TextFadeCreditsDisplay currentNames = new TextFadeCreditsDisplay(nameTitleFadeInTime, nameTime, 0, new StaticMessage(language.credits), 20, 300, centerText);
            currentCredits.add(currentNames);
            currentNames.initDrawAndGetTotalTimeShown();
            currentHeight += currentNames.getDrawBounds().height;
            currentCredits.add(new WaitCreditsDisplay(namesWaitBaseTime));
            languageCredits.add(new FadeWrapperCreditsDisplay(currentCredits, 0, fadeOutTime));
            languageCredits.add(new WaitCreditsDisplay(1, 0, 30));
            currentHeight += 30;
        }
        this.add(new WaitCreditsDisplay(waitBetweenSectionsTime));
        if (!this.presetSubmitters.isEmpty()) {
            ArrayList<String> presetSubmitters = new ArrayList<String>(this.presetSubmitters);
            presetSubmitters.sort(null);
            GameCreditsTopToBotList presetSubmittersTitle = new GameCreditsTopToBotList(centerText, true);
            presetSubmittersTitle.add(new TextFadeCreditsDisplay(nameTitleFadeInTime, 0, 0, new LocalMessage("credits", "creativepresets"), 32, centerText));
            presetSubmittersTitle.add(new WaitCreditsDisplay(1, 0, 10));
            GameCreditsSinglesList presetSubmittersContent = new GameCreditsSinglesList(centerText, false);
            Object currentPresetSubmittersColumn = null;
            Iterator<String> presetSubmittersIterator = presetSubmitters.iterator();
            while (presetSubmittersIterator.hasNext()) {
                String presetSubmitter = presetSubmittersIterator.next();
                if (currentPresetSubmittersColumn == null) {
                    currentPresetSubmittersColumn = new GameCreditsTopToBotList(centerText, true);
                }
                ((GameCreditsTopToBotList)currentPresetSubmittersColumn).add(new TextFadeCreditsDisplay(nameTitleFadeInTime, 0, 0, new StaticMessage(presetSubmitter), 20, centerText));
                if (((GameCreditsTopToBotList)currentPresetSubmittersColumn).size() < 15) continue;
                ((GameCreditsTopToBotList)currentPresetSubmittersColumn).add(new WaitCreditsDisplay(waitBetweenSectionsTime));
                if (presetSubmittersIterator.hasNext()) {
                    presetSubmittersContent.add(new FadeWrapperCreditsDisplay((GameCreditsDisplay)currentPresetSubmittersColumn, 0, fadeOutTime));
                } else {
                    presetSubmittersContent.add((GameCreditsDisplay)currentPresetSubmittersColumn);
                }
                currentPresetSubmittersColumn = null;
            }
            if (currentPresetSubmittersColumn != null) {
                ((GameCreditsTopToBotList)currentPresetSubmittersColumn).add(new WaitCreditsDisplay(waitBetweenSectionsTime));
                presetSubmittersContent.add((GameCreditsDisplay)currentPresetSubmittersColumn);
            }
            presetSubmittersTitle.add(presetSubmittersContent);
            this.add(new FadeWrapperCreditsDisplay(presetSubmittersTitle, 0, fadeOutTime));
        }
        this.add(new WaitCreditsDisplay(waitBetweenSectionsTime));
        GameCreditsTopToBotList specialThanksTitle = new GameCreditsTopToBotList(centerText, true);
        specialThanksTitle.add(new TextFadeCreditsDisplay(nameTitleFadeInTime, 0, 0, new LocalMessage("credits", "specialthanks"), 32, centerText));
        specialThanksTitle.add(new WaitCreditsDisplay(1, 0, 10));
        GameCreditsSinglesList specialThanksContent = new GameCreditsSinglesList(centerText, false);
        GameCreditsTopToBotList currentSpecialThanksColumn = null;
        for (GameMessage presetSubmitter : this.specialThanks) {
            if (currentSpecialThanksColumn == null) {
                currentSpecialThanksColumn = new GameCreditsTopToBotList(centerText, true);
            }
            currentSpecialThanksColumn.add(new TextFadeCreditsDisplay(nameTitleFadeInTime, 0, 0, presetSubmitter, 20, centerText));
            if (currentSpecialThanksColumn.size() < 15) continue;
            currentSpecialThanksColumn.add(new WaitCreditsDisplay(namesWaitBaseTime));
            specialThanksContent.add(new FadeWrapperCreditsDisplay(currentSpecialThanksColumn, 0, fadeOutTime));
            currentSpecialThanksColumn = null;
        }
        if (currentSpecialThanksColumn != null) {
            currentSpecialThanksColumn.add(new WaitCreditsDisplay(namesWaitBaseTime));
            specialThanksContent.add(new FadeWrapperCreditsDisplay(currentSpecialThanksColumn, 0, fadeOutTime));
        }
        GameCreditsTopToBotList lastSpecialThanks = new GameCreditsTopToBotList(centerText, true);
        lastSpecialThanks.add(new TextFadeCreditsDisplay(nameTitleFadeInTime, 0, 0, new LocalMessage("credits", "finalthanks"), 20, 400, centerText));
        lastSpecialThanks.add(new WaitCreditsDisplay(1000, 0, 20));
        TextFadeCreditsDisplay finalHeart = new TextFadeCreditsDisplay(fadeInTime, 2000, 0, new StaticMessage(""), 32, centerText);
        for (int i = 0; i < 7; ++i) {
            finalHeart.endGlyphs.add(new FairGameSpriteGlyph(Settings.UI.heart_fill, 0, -3));
            if (i >= 6) continue;
            finalHeart.endGlyphs.add(new FairSpacerGlyph(5.0f, 5.0f));
        }
        lastSpecialThanks.add(finalHeart);
        lastSpecialThanks.add(new WaitCreditsDisplay(waitBetweenSectionsTime, 0, 40));
        GameCreditsHorizontalList logoList = new GameCreditsHorizontalList(centerText);
        logoList.add(new TextFadeCreditsDisplay(0, 100, 0, new StaticMessage("\"Necesse\", a game by"), 20, centerText));
        logoList.add(new WaitCreditsDisplay(1, 0, 10));
        logoList.add(new GameSpriteCreditsDisplay(0, 100, 0, GameResources.fairGamesLogo, 100, 400, false));
        lastSpecialThanks.add(new FadeWrapperCreditsDisplay(logoList, fadeInTime, 0));
        lastSpecialThanks.add(new WaitCreditsDisplay(titleTextTime * 3));
        specialThanksContent.add(lastSpecialThanks);
        specialThanksTitle.add(specialThanksContent);
        this.add(new FadeWrapperCreditsDisplay(specialThanksTitle, 0, fadeOutTime * 2));
        this.add(new WaitCreditsDisplay(1000));
    }
}

