/*
 * Decompiled with CFR 0.152.
 */
package necesse.gfx;

import java.awt.Color;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.Collections;
import java.util.HashMap;
import necesse.engine.GameLoadingScreen;
import necesse.engine.GlobalData;
import necesse.engine.Settings;
import necesse.engine.incursionPerkTree.IncursionPerk;
import necesse.engine.localization.Localization;
import necesse.engine.registries.BiomeRegistry;
import necesse.engine.registries.BuffRegistry;
import necesse.engine.registries.IncursionBiomeRegistry;
import necesse.engine.registries.IncursionPerksRegistry;
import necesse.engine.registries.ItemRegistry;
import necesse.engine.registries.LogicGateRegistry;
import necesse.engine.registries.MapIconRegistry;
import necesse.engine.registries.MobRegistry;
import necesse.engine.registries.MusicRegistry;
import necesse.engine.registries.ObjectRegistry;
import necesse.engine.registries.ProjectileRegistry;
import necesse.engine.registries.SettlerRegistry;
import necesse.engine.registries.TileRegistry;
import necesse.engine.sound.GameMusic;
import necesse.engine.sound.SameNearRandomSoundCooldown;
import necesse.engine.sound.SameNearSoundCooldown;
import necesse.engine.sound.gameSound.GameSound;
import necesse.engine.util.GameMath;
import necesse.engine.window.GameWindow;
import necesse.engine.window.WindowManager;
import necesse.entity.mobs.buffs.staticBuffs.Buff;
import necesse.gfx.HumanLook;
import necesse.gfx.gameTexture.GameTexture;
import necesse.gfx.gameTexture.GameTextureSection;
import necesse.gfx.gameTexture.SharedGameTexture;
import necesse.gfx.shader.AscendedVoidShader;
import necesse.gfx.shader.ColorShader;
import necesse.gfx.shader.DarknessShader;
import necesse.gfx.shader.EdgeMaskShader;
import necesse.gfx.shader.FormShader;
import necesse.gfx.shader.GameShader;
import necesse.gfx.shader.LiquidShader;
import necesse.gfx.shader.PixelScalingShader;
import necesse.gfx.shader.RainShader;
import necesse.gfx.shader.RectangleShader;
import necesse.gfx.shader.SharpenShader;
import necesse.gfx.shader.ShockwaveShader;
import necesse.gfx.shader.TextureOffsetShader;
import necesse.gfx.shader.WaveShader;
import necesse.gfx.shader.WhiteShader;
import necesse.gfx.ui.GameInterfaceStyle;
import necesse.inventory.item.Item;
import necesse.level.gameLogicGate.GameLogicGate;
import necesse.level.gameObject.GameObject;
import necesse.level.gameObject.WallObject;
import necesse.level.gameTile.GameTile;
import necesse.level.maps.biomes.Biome;
import necesse.level.maps.incursion.IncursionBiome;
import necesse.level.maps.mapData.GameMapIcon;

public class GameResources {
    private static HashMap<String, GameShader> shaders;
    public static GameTexture error;
    public static GameTexture empty;
    public static GameTexture cursors;
    public static GameTexture wire;
    public static GameTexture fairGamesLogo;
    public static GameTexture item_shadow;
    public static GameTexture chains;
    public static GameTexture aim;
    public static GameTexture aimArrow;
    public static GameTexture gradient;
    public static GameTexture flash;
    public static GameTexture tileDamageOverlay;
    public static GameTexture dredgingStaffPillars;
    public static GameTexture ancientDredgingStaffPillars;
    public static GameTexture slimeGround;
    public static GameTexture slimeSpike;
    public static GameTexture ascendedSlimeGround;
    public static GameTexture ascendedSlimeSpike;
    public static GameTexture webParticles;
    public static GameTexture empressAcid;
    public static GameTexture spideriteStaffWeb;
    public static GameTexture smokeParticles;
    public static GameTexture hydroPumpParticles;
    public static GameTexture fallenWizardPortalParticle;
    public static GameTextureSection particles;
    public static GameTextureSection fogParticles;
    public static GameTextureSection poisonCloudParticles;
    public static GameTextureSection debrisParticles;
    public static GameTextureSection puffParticles;
    public static GameTextureSection voidPuffParticles;
    public static GameTextureSection magicSparkParticles;
    public static GameTextureSection rainBlobParticle;
    public static GameTextureSection glintParticles;
    public static GameTextureSection sleepParticles;
    public static GameTextureSection pearlescentShardParticles;
    public static GameTextureSection amethystShardParticles;
    public static GameTextureSection sapphireShardParticles;
    public static GameTextureSection emeraldShardParticles;
    public static GameTextureSection rubyShardParticles;
    public static GameTextureSection topazShardParticles;
    public static GameTextureSection starParticles;
    public static GameTextureSection healingParticles;
    public static GameTextureSection liquidBlobParticle;
    public static GameTextureSection bubbleParticle;
    public static GameTextureSection explosiveModifierChargeUp;
    public static GameTextureSection smokePuff;
    public static GameTextureSection stabbyBushParticles;
    public static GameTextureSection heartParticle;
    public static GameTextureSection mapleLeafParticles;
    public static GameTextureSection dryadLeafParticles;
    public static GameTextureSection quicksandBlob;
    public static GameTextureSection powerupParticle;
    public static GameTextureSection sentientSword;
    public static GameTextureSection agedChampionWaveParticles;
    public static GameTextureSection bulletCasingParticles;
    public static GameTextureSection reverseDamageParticles;
    public static GameTextureSection ascendedParticle;
    public static GameTextureSection ascendedShadeParticle;
    public static GameTexture ascendedFractureParticle;
    public static GameTexture ascendedSparklesParticles;
    public static GameTexture ascendedVoidStarParticles;
    public static GameTexture voidRainParticle;
    public static GameTexture voidRainTargetParticle;
    public static GameTexture generatedParticlesTexture;
    public static GameTexture theCrimsonSkyBloodPool;
    public static GameTexture stormingParticleTexture;
    public static GameTexture slimeGreatbowSlime;
    public static GameTexture cutSnowballParticles;
    public static GameTexture starBarrierPickup;
    public static GameTexture empowermentBuffPickup;
    public static GameTexture coinStackIcon;
    public static GameTexture lockedPerkOverlay;
    public static GameTexture perkTreeFallenAltar;
    public static GameTexture perkTreeVial;
    public static GameTexture perkTreeLines;
    public static GameTexture perkTreeChains;
    public static GameTexture perkTreePerkLocksOtherPerksBorder;
    public static GameTexture perkTreeCanBuyPerkBorder;
    public static GameTexture perkTreeOwnsPerkBorder;
    public static GameTexture perkTreePerkBorder;
    public static GameTexture crystalBomb;
    public static GameTexture electricOrb;
    public static GameTexture smallBoneSpikes;
    public static GameTexture smallEarthSpikes;
    public static GameTexture sapphireGlyphParticle;
    public static GameTexture sapphireGlyphCircleParticle;
    public static GameTexture sapphireGlyphAnim;
    public static GameTexture amethystGlyphParticle;
    public static GameTexture amethystGlyphCircleParticle;
    public static GameTexture rubyGlyphParticle;
    public static GameTexture rubyGlyphCircleParticle;
    public static GameTexture emeraldGlyphParticle;
    public static GameTexture emeraldGlyphCircleParticle;
    public static GameTexture topazGlyphParticle;
    public static GameTexture topazGlyphCircleParticle;
    public static GameTexture nettedDebuffNet;
    public static GameTexture ticTacToeX;
    public static GameTexture ticTacToeO;
    public static GameTexture runeGoo;
    public static GameTexture cursedCroneSpiritGlyph;
    public static GameTexture chickenGlyphParticle;
    public static GameTexture bounceGlyphParticle;
    public static GameTexture reverseDamageGlyphParticle;
    public static GameTexture wanderbotGlyphParticle;
    public static GameTexture shockbyte_logo;
    public static SharedGameTexture particlesTextureGenerator;
    public static GameSound journalchallengecompleted;
    public static GameSound alljournalchallengescompleted;
    public static GameSound rain1;
    public static GameSound rain2;
    public static GameSound rain3;
    public static GameSound rain4;
    public static GameSound rain5;
    public static GameSound wind1;
    public static GameSound wind2;
    public static GameSound wind3;
    public static GameSound windDesert1;
    public static GameSound windDesert2;
    public static GameSound windDesert3;
    public static GameSound windPlains1;
    public static GameSound windPlains2;
    public static GameSound windPlains3;
    public static GameSound windSnow1;
    public static GameSound windSnow2;
    public static GameSound windSnow3;
    public static GameSound windSwamp1;
    public static GameSound windSwamp2;
    public static GameSound windSwamp3;
    public static GameSound tap;
    public static GameSound tap2;
    public static GameSound tick;
    public static GameSound pop;
    public static GameSound swing1;
    public static GameSound swing2;
    public static GameSound flick;
    public static GameSound spit;
    public static GameSound crack;
    public static GameSound crackdeath;
    public static GameSound bow;
    public static GameSound drink;
    public static GameSound eat;
    public static GameSound bowhit;
    public static GameSound gunhit;
    public static GameSound jingle;
    public static GameSound jinglehit;
    public static GameSound hoverboots;
    public static GameSound magicbolt1;
    public static GameSound magicbolt2;
    public static GameSound magicbolt3;
    public static GameSound magicbolt4;
    public static GameSound firespell1;
    public static GameSound dragonfly1;
    public static GameSound swoosh;
    public static GameSound swoosh2;
    public static GameSound handgun;
    public static GameSound sniperrifle;
    public static GameSound shotgun;
    public static GameSound hurt;
    public static GameSound npchurt;
    public static GameSound npcdeath;
    public static GameSound fizz;
    public static GameSound roar;
    public static GameSound magicroar;
    public static GameSound warcry;
    public static GameSound warcryshort;
    public static GameSound warcryumf;
    public static GameSound explosionHeavy;
    public static GameSound explosionLight;
    public static GameSound teleport;
    public static GameSound teleportfail;
    public static GameSound splash;
    public static GameSound punch;
    public static GameSound cratebreak1;
    public static GameSound cratebreak2;
    public static GameSound cratebreak3;
    public static GameSound waterblob;
    public static GameSound watersplash;
    public static GameSound grass;
    public static GameSound coins;
    public static GameSound coinsPlace;
    public static GameSound shatter1;
    public static GameSound shatter2;
    public static GameSound leafpiledestroy;
    public static GameSound leavesbreak1;
    public static GameSound leavesbreak2;
    public static GameSound leavesbreak3;
    public static GameSound leavesbreak4;
    public static GameSound squeak;
    public static GameSound chestopen;
    public static GameSound chestclose;
    public static GameSound dooropen;
    public static GameSound doorclose;
    public static GameSound blunthit;
    public static GameSound shake;
    public static GameSound rumble;
    public static GameSound shears;
    public static GameSound run;
    public static GameSound stomp;
    public static GameSound train;
    public static GameSound trainBrake;
    public static GameSound cling;
    public static GameSound laserBeam1;
    public static GameSound laserBlast1;
    public static GameSound laserBlast2;
    public static GameSound fadedeath1;
    public static GameSound fadedeath2;
    public static GameSound fadedeath3;
    public static GameSound iceHit;
    public static GameSound iceCrack1;
    public static GameSound iceCrack2;
    public static GameSound iceCrack3;
    public static GameSound iceBreak;
    public static GameSound cameraShutter;
    public static GameSound fireworkFuse;
    public static GameSound fireworkExplosion;
    public static GameSound fireworkCrack;
    public static GameSound crystalHit1;
    public static GameSound crystalHit2;
    public static GameSound crystalHit3;
    public static GameSound zap1;
    public static GameSound zap2;
    public static GameSound electricLoop;
    public static GameSound electricExplosion;
    public static GameSound bassNote;
    public static GameSound hatNote;
    public static GameSound kickNote;
    public static GameSound pianoNote;
    public static GameSound snareNote;
    public static GameSound glyphChargeUp;
    public static GameSound mosquitoBuzz;
    public static GameSound batAmbient;
    public static GameSound cavelingHurt;
    public static GameSound cavelingDeath;
    public static GameSound icicleRumble;
    public static GameSound icicleFall;
    public static GameSound icicleImpact;
    public static GameSound spiritBeam;
    public static GameSound croneLaugh;
    public static GameSound dryadSentinelGrowl;
    public static GameSound glyphTrapCharge;
    public static GameSound glyphTrapChicken;
    public static GameSound glyphTrapReverseDamage;
    public static GameSound bounce;
    public static GameSound humanChicken;
    public static GameSound fireShot;
    public static GameSound flamelingShooterPopIn;
    public static GameSound cowAmbient;
    public static GameSound cowHurt;
    public static GameSound cowDeath;
    public static GameSound polarBearAmbient;
    public static GameSound polarBearHurt;
    public static GameSound polarBearDeath;
    public static GameSound boarAmbient;
    public static GameSound boarHurt;
    public static GameSound boarDeath;
    public static GameSound ramAmbient;
    public static GameSound ramHurt;
    public static GameSound ramDeath;
    public static GameSound rabbitAmbient1;
    public static GameSound rabbitAmbient2;
    public static GameSound rabbitHurt;
    public static GameSound rabbitDeath;
    public static GameSound beeAmbient1;
    public static GameSound beeAmbient2;
    public static GameSound beeAmbient3;
    public static GameSound beeAmbient4;
    public static GameSound frogHurt;
    public static GameSound frogDeath;
    public static GameSound frogAmbient1;
    public static GameSound frogAmbient2;
    public static GameSound frogAmbient3;
    public static GameSound crabAmbient;
    public static GameSound crabDeath;
    public static GameSound scorpionAmbient;
    public static GameSound scorpionDeath;
    public static GameSound turtleAmbient;
    public static GameSound turtleDeath;
    public static GameSound swampSlugAmbient;
    public static GameSound swampSlugDeath;
    public static GameSound squirrelAmbient;
    public static GameSound squirrelDeath;
    public static GameSound caveCropplerAmbient;
    public static GameSound caveCropplerDeath;
    public static GameSound critterSpiderAmbient;
    public static GameSound critterSpiderDeath;
    public static GameSound mouseAmbient;
    public static GameSound mouseDeath;
    public static GameSound chickenAmbient;
    public static GameSound chickenHurt;
    public static GameSound chickenDeath;
    public static GameSound bullAmbient;
    public static GameSound bullHurt;
    public static GameSound bullDeath;
    public static GameSound grizzlyAmbient;
    public static GameSound grizzlyHurt;
    public static GameSound grizzlyDeath;
    public static GameSound grizzlySleep;
    public static GameSound ostrichAmbient;
    public static GameSound ostrichHurt;
    public static GameSound ostrichDeath;
    public static GameSound penguinAmbient;
    public static GameSound penguinHurt;
    public static GameSound penguinDeath;
    public static GameSound pigAmbient;
    public static GameSound pigHurt;
    public static GameSound pigDeath;
    public static GameSound roosterAmbient;
    public static GameSound roosterHurt;
    public static GameSound roosterDeath;
    public static GameSound sheepAmbient;
    public static GameSound sheepHurt;
    public static GameSound sheepDeath;
    public static GameSound nunchucks;
    public static GameSound spiderclaw;
    public static GameSound evilsprotectorbegin;
    public static GameSound evilsprotectorhurt;
    public static GameSound evilsprotectordeath;
    public static GameSound queenspiderbegin;
    public static GameSound queenspiderhurt;
    public static GameSound queenspiderdeath;
    public static GameSound voidwizardbegin;
    public static GameSound voidwizardhurt;
    public static GameSound voidwizarddeath;
    public static GameSound chieftainbegin;
    public static GameSound chieftainhurt;
    public static GameSound chieftaindeath;
    public static GameSound swampguardianbegin;
    public static GameSound swampguardianhurt;
    public static GameSound swampguardiandeath;
    public static GameSound ancientvulturebegin;
    public static GameSound ancientvulturehurt;
    public static GameSound ancientvulturedeath;
    public static GameSound piratecaptainbegin;
    public static GameSound piratecaptainhurt;
    public static GameSound piratecaptaindeath;
    public static GameSound reaperbegin;
    public static GameSound reaperhurt;
    public static GameSound reaperdeath;
    public static GameSound cryoqueenbegin;
    public static GameSound cryoqueenhurt;
    public static GameSound cryoqueendeath;
    public static GameSound cursedcronebegin;
    public static GameSound cursedcronehurt;
    public static GameSound cursedcronedeath;
    public static GameSound pestwardenbegin;
    public static GameSound pestwardenhurt;
    public static GameSound pestwardendeath;
    public static GameSound gritbegin;
    public static GameSound grithurt;
    public static GameSound gritdeath;
    public static GameSound sagebegin;
    public static GameSound sagehurt;
    public static GameSound sagedeath;
    public static GameSound fallenwizardbegin;
    public static GameSound fallenwizardhurt;
    public static GameSound fallenwizarddeath;
    public static GameSound motherslimebegin;
    public static GameSound motherslimehurt;
    public static GameSound motherslimedeath;
    public static GameSound nightswarmbegin;
    public static GameSound nightswarmhurt;
    public static GameSound nightswarmdeath;
    public static GameSound nightswarmdeathfinal;
    public static GameSound spiderempressbegin;
    public static GameSound spiderempresshurt;
    public static GameSound spiderempressdeath;
    public static GameSound sunlightchampionbegin;
    public static GameSound sunlightchampionhurt;
    public static GameSound sunlightchampiondeath;
    public static GameSound moonlightdancerbegin;
    public static GameSound moonlightdancerhurt;
    public static GameSound moonlightdancerdeath;
    public static GameSound crystaldragonbegin;
    public static GameSound crystaldragonhurt;
    public static GameSound crystaldragondeath;
    public static GameSound ascendedPylonDeath;
    public static GameSound blackholeBegin;
    public static GameSound ascendedWizardBegin;
    public static GameSound ascendedWizardHurt1;
    public static GameSound ascendedWizardHurt2;
    public static GameSound ascendedWizardHurt3;
    public static GameSound ascendedWizardStage1End;
    public static GameSound ascendedWizardStage2Begin;
    public static GameSound ascendedWizardStage2Hurt1;
    public static GameSound ascendedWizardStage2Hurt2;
    public static GameSound ascendedWizardStage2Hurt3;
    public static GameSound ascendedWizardStage2End;
    public static GameSound ascendedWizardFlashBegin;
    public static GameSound theVoidBegin;
    public static GameSound theVoidDeath;
    public static GameSound theVoidFlashBegin;
    public static GameSound theVoidHurt1;
    public static GameSound theVoidHurt2;
    public static GameSound theVoidHurt3;
    public static GameSound theVoidHurt4;
    public static GameSound slimeSplash1;
    public static GameSound slimeSplash2;
    public static GameSound slimeSplash3;
    public static GameSound slimeSplash4;
    public static GameSound defaultOpen;
    public static GameSound alchemyTableOpen;
    public static GameSound anvilOpen;
    public static GameSound workstationOpen;
    public static GameSound landscapingStationOpen;
    public static GameSound drawerOpen;
    public static GameSound cabinetdoorOpen;
    public static GameSound bookShuffle;
    public static GameSound petParrot;
    public static GameSound walkingTorch;
    public static GameSound petPenguin;
    public static GameSound petEvilMinion;
    public static GameSound petGrizzlyCub;
    public static GameSound seahorseAmbient;
    public static GameSound hoverboard;
    public static GameSound woodBoat;
    public static GameSound steelBoat;
    public static GameSound witchBroom;
    public static GameSound[] birdAmbients;
    public static GameSound[] duckAmbients;
    public static GameSound duckHurt;
    public static GameSound duckDeath;
    public static GameSound[] zombieGroans;
    public static GameSound[] flagNoises;
    public static GameSound campfireAmbient;
    public static GameSound campfireSizzle;
    public static GameSound runningWater;
    public static GameSound dropSizzle;
    public static GameSound fishingRodSwing;
    public static GameSound fishingRodReel;
    public static GameSound burningFuse;
    public static GameSound defaultSpear;
    public static GameSound cryoSpear;
    public static GameSound ravenBeakSpear;
    public static GameSound vulturesTalon;
    public static GameSound singleBladedGlaive;
    public static GameSound cryoGlaive;
    public static GameSound slimeGlaive;
    public static GameSound regularSwords;
    public static GameSound gemstoneSwords;
    public static GameSound causticExecutioner;
    public static GameSound bloowClawSwing;
    public static GameSound bloodClawShoot;
    public static GameSound fishianWarriorHook;
    public static GameSound lightningHammer;
    public static GameSound sandKnife;
    public static GameSound venomSlasher;
    public static GameSound woodSword;
    public static GameSound katanaSwing;
    public static GameSound katanaChargeBegin;
    public static GameSound katanaDashReady;
    public static GameSound katanaDash;
    public static GameSound boxingGloveGun;
    public static GameSound heavyHammer;
    public static GameSound reaperScythe;
    public static GameSound carapaceDagger;
    public static GameSound iceJavelin;
    public static GameSound ninjaStar;
    public static GameSound snowBall;
    public static GameSound snowBallHit;
    public static GameSound cryoBlaster;
    public static GameSound flintLock;
    public static GameSound antiqueRifle;
    public static GameSound deathRipperCharge;
    public static GameSound swampTome;
    public static GameSound bloodBolt;
    public static GameSound shadowBolt;
    public static GameSound bloodGrimoire;
    public static GameSound bloodVolley;
    public static GameSound frostPiercer;
    public static GameSound frostPiercerHit;
    public static GameSound genieLamp;
    public static GameSound dragonLance;
    public static GameSound reapersCall;
    public static GameSound reaperSpiritDeath;
    public static GameSound rubyShields;
    public static GameSound bashyBushAmbient;
    public static GameSound bashyBushHurt;
    public static GameSound bashyBushAttack;
    public static GameSound magicSwing;
    public static GameSound magicExplosion;
    public static GameSound sapphireStaff;
    public static GameSound rubyStaff;
    public static GameSound emeraldStaff;
    public static GameSound amethystStaff;
    public static GameSound crystalGlyph;
    public static GameSound emeraldWand;
    public static GameSound sparkler;
    public static GameSound regularBoomerang;
    public static GameSound butchersCleaver;
    public static GameSound dragonsReboundOrange;
    public static GameSound dragonsReboundBlue;
    public static GameSound frostBoomerang;
    public static GameSound nightRazor;
    public static GameSound razorBlade;
    public static GameSound rollingPin;
    public static GameSound rollingPinHit;
    public static GameSound spiderBoomerang;
    public static GameSound tungstenBoomerang;
    public static GameSound voidBoomerang;
    public static GameSound glacialBoomerang;
    public static GameSound glacialBoomerangHold;
    public static GameSound regularGreatSwords1;
    public static GameSound regularGreatSwords2;
    public static GameSound regularGreatSwords3;
    public static GameSound brutesBattleAxe1;
    public static GameSound brutesBattleAxe2;
    public static GameSound brutesBattleAxe3;
    public static GameSound dryadGreatHammer1;
    public static GameSound dryadGreatHammer2;
    public static GameSound necroticGreatsword1;
    public static GameSound necroticGreatsword2;
    public static GameSound necroticGreatsword3;
    public static GameSound necroticGreatswordWaveProjectile;
    public static GameSound ravenwingGreatsword1;
    public static GameSound ravenwingGreatsword2;
    public static GameSound ravenwingGreatsword3;
    public static GameSound woodGreatsword1;
    public static GameSound woodGreatsword2;
    public static GameSound woodGreatsword3;
    public static GameSound slimeGreatsword1;
    public static GameSound slimeGreatsword2;
    public static GameSound slimeGreatsword3;
    public static GameSound slimeSpawn;
    public static GameSound slimeGreatswordWaveProjectile;
    public static GameSound greatbowCharge;
    public static GameSound greatbowChargeComplete;
    public static GameSound regularGreatBowWeak;
    public static GameSound regularGreatBowStrong;
    public static GameSound myceliumGreatBowWeak;
    public static GameSound myceliumGreatBowStrong;
    public static GameSound nightPiercerGreatBowWeak;
    public static GameSound nightPiercerGreatBowStrong;
    public static GameSound slimeGreatBowWeak;
    public static GameSound slimeGreatBowStrong;
    public static GameSound druidsGreatBowWeak;
    public static GameSound druidsGreatBowStrong;
    public static GameSound cryoSetStorm;
    public static LiquidShader liquidShader;
    public static WaveShader waveShader;
    public static RainShader rainShader;
    public static TextureOffsetShader textureOffsetShader;
    public static RectangleShader rectangleShader;
    public static EdgeMaskShader edgeMaskShader;
    public static FormShader formShader;
    public static SharpenShader sharpenShader;
    public static GameShader whiteShader;
    public static ColorShader colorSettingShader;
    public static ColorShader debugColorShader;
    public static ColorShader brightnessShader;
    public static ColorShader windowColorShader;
    public static GameShader horizontalGaussShader;
    public static GameShader verticalGaussShader;
    public static PixelScalingShader pixelScalingShader;
    public static DarknessShader darknessShader;
    public static ShockwaveShader shockwaveShader;
    public static ShockwaveShader shockwaveTestShader;
    public static AscendedVoidShader ascendedVoidShader;

    public static void loadTextures() {
        GameLoadingScreen.drawLoadingString(Localization.translate("loading", "textures"));
        GameTexture texture = new GameTexture("empty", 1, 1);
        texture.setPixel(0, 0, 255, 255, 255, 255);
        texture.makeFinal();
        empty = texture;
        error = GameTexture.fromFile("error");
        cursors = GameTexture.fromFile("cursors");
        wire = GameTexture.fromFile("wire");
        fairGamesLogo = GameTexture.fromFile("fairgames");
        item_shadow = GameTexture.fromFile("items/item_shadow");
        for (GameInterfaceStyle gameInterfaceStyle : GameInterfaceStyle.styles) {
            gameInterfaceStyle.loadTextures();
        }
        chains = GameTexture.fromFile("chains");
        aim = GameTexture.fromFile("aim");
        aimArrow = GameTexture.fromFile("aimarrow");
        gradient = GameTexture.fromFile("gradient");
        flash = GameTexture.fromFile("flash");
        tileDamageOverlay = GameTexture.fromFile("tiles/breaktileoverlay");
        SettlerRegistry.loadSettlerIconTextures();
        GlobalData.achievements().loadTextures();
        HumanLook.loadTextures();
        GameLoadingScreen.drawLoadingString(Localization.translate("loading", "textures"));
        MobRegistry.Textures.load();
        ProjectileRegistry.Textures.load();
        particlesTextureGenerator = new SharedGameTexture("particlesShared");
        particles = particlesTextureGenerator.addTexture(GameTexture.fromFile("particles/particles"));
        fogParticles = particlesTextureGenerator.addTexture(GameTexture.fromFile("particles/fog"));
        poisonCloudParticles = particlesTextureGenerator.addTexture(GameTexture.fromFile("particles/poisoncloud"));
        debrisParticles = particlesTextureGenerator.addTexture(GameTexture.fromFile("particles/debris"));
        puffParticles = particlesTextureGenerator.addTexture(GameTexture.fromFile("particles/puffs"));
        voidPuffParticles = particlesTextureGenerator.addTexture(GameTexture.fromFile("particles/voidpuffs"));
        magicSparkParticles = particlesTextureGenerator.addTexture(GameTexture.fromFile("particles/magicalspark"));
        rainBlobParticle = particlesTextureGenerator.addTexture(GameTexture.fromFile("particles/rainblob"));
        glintParticles = particlesTextureGenerator.addTexture(GameTexture.fromFile("particles/glint"));
        sleepParticles = particlesTextureGenerator.addTexture(GameTexture.fromFile("particles/sleepparticle"));
        pearlescentShardParticles = particlesTextureGenerator.addTexture(GameTexture.fromFile("particles/pearlescentshard"));
        amethystShardParticles = particlesTextureGenerator.addTexture(GameTexture.fromFile("particles/amethystshard"));
        sapphireShardParticles = particlesTextureGenerator.addTexture(GameTexture.fromFile("particles/sapphireshard"));
        emeraldShardParticles = particlesTextureGenerator.addTexture(GameTexture.fromFile("particles/emeraldshard"));
        rubyShardParticles = particlesTextureGenerator.addTexture(GameTexture.fromFile("particles/rubyshard"));
        topazShardParticles = particlesTextureGenerator.addTexture(GameTexture.fromFile("particles/topazshard"));
        starParticles = particlesTextureGenerator.addTexture(GameTexture.fromFile("particles/star"));
        healingParticles = particlesTextureGenerator.addTexture(GameTexture.fromFile("particles/healing"));
        liquidBlobParticle = particlesTextureGenerator.addTexture(GameTexture.fromFile("particles/liquidblob"));
        quicksandBlob = particlesTextureGenerator.addTexture(GameTexture.fromFile("particles/quicksandblob"));
        bubbleParticle = particlesTextureGenerator.addTexture(GameTexture.fromFile("particles/bubble"));
        explosiveModifierChargeUp = particlesTextureGenerator.addTexture(GameTexture.fromFile("particles/incursionexplosivemodifierchargeup"));
        stabbyBushParticles = particlesTextureGenerator.addTexture(GameTexture.fromFile("particles/stabbybush_particles"));
        heartParticle = particlesTextureGenerator.addTexture(GameTexture.fromFile("particles/heart_particle"));
        mapleLeafParticles = particlesTextureGenerator.addTexture(GameTexture.fromFile("particles/mapleleaves"));
        dryadLeafParticles = particlesTextureGenerator.addTexture(GameTexture.fromFile("particles/dryadleaves"));
        powerupParticle = particlesTextureGenerator.addTexture(GameTexture.fromFile("particles/powerupparticle"));
        sentientSword = particlesTextureGenerator.addTexture(GameTexture.fromFile("particles/sentientswordparticle"));
        agedChampionWaveParticles = particlesTextureGenerator.addTexture(GameTexture.fromFile("projectiles/agedchampionwave"));
        bulletCasingParticles = particlesTextureGenerator.addTexture(GameTexture.fromFile("particles/bulletcasing"));
        reverseDamageParticles = particlesTextureGenerator.addTexture(GameTexture.fromFile("particles/reversedamageparticles"));
        ascendedParticle = particlesTextureGenerator.addTexture(GameTexture.fromFile("particles/ascendedparticle"));
        ascendedShadeParticle = particlesTextureGenerator.addTexture(GameTexture.fromFile("particles/ascendedshadeparticle"));
        smokeParticles = GameTexture.fromFile("particles/smoke");
        hydroPumpParticles = GameTexture.fromFile("particles/hydropump");
        dredgingStaffPillars = GameTexture.fromFile("particles/dredgingstaff");
        slimeGround = GameTexture.fromFile("particles/slimeground");
        slimeSpike = GameTexture.fromFile("particles/slimespike");
        ascendedSlimeGround = GameTexture.fromFile("particles/ascendedslimeground");
        ascendedSlimeSpike = GameTexture.fromFile("particles/ascendedslimespike");
        webParticles = GameTexture.fromFile("particles/smallweb");
        empressAcid = GameTexture.fromFile("particles/empressacid");
        spideriteStaffWeb = GameTexture.fromFile("particles/spideritestaffweb");
        ancientDredgingStaffPillars = GameTexture.fromFile("particles/ancientdredgingstaff");
        fallenWizardPortalParticle = GameTexture.fromFile("particles/fallenwizardportal");
        theCrimsonSkyBloodPool = GameTexture.fromFile("particles/thecrimsonskybloodpool");
        stormingParticleTexture = GameTexture.fromFile("particles/stormingparticle");
        slimeGreatbowSlime = GameTexture.fromFile("particles/slimegreatbowslime");
        cutSnowballParticles = GameTexture.fromFile("particles/snowball_cut");
        starBarrierPickup = GameTexture.fromFile("particles/starbarrier_pickup");
        empowermentBuffPickup = GameTexture.fromFile("particles/empowermentbuff_pickup");
        smokePuff = particlesTextureGenerator.addTexture(GameTexture.fromFile("particles/smokepuff"));
        crystalBomb = GameTexture.fromFile("particles/crystalbomb");
        electricOrb = GameTexture.fromFile("particles/electricorb");
        smallBoneSpikes = GameTexture.fromFile("particles/smallbonespikes");
        smallEarthSpikes = GameTexture.fromFile("particles/smallearthspikes");
        sapphireGlyphParticle = GameTexture.fromFile("particles/sapphireglyphparticle");
        sapphireGlyphCircleParticle = GameTexture.fromFile("particles/sapphireglyphcircleparticle");
        sapphireGlyphAnim = GameTexture.fromFile("particles/sapphireglyphanim");
        amethystGlyphParticle = GameTexture.fromFile("particles/amethystglyphparticle");
        amethystGlyphCircleParticle = GameTexture.fromFile("particles/amethystglyphcircleparticle");
        rubyGlyphParticle = GameTexture.fromFile("particles/rubyglyphparticle");
        rubyGlyphCircleParticle = GameTexture.fromFile("particles/rubyglyphcircleparticle");
        emeraldGlyphParticle = GameTexture.fromFile("particles/emeraldglyphparticle");
        emeraldGlyphCircleParticle = GameTexture.fromFile("particles/emeraldglyphcircleparticle");
        topazGlyphParticle = GameTexture.fromFile("particles/topazglyphparticle");
        topazGlyphCircleParticle = GameTexture.fromFile("particles/topazglyphcircleparticle");
        nettedDebuffNet = GameTexture.fromFile("particles/netted");
        ticTacToeX = GameTexture.fromFile("particles/tttx");
        ticTacToeO = GameTexture.fromFile("particles/ttto");
        runeGoo = GameTexture.fromFile("particles/runegoo");
        cursedCroneSpiritGlyph = GameTexture.fromFile("particles/cursedcronespiritglyph");
        chickenGlyphParticle = GameTexture.fromFile("particles/chickenglyph");
        bounceGlyphParticle = GameTexture.fromFile("particles/bounceglyph");
        reverseDamageGlyphParticle = GameTexture.fromFile("particles/reversedamageglyph");
        ascendedFractureParticle = GameTexture.fromFile("particles/ascendedfracture");
        ascendedSparklesParticles = GameTexture.fromFile("particles/ascendedsparkles");
        ascendedVoidStarParticles = GameTexture.fromFile("particles/ascendedvoidstar");
        voidRainParticle = GameTexture.fromFile("particles/voidrain");
        voidRainTargetParticle = GameTexture.fromFile("particles/voidrain_target");
        wanderbotGlyphParticle = GameTexture.fromFile("particles/wanderbotglyph");
        coinStackIcon = GameTexture.fromFile("items/coinstack");
        shockbyte_logo = GameTexture.fromFile("ui/shockbyte_logo");
        lockedPerkOverlay = GameTexture.fromFile("incursionperks/lockedperkoverlay");
        perkTreeFallenAltar = GameTexture.fromFile("ui/primal/perktreefallenaltar");
        perkTreeVial = GameTexture.fromFile("ui/primal/perktreevial");
        perkTreeLines = GameTexture.fromFile("ui/primal/perk_tree_lines");
        perkTreeChains = GameTexture.fromFile("ui/primal/perk_tree_chains");
        perkTreePerkLocksOtherPerksBorder = GameTexture.fromFile("ui/primal/perk_unlocks_others_border");
        perkTreeCanBuyPerkBorder = GameTexture.fromFile("ui/primal/perk_tree_can_buy_perk_border");
        perkTreeOwnsPerkBorder = GameTexture.fromFile("ui/primal/perk_tree_owns_perk_border");
        perkTreePerkBorder = GameTexture.fromFile("ui/primal/perk_tree_perk_border");
        Biome.setupBiomeTextures();
        GameTile.setupTileTextures();
        WallObject.setupWallTextures();
        for (GameTile gameTile : TileRegistry.getTiles()) {
            gameTile.loadTileTextures();
        }
        for (GameObject gameObject : ObjectRegistry.getObjects()) {
            gameObject.loadTextures();
        }
        for (GameLogicGate gameLogicGate : LogicGateRegistry.getLogicGates()) {
            gameLogicGate.loadTextures();
        }
        for (Item item : ItemRegistry.getItems()) {
            item.loadTextures();
        }
        for (Buff buff : BuffRegistry.getBuffs()) {
            buff.loadTextures();
        }
        for (Biome biome : BiomeRegistry.getBiomes()) {
            biome.loadTextures();
        }
        for (IncursionBiome incursionBiome : IncursionBiomeRegistry.getBiomes()) {
            incursionBiome.loadTextures();
        }
        MobRegistry.loadMobIcons();
        for (GameMapIcon gameMapIcon : MapIconRegistry.getAllIcons()) {
            gameMapIcon.loadTextures();
        }
        for (IncursionPerk incursionPerk : IncursionPerksRegistry.getPerks()) {
            incursionPerk.loadTextures();
        }
        if (GlobalData.isDevMode()) {
            ArrayList<String> unloadedExcludes = new ArrayList<String>(Arrays.asList("cursors", "fonts/bit12", "fonts/bit16", "fonts/bit20", "fonts/bitoutline12", "fonts/bitoutline16", "fonts/bitoutline20"));
            ArrayList<String> arrayList = new ArrayList<String>(Collections.singletonList("ui/input"));
            GameTexture.listUnloadedTextures(unloadedExcludes, arrayList);
        }
    }

    public static void startSoundLoading() {
        int i;
        GameLoadingScreen.drawLoadingString(Localization.translate("loading", "sound"));
        GameSound.startLoaderThreads();
        for (GameMusic music : MusicRegistry.getMusic()) {
            music.loadSound();
        }
        rain1 = GameSound.fromFile("weather/rain1");
        rain2 = GameSound.fromFile("weather/rain2");
        rain3 = GameSound.fromFile("weather/rain3");
        rain4 = GameSound.fromFile("weather/rain4");
        rain5 = GameSound.fromFile("weather/rain5");
        wind1 = GameSound.fromFile("weather/wind1");
        wind2 = GameSound.fromFile("weather/wind2");
        wind3 = GameSound.fromFile("weather/wind3");
        windDesert1 = GameSound.fromFile("weather/winddesert1");
        windDesert2 = GameSound.fromFile("weather/winddesert2");
        windDesert3 = GameSound.fromFile("weather/winddesert3");
        windPlains1 = GameSound.fromFile("weather/windplains1");
        windPlains2 = GameSound.fromFile("weather/windplains2");
        windPlains3 = GameSound.fromFile("weather/windplains3");
        windSnow1 = GameSound.fromFile("weather/windsnow1");
        windSnow2 = GameSound.fromFile("weather/windsnow2");
        windSnow3 = GameSound.fromFile("weather/windsnow3");
        windSwamp1 = GameSound.fromFile("weather/windswamp1");
        windSwamp2 = GameSound.fromFile("weather/windswamp2");
        windSwamp3 = GameSound.fromFile("weather/windswamp3");
        tap = GameSound.fromFile("tap", 10);
        tap2 = GameSound.fromFile("tap2", 10);
        tick = GameSound.fromFile("tick", 10);
        pop = GameSound.fromFile("pop", 100);
        swing1 = GameSound.fromFile("swing1");
        swing2 = GameSound.fromFile("swing2");
        flick = GameSound.fromFile("flick");
        spit = GameSound.fromFile("spit");
        crack = GameSound.fromFile("crack", 100);
        crackdeath = GameSound.fromFile("crackdeath", 100);
        bow = GameSound.fromFile("bow");
        drink = GameSound.fromFile("drink");
        eat = GameSound.fromFile("eat");
        bowhit = GameSound.fromFile("bowhit", 100);
        gunhit = GameSound.fromFile("gunhit", 100);
        jingle = GameSound.fromFile("jingle");
        jinglehit = GameSound.fromFile("jinglehit", 100);
        hoverboots = GameSound.fromFile("hoverboots");
        handgun = GameSound.fromFile("handgun");
        sniperrifle = GameSound.fromFile("sniperrifle");
        shotgun = GameSound.fromFile("shotgun");
        hurt = GameSound.fromFile("hurt", 100);
        npchurt = GameSound.fromFile("npchurt", 100);
        npcdeath = GameSound.fromFile("npcdeath", 100);
        fizz = GameSound.fromFile("fizz");
        roar = GameSound.fromFile("roar");
        magicroar = GameSound.fromFile("magicroar");
        warcry = GameSound.fromFile("warcry");
        warcryshort = GameSound.fromFile("warcryshort");
        warcryumf = GameSound.fromFile("warcryumf");
        explosionHeavy = GameSound.fromFile("explosionheavy");
        explosionLight = GameSound.fromFile("explosionlight");
        teleport = GameSound.fromFile("teleport", 100);
        teleportfail = GameSound.fromFile("teleportfail");
        splash = GameSound.fromFile("splash");
        punch = GameSound.fromFile("punch", 10);
        cratebreak1 = GameSound.fromFile("cratebreak1", 10);
        cratebreak2 = GameSound.fromFile("cratebreak2", 10);
        cratebreak3 = GameSound.fromFile("cratebreak3", 10);
        waterblob = GameSound.fromFile("waterblob");
        watersplash = GameSound.fromFile("watersplash");
        grass = GameSound.fromFile("grass", 10);
        leafpiledestroy = GameSound.fromFile("environment/leafpiledestroy", 100);
        leavesbreak1 = GameSound.fromFile("weather/leavesbreak1", 100);
        leavesbreak2 = GameSound.fromFile("weather/leavesbreak2", 100);
        leavesbreak3 = GameSound.fromFile("weather/leavesbreak3", 100);
        leavesbreak4 = GameSound.fromFile("weather/leavesbreak4", 100);
        coins = GameSound.fromFile("coins", 10);
        coinsPlace = GameSound.fromFile("coinsplace", 10);
        shatter1 = GameSound.fromFile("shatter1", 10);
        shatter2 = GameSound.fromFile("shatter2", 10);
        squeak = GameSound.fromFile("squeak", 100);
        fadedeath1 = GameSound.fromFile("fadedeath1", 100);
        fadedeath2 = GameSound.fromFile("fadedeath2", 100);
        fadedeath3 = GameSound.fromFile("fadedeath3", 100);
        iceHit = GameSound.fromFile("icehit");
        iceCrack1 = GameSound.fromFile("icecrack1");
        iceCrack2 = GameSound.fromFile("icecrack2");
        iceCrack3 = GameSound.fromFile("icecrack3");
        iceBreak = GameSound.fromFile("icebreak");
        blunthit = GameSound.fromFile("blunthit", 50);
        shake = GameSound.fromFile("shake");
        rumble = GameSound.fromFile("rumble");
        shears = GameSound.fromFile("shears");
        run = GameSound.fromFile("run");
        stomp = GameSound.fromFile("stomp");
        train = GameSound.fromFile("train");
        trainBrake = GameSound.fromFile("trainbrake");
        cling = GameSound.fromFile("cling");
        laserBeam1 = GameSound.fromFile("laserbeam1");
        laserBlast1 = GameSound.fromFile("laserblast1");
        laserBlast2 = GameSound.fromFile("laserblast2");
        magicbolt1 = GameSound.fromFile("magicbolt1");
        magicbolt2 = GameSound.fromFile("magicbolt2");
        magicbolt3 = GameSound.fromFile("magicbolt3");
        magicbolt4 = GameSound.fromFile("magicbolt4");
        firespell1 = GameSound.fromFile("firespell1");
        dragonfly1 = GameSound.fromFile("dragonfly1");
        swoosh = GameSound.fromFile("swoosh");
        swoosh2 = GameSound.fromFile("swoosh2");
        cameraShutter = GameSound.fromFile("camerashutter");
        fireworkFuse = GameSound.fromFile("fireworkfuse");
        fireworkExplosion = GameSound.fromFile("fireworkexplosion");
        fireworkCrack = GameSound.fromFile("fireworkcrack");
        crystalHit1 = GameSound.fromFile("crystalhit1", 10);
        crystalHit2 = GameSound.fromFile("crystalhit2", 10);
        crystalHit3 = GameSound.fromFile("crystalhit3", 10);
        zap1 = GameSound.fromFile("zap1", 10);
        zap2 = GameSound.fromFile("zap2", 10);
        electricLoop = GameSound.fromFile("electricloop");
        electricExplosion = GameSound.fromFile("electricexplosion");
        glyphChargeUp = GameSound.fromFile("glyphchargeup");
        mosquitoBuzz = GameSound.fromFile("mosquitobuzz");
        icicleRumble = GameSound.fromFile("iciclerumble");
        icicleFall = GameSound.fromFile("iciclefall");
        icicleImpact = GameSound.fromFile("icicleimpact");
        spiritBeam = GameSound.fromFile("spiritbeam");
        croneLaugh = GameSound.fromFile("cronelaugh");
        dryadSentinelGrowl = GameSound.fromFile("dryadsentinelgrowl");
        glyphTrapCharge = GameSound.fromFile("glyphtrapcharge");
        glyphTrapChicken = GameSound.fromFile("glyphtrapchicken");
        glyphTrapReverseDamage = GameSound.fromFile("glyphtrapreversedamage");
        bounce = GameSound.fromFile("bounce");
        fireShot = GameSound.fromFile("fireshot");
        flamelingShooterPopIn = GameSound.fromFile("flamelingshooterpopin");
        journalchallengecompleted = GameSound.fromFile("journalchallengecompleted");
        alljournalchallengescompleted = GameSound.fromFile("alljournalchallengescompleted");
        slimeSplash1 = GameSound.fromFile("slimesplash1", 100);
        slimeSplash2 = GameSound.fromFile("slimesplash2", 100);
        slimeSplash3 = GameSound.fromFile("slimesplash3", 100);
        slimeSplash4 = GameSound.fromFile("slimesplash4", 100);
        for (i = 0; i < flagNoises.length; ++i) {
            GameResources.flagNoises[i] = GameSound.fromFile("environment/flagnoise" + (i + 1), new SameNearRandomSoundCooldown(3000, 5000, 96));
        }
        runningWater = GameSound.fromFile("environment/runningwater");
        campfireAmbient = GameSound.fromFile("environment/campfire", new SameNearRandomSoundCooldown(2000, 5000, 256));
        campfireSizzle = GameSound.fromFile("environment/campfiresizzle", new SameNearRandomSoundCooldown(2000, 5000, 256));
        dropSizzle = GameSound.fromFile("environment/dropsizzle", new SameNearRandomSoundCooldown(1000, 1000, 256));
        petParrot = GameSound.fromFile("mobs/followers/petparrot", new SameNearRandomSoundCooldown(1500, 2500, 160));
        walkingTorch = GameSound.fromFile("mobs/followers/walkingtorch", new SameNearRandomSoundCooldown(1500, 2500, 160));
        petPenguin = GameSound.fromFile("mobs/followers/petpenguin", new SameNearRandomSoundCooldown(1500, 2500, 160));
        petEvilMinion = GameSound.fromFile("mobs/followers/petevilminion", new SameNearRandomSoundCooldown(1500, 2500, 160));
        petGrizzlyCub = GameSound.fromFile("mobs/followers/petgrizzlycub", new SameNearRandomSoundCooldown(1500, 2500, 160));
        seahorseAmbient = GameSound.fromFile("seahorseambient", new SameNearSoundCooldown(200, 96));
        hoverboard = GameSound.fromFile("hoverboard", new SameNearSoundCooldown(200, 96));
        witchBroom = GameSound.fromFile("witchbroom", new SameNearSoundCooldown(200, 96));
        woodBoat = GameSound.fromFile("woodboat", new SameNearSoundCooldown(200, 96));
        steelBoat = GameSound.fromFile("steelboat", new SameNearSoundCooldown(200, 96));
        fishingRodSwing = GameSound.fromFile("fishingrodswing");
        fishingRodReel = GameSound.fromFile("fishingrodreel");
        defaultOpen = GameSound.fromFile("defaultopen", 100);
        alchemyTableOpen = GameSound.fromFile("alchemytableopen", 100);
        anvilOpen = GameSound.fromFile("anvilopen", 100);
        chestopen = GameSound.fromFile("chestopen", 100);
        chestclose = GameSound.fromFile("chestclose", 100);
        dooropen = GameSound.fromFile("dooropen", 100);
        doorclose = GameSound.fromFile("doorclose", 100);
        drawerOpen = GameSound.fromFile("draweropen", 100);
        cabinetdoorOpen = GameSound.fromFile("cabinetdooropen", 100);
        bookShuffle = GameSound.fromFile("bookshuffle", 100);
        workstationOpen = GameSound.fromFile("workstationopen", 100);
        landscapingStationOpen = GameSound.fromFile("landscapingstationopen", 100);
        cowAmbient = GameSound.fromFile("mobs/animals/cowambient", new SameNearRandomSoundCooldown(2500, 6500, 160));
        cowHurt = GameSound.fromFile("mobs/animals/cowhurt", 500, 1500);
        cowDeath = GameSound.fromFile("mobs/animals/cowdeath");
        humanChicken = GameSound.fromFile("mobs/animals/humanchicken");
        chickenAmbient = GameSound.fromFile("mobs/animals/chickenambient", new SameNearRandomSoundCooldown(2500, 6500, 160));
        chickenHurt = GameSound.fromFile("mobs/animals/chickenhurt", 500, 1500);
        chickenDeath = GameSound.fromFile("mobs/animals/chickendeath");
        bullAmbient = GameSound.fromFile("mobs/animals/bullambient", new SameNearRandomSoundCooldown(2500, 6500, 160));
        bullHurt = GameSound.fromFile("mobs/animals/bullhurt", 500, 1500);
        bullDeath = GameSound.fromFile("mobs/animals/bulldeath");
        grizzlyAmbient = GameSound.fromFile("mobs/animals/grizzlyambient", new SameNearRandomSoundCooldown(2500, 6500, 160));
        grizzlyHurt = GameSound.fromFile("mobs/animals/grizzlyhurt", 500, 1500);
        grizzlyDeath = GameSound.fromFile("mobs/animals/grizzlydeath");
        grizzlySleep = GameSound.fromFile("mobs/animals/bearsleep");
        ostrichAmbient = GameSound.fromFile("mobs/animals/ostrichambient", new SameNearRandomSoundCooldown(2500, 6500, 160));
        ostrichHurt = GameSound.fromFile("mobs/animals/ostrichhurt", 500, 1500);
        ostrichDeath = GameSound.fromFile("mobs/animals/ostrichdeath");
        penguinAmbient = GameSound.fromFile("mobs/animals/penguinambient", new SameNearRandomSoundCooldown(2500, 6500, 160));
        penguinHurt = GameSound.fromFile("mobs/animals/penguinhurt", 500, 1500);
        penguinDeath = GameSound.fromFile("mobs/animals/penguindeath");
        pigAmbient = GameSound.fromFile("mobs/animals/pigambient", new SameNearRandomSoundCooldown(2500, 6500, 160));
        pigHurt = GameSound.fromFile("mobs/animals/pighurt", 500, 1500);
        pigDeath = GameSound.fromFile("mobs/animals/pigdeath");
        roosterAmbient = GameSound.fromFile("mobs/animals/roosterambient", new SameNearRandomSoundCooldown(2500, 6500, 160));
        roosterHurt = GameSound.fromFile("mobs/animals/roosterhurt", 500, 1500);
        roosterDeath = GameSound.fromFile("mobs/animals/roosterdeath");
        sheepAmbient = GameSound.fromFile("mobs/animals/sheepambient", new SameNearRandomSoundCooldown(2500, 6500, 160));
        sheepHurt = GameSound.fromFile("mobs/animals/sheephurt", 500, 1500);
        sheepDeath = GameSound.fromFile("mobs/animals/sheepdeath");
        polarBearAmbient = GameSound.fromFile("mobs/animals/polarbearambient", new SameNearRandomSoundCooldown(2500, 6500, 160));
        polarBearHurt = GameSound.fromFile("mobs/animals/polarbearhurt", 500, 1500);
        polarBearDeath = GameSound.fromFile("mobs/animals/polarbeardeath");
        boarAmbient = GameSound.fromFile("mobs/animals/boarambient", new SameNearRandomSoundCooldown(2500, 6500, 160));
        boarHurt = GameSound.fromFile("mobs/animals/boarhurt", 500, 1500);
        boarDeath = GameSound.fromFile("mobs/animals/boardeath");
        ramAmbient = GameSound.fromFile("mobs/animals/ramambient", new SameNearRandomSoundCooldown(2500, 6500, 160));
        ramHurt = GameSound.fromFile("mobs/animals/ramhurt", 500, 1500);
        ramDeath = GameSound.fromFile("mobs/animals/ramdeath");
        rabbitAmbient1 = GameSound.fromFile("mobs/animals/rabbitambient1", new SameNearRandomSoundCooldown(2500, 6500, 160));
        rabbitAmbient2 = GameSound.fromFile("mobs/animals/rabbitambient2", new SameNearRandomSoundCooldown(2500, 6500, 160));
        rabbitHurt = GameSound.fromFile("mobs/animals/rabbithurt");
        rabbitDeath = GameSound.fromFile("mobs/animals/rabbitdeath");
        beeAmbient1 = GameSound.fromFile("mobs/animals/beeambient1", new SameNearRandomSoundCooldown(2500, 6500, 160));
        beeAmbient2 = GameSound.fromFile("mobs/animals/beeambient2", new SameNearRandomSoundCooldown(2500, 6500, 160));
        beeAmbient3 = GameSound.fromFile("mobs/animals/beeambient3", new SameNearRandomSoundCooldown(2500, 6500, 160));
        beeAmbient4 = GameSound.fromFile("mobs/animals/beeambient4", new SameNearRandomSoundCooldown(2500, 6500, 160));
        frogAmbient1 = GameSound.fromFile("mobs/animals/frogambient1");
        frogAmbient2 = GameSound.fromFile("mobs/animals/frogambient2");
        frogAmbient3 = GameSound.fromFile("mobs/animals/frogambient3");
        frogDeath = GameSound.fromFile("mobs/animals/frogdeath", new SameNearRandomSoundCooldown(1500, 3500, 160));
        frogHurt = GameSound.fromFile("mobs/animals/froghurt", new SameNearRandomSoundCooldown(1500, 3500, 160));
        crabAmbient = GameSound.fromFile("mobs/animals/crabambient", new SameNearRandomSoundCooldown(2500, 6500, 160));
        crabDeath = GameSound.fromFile("mobs/animals/crabdeath");
        scorpionAmbient = GameSound.fromFile("mobs/animals/scorpionambient", new SameNearRandomSoundCooldown(2500, 6500, 160));
        scorpionDeath = GameSound.fromFile("mobs/animals/scorpiondeath");
        mouseAmbient = GameSound.fromFile("mobs/animals/mouseambient", new SameNearRandomSoundCooldown(2500, 6500, 160));
        mouseDeath = GameSound.fromFile("mobs/animals/mousedeath");
        critterSpiderAmbient = GameSound.fromFile("mobs/animals/critterspiderambient", new SameNearRandomSoundCooldown(2500, 6500, 160));
        critterSpiderDeath = GameSound.fromFile("mobs/animals/critterspiderdeath");
        caveCropplerAmbient = GameSound.fromFile("mobs/creatures/cavecropplerambient", new SameNearRandomSoundCooldown(2500, 6500, 160));
        caveCropplerDeath = GameSound.fromFile("mobs/creatures/cavecropplerdeath");
        squirrelAmbient = GameSound.fromFile("mobs/animals/squirrelambient", new SameNearRandomSoundCooldown(2500, 6500, 160));
        squirrelDeath = GameSound.fromFile("mobs/animals/squirreldeath");
        swampSlugAmbient = GameSound.fromFile("mobs/animals/swampslugambient", new SameNearRandomSoundCooldown(2500, 6500, 160));
        swampSlugDeath = GameSound.fromFile("mobs/animals/swampslugdeath");
        turtleAmbient = GameSound.fromFile("mobs/animals/turtleambient", new SameNearRandomSoundCooldown(2500, 6500, 160));
        turtleDeath = GameSound.fromFile("mobs/animals/turtledeath");
        batAmbient = GameSound.fromFile("mobs/animals/batambient", new SameNearRandomSoundCooldown(2500, 6500, 160));
        cavelingHurt = GameSound.fromFile("mobs/creatures/cavelinghurt", new SameNearRandomSoundCooldown(2500, 6500, 256));
        cavelingDeath = GameSound.fromFile("mobs/creatures/cavelingdeath", new SameNearRandomSoundCooldown(2500, 6500, 256));
        for (i = 0; i < duckAmbients.length; ++i) {
            GameResources.duckAmbients[i] = GameSound.fromFile("mobs/animals/duckambient" + (i + 1), new SameNearRandomSoundCooldown(1000, 5000, 96));
        }
        duckHurt = GameSound.fromFile("mobs/animals/duckhurt", new SameNearRandomSoundCooldown(2500, 4500, 160));
        duckDeath = GameSound.fromFile("mobs/animals/duckdeath", new SameNearRandomSoundCooldown(2500, 4500, 160));
        for (i = 0; i < birdAmbients.length; ++i) {
            GameResources.birdAmbients[i] = GameSound.fromFile("mobs/animals/birdambient" + (i + 1), new SameNearRandomSoundCooldown(3000, 5000, 96));
        }
        for (i = 0; i < zombieGroans.length; ++i) {
            GameResources.zombieGroans[i] = GameSound.fromFile("zombiegroan" + (i + 1), new SameNearRandomSoundCooldown(1000, 5000, 96));
        }
        cryoBlaster = GameSound.fromFile("cryoblaster");
        flintLock = GameSound.fromFile("flintlock");
        deathRipperCharge = GameSound.fromFile("deathrippercharge");
        antiqueRifle = GameSound.fromFile("antiquerifle");
        swampTome = GameSound.fromFile("swamptome");
        shadowBolt = GameSound.fromFile("shadowbolt");
        bloodBolt = GameSound.fromFile("bloodbolt");
        bloodVolley = GameSound.fromFile("bloodvolley");
        bloodGrimoire = GameSound.fromFile("bloodgrimoire");
        magicExplosion = GameSound.fromFile("magicexplosion");
        magicSwing = GameSound.fromFile("magicswing");
        rubyStaff = GameSound.fromFile("rubystaff");
        sapphireStaff = GameSound.fromFile("sapphirestaff");
        amethystStaff = GameSound.fromFile("amethyststaff");
        emeraldStaff = GameSound.fromFile("emeraldstaff");
        crystalGlyph = GameSound.fromFile("crystalglyph");
        emeraldWand = GameSound.fromFile("emeraldwand");
        sparkler = GameSound.fromFile("sparkler");
        genieLamp = GameSound.fromFile("genielamp");
        dragonLance = GameSound.fromFile("dragonlance");
        frostPiercer = GameSound.fromFile("frostpiercer", 100);
        frostPiercerHit = GameSound.fromFile("frostpiercerhit", 100);
        reapersCall = GameSound.fromFile("reaperscall", 100);
        reaperSpiritDeath = GameSound.fromFile("mobs/followers/reaperspiritdeath", 100);
        rubyShields = GameSound.fromFile("rubyshields", 100);
        bashyBushAmbient = GameSound.fromFile("bashybushambient", 100);
        bashyBushAttack = GameSound.fromFile("bashybushattack", 500);
        bashyBushHurt = GameSound.fromFile("bashybushhurt", 500);
        regularSwords = GameSound.fromFile("regularswords");
        gemstoneSwords = GameSound.fromFile("gemstoneswords");
        causticExecutioner = GameSound.fromFile("causticexecutioner");
        bloowClawSwing = GameSound.fromFile("bloodclawswing");
        bloodClawShoot = GameSound.fromFile("bloodclawshoot", 100);
        fishianWarriorHook = GameSound.fromFile("fishianwarriorhook");
        lightningHammer = GameSound.fromFile("lightninghammer");
        sandKnife = GameSound.fromFile("sandknife");
        venomSlasher = GameSound.fromFile("venomslasher");
        woodSword = GameSound.fromFile("woodsword");
        katanaSwing = GameSound.fromFile("katanaswing");
        katanaChargeBegin = GameSound.fromFile("katanachargebegin");
        katanaDashReady = GameSound.fromFile("katanadashready");
        katanaDash = GameSound.fromFile("katanadash");
        reaperScythe = GameSound.fromFile("reaperscythe");
        boxingGloveGun = GameSound.fromFile("boxingglovegun");
        nunchucks = GameSound.fromFile("nunchucks");
        spiderclaw = GameSound.fromFile("spiderclaw");
        defaultSpear = GameSound.fromFile("defaultspear");
        cryoSpear = GameSound.fromFile("cryospear");
        ravenBeakSpear = GameSound.fromFile("ravenbeakspear");
        vulturesTalon = GameSound.fromFile("vulturestalon");
        singleBladedGlaive = GameSound.fromFile("singlebladedglaive");
        cryoGlaive = GameSound.fromFile("cryoglaive");
        slimeGlaive = GameSound.fromFile("slimeglaive");
        heavyHammer = GameSound.fromFile("heavyhammer");
        carapaceDagger = GameSound.fromFile("carapacedagger");
        iceJavelin = GameSound.fromFile("icejavelin");
        ninjaStar = GameSound.fromFile("ninjastar");
        snowBall = GameSound.fromFile("snowball");
        snowBallHit = GameSound.fromFile("snowballhit");
        burningFuse = GameSound.fromFile("burningfuse");
        regularBoomerang = GameSound.fromFile("regularboomerang");
        butchersCleaver = GameSound.fromFile("butcherscleaver");
        dragonsReboundBlue = GameSound.fromFile("dragonsreboundblue");
        dragonsReboundOrange = GameSound.fromFile("dragonsreboundorange");
        frostBoomerang = GameSound.fromFile("frostboomerang");
        glacialBoomerang = GameSound.fromFile("glacialboomerang", 100);
        glacialBoomerangHold = GameSound.fromFile("glacialboomeranghold");
        nightRazor = GameSound.fromFile("nightrazor");
        razorBlade = GameSound.fromFile("razorblade");
        rollingPin = GameSound.fromFile("rollingpin");
        rollingPinHit = GameSound.fromFile("rollingpinhit");
        spiderBoomerang = GameSound.fromFile("spiderboomerang");
        tungstenBoomerang = GameSound.fromFile("tungstenboomerang");
        voidBoomerang = GameSound.fromFile("voidboomerang");
        regularGreatSwords1 = GameSound.fromFile("regulargreatswords1");
        regularGreatSwords2 = GameSound.fromFile("regulargreatswords2");
        regularGreatSwords3 = GameSound.fromFile("regulargreatswords3");
        brutesBattleAxe1 = GameSound.fromFile("brutesbattleaxe1");
        brutesBattleAxe2 = GameSound.fromFile("brutesbattleaxe2");
        brutesBattleAxe3 = GameSound.fromFile("brutesbattleaxe3");
        dryadGreatHammer1 = GameSound.fromFile("dryadgreathammer1");
        dryadGreatHammer2 = GameSound.fromFile("dryadgreathammer2");
        necroticGreatsword1 = GameSound.fromFile("necroticgreatsword1");
        necroticGreatsword2 = GameSound.fromFile("necroticgreatsword2");
        necroticGreatsword3 = GameSound.fromFile("necroticgreatsword3");
        necroticGreatswordWaveProjectile = GameSound.fromFile("necroticgreatswordwaveprojectile");
        woodGreatsword1 = GameSound.fromFile("woodgreatsword1");
        woodGreatsword2 = GameSound.fromFile("woodgreatsword2");
        woodGreatsword3 = GameSound.fromFile("woodgreatsword3");
        ravenwingGreatsword1 = GameSound.fromFile("ravenwinggreatsword1");
        ravenwingGreatsword2 = GameSound.fromFile("ravenwinggreatsword2");
        ravenwingGreatsword3 = GameSound.fromFile("ravenwinggreatsword3");
        slimeGreatsword1 = GameSound.fromFile("slimegreatsword1");
        slimeGreatsword2 = GameSound.fromFile("slimegreatsword2");
        slimeGreatsword3 = GameSound.fromFile("slimegreatsword3");
        slimeGreatswordWaveProjectile = GameSound.fromFile("slimegreatswordwaveprojectile");
        slimeSpawn = GameSound.fromFile("slimespawn");
        greatbowCharge = GameSound.fromFile("greatbowcharge");
        greatbowChargeComplete = GameSound.fromFile("greatbowchargecomplete");
        regularGreatBowWeak = GameSound.fromFile("regulargreatbowweak");
        regularGreatBowStrong = GameSound.fromFile("regulargreatbowstrong");
        myceliumGreatBowWeak = GameSound.fromFile("myceliumgreatbowweak");
        myceliumGreatBowStrong = GameSound.fromFile("myceliumgreatbowstrong");
        nightPiercerGreatBowWeak = GameSound.fromFile("nightpiercergreatbowweak");
        nightPiercerGreatBowStrong = GameSound.fromFile("nightpiercergreatbowstrong");
        slimeGreatBowWeak = GameSound.fromFile("slimegreatbowweak");
        slimeGreatBowStrong = GameSound.fromFile("slimegreatbowstrong");
        druidsGreatBowWeak = GameSound.fromFile("druidsgreatbowweak");
        druidsGreatBowStrong = GameSound.fromFile("druidsgreatbowstrong");
        cryoSetStorm = GameSound.fromFile("cryosetstorm");
        evilsprotectorbegin = GameSound.fromFile("evilsprotectorbegin", 500);
        evilsprotectorhurt = GameSound.fromFile("evilsprotectorhurt", 500);
        evilsprotectordeath = GameSound.fromFile("evilsprotectordeath");
        queenspiderbegin = GameSound.fromFile("queenspiderbegin", 500);
        queenspiderhurt = GameSound.fromFile("queenspiderhurt", 500);
        queenspiderdeath = GameSound.fromFile("queenspiderdeath");
        voidwizardbegin = GameSound.fromFile("voidwizardbegin", 500);
        voidwizardhurt = GameSound.fromFile("voidwizardhurt", 500);
        voidwizarddeath = GameSound.fromFile("voidwizarddeath");
        chieftainbegin = GameSound.fromFile("chieftainbegin", 500);
        chieftainhurt = GameSound.fromFile("chieftainhurt", 500);
        chieftaindeath = GameSound.fromFile("chieftaindeath");
        swampguardianbegin = GameSound.fromFile("swampguardianbegin", 500);
        swampguardianhurt = GameSound.fromFile("swampguardianhurt", 500);
        swampguardiandeath = GameSound.fromFile("swampguardiandeath");
        ancientvulturebegin = GameSound.fromFile("ancientvulturebegin", 500);
        ancientvulturehurt = GameSound.fromFile("ancientvulturehurt", 500);
        ancientvulturedeath = GameSound.fromFile("ancientvulturedeath");
        piratecaptainbegin = GameSound.fromFile("piratecaptainbegin", 500);
        piratecaptainhurt = GameSound.fromFile("piratecaptainhurt", 500);
        piratecaptaindeath = GameSound.fromFile("piratecaptaindeath");
        reaperbegin = GameSound.fromFile("reaperbegin", 500);
        reaperhurt = GameSound.fromFile("reaperhurt", 500);
        reaperdeath = GameSound.fromFile("reaperdeath");
        cryoqueenbegin = GameSound.fromFile("cryoqueenbegin", 500);
        cryoqueenhurt = GameSound.fromFile("cryoqueenhurt", 500);
        cryoqueendeath = GameSound.fromFile("cryoqueendeath");
        cursedcronebegin = GameSound.fromFile("cursedcronebegin", 500);
        cursedcronehurt = GameSound.fromFile("cursedcronehurt", 500);
        cursedcronedeath = GameSound.fromFile("cursedcronedeath");
        pestwardenbegin = GameSound.fromFile("pestwardenbegin", 500);
        pestwardenhurt = GameSound.fromFile("pestwardenhurt", 500);
        pestwardendeath = GameSound.fromFile("pestwardendeath", 100);
        gritbegin = GameSound.fromFile("gritbegin", 500);
        grithurt = GameSound.fromFile("grithurt", 500);
        gritdeath = GameSound.fromFile("gritdeath");
        sagebegin = GameSound.fromFile("sagebegin", 500);
        sagehurt = GameSound.fromFile("sagehurt", 500);
        sagedeath = GameSound.fromFile("sagedeath");
        fallenwizardbegin = GameSound.fromFile("fallenwizardbegin", 500);
        fallenwizardhurt = GameSound.fromFile("fallenwizardhurt", 500);
        fallenwizarddeath = GameSound.fromFile("fallenwizarddeath");
        motherslimebegin = GameSound.fromFile("motherslimebegin", 500);
        motherslimehurt = GameSound.fromFile("motherslimehurt", 500);
        motherslimedeath = GameSound.fromFile("motherslimedeath");
        nightswarmbegin = GameSound.fromFile("nightswarmbegin", 500);
        nightswarmhurt = GameSound.fromFile("nightswarmhurt", 500);
        nightswarmdeath = GameSound.fromFile("nightswarmdeath", 400);
        nightswarmdeathfinal = GameSound.fromFile("nightswarmdeathfinal", 400);
        spiderempressbegin = GameSound.fromFile("spiderempressbegin", 500);
        spiderempresshurt = GameSound.fromFile("spiderempresshurt", 500);
        spiderempressdeath = GameSound.fromFile("spiderempressdeath");
        sunlightchampionbegin = GameSound.fromFile("sunlightchampionbegin", 500);
        sunlightchampionhurt = GameSound.fromFile("sunlightchampionhurt", 500);
        sunlightchampiondeath = GameSound.fromFile("sunlightchampiondeath");
        moonlightdancerbegin = GameSound.fromFile("moonlightdancerbegin", 500);
        moonlightdancerhurt = GameSound.fromFile("moonlightdancerhurt", 500);
        moonlightdancerdeath = GameSound.fromFile("moonlightdancerdeath");
        crystaldragonbegin = GameSound.fromFile("crystaldragonbegin", 500);
        crystaldragonhurt = GameSound.fromFile("crystaldragonhurt", 500);
        crystaldragondeath = GameSound.fromFile("crystaldragondeath");
        ascendedPylonDeath = GameSound.fromFile("ascendedpylondeath");
        blackholeBegin = GameSound.fromFile("blackholebegin");
        ascendedWizardBegin = GameSound.fromFile("ascendedwizardbegin");
        ascendedWizardHurt1 = GameSound.fromFile("ascendedwizardhurt1");
        ascendedWizardHurt2 = GameSound.fromFile("ascendedwizardhurt2");
        ascendedWizardHurt3 = GameSound.fromFile("ascendedwizardhurt3");
        ascendedWizardStage1End = GameSound.fromFile("ascendedwizardstage1end");
        ascendedWizardStage2Begin = GameSound.fromFile("ascendedwizardstage2begin");
        ascendedWizardStage2Hurt1 = GameSound.fromFile("ascendedwizardstage2hurt1");
        ascendedWizardStage2Hurt2 = GameSound.fromFile("ascendedwizardstage2hurt2");
        ascendedWizardStage2Hurt3 = GameSound.fromFile("ascendedwizardstage2hurt3");
        ascendedWizardStage2End = GameSound.fromFile("ascendedwizardstage2end");
        ascendedWizardFlashBegin = GameSound.fromFile("ascendedwizardflashbegin");
        theVoidBegin = GameSound.fromFile("thevoidbegin");
        theVoidDeath = GameSound.fromFile("thevoiddeath");
        theVoidFlashBegin = GameSound.fromFile("thevoidflashbegin");
        theVoidHurt1 = GameSound.fromFile("thevoidhurt1");
        theVoidHurt2 = GameSound.fromFile("thevoidhurt2");
        theVoidHurt3 = GameSound.fromFile("thevoidhurt3");
        theVoidHurt4 = GameSound.fromFile("thevoidhurt4");
        bassNote = GameSound.fromFile("notes/bass");
        hatNote = GameSound.fromFile("notes/hat");
        kickNote = GameSound.fromFile("notes/kick");
        pianoNote = GameSound.fromFile("notes/piano");
        snareNote = GameSound.fromFile("notes/snare");
    }

    public static void finishLoadingSounds() {
        GameLoadingScreen.drawLoadingString(Localization.translate("loading", "sound"));
        GameSound.endLoaderThreads();
        if (GlobalData.isDevMode()) {
            GameSound.listUnloadedSounds(new ArrayList<String>(), new ArrayList<String>());
        }
    }

    public static void loadShaders() {
        GameLoadingScreen.drawLoadingString(Localization.translate("loading", "shaders"));
        GameResources.deleteShaders();
        shaders = new HashMap();
        liquidShader = new LiquidShader();
        GameResources.addShader("liquidShader", liquidShader);
        waveShader = new WaveShader();
        GameResources.addShader("waveShader", waveShader);
        rainShader = new RainShader();
        GameResources.addShader("rainShader", rainShader);
        textureOffsetShader = new TextureOffsetShader();
        GameResources.addShader("textureOffsetShader", textureOffsetShader);
        rectangleShader = new RectangleShader();
        GameResources.addShader("rectangleShader", rectangleShader);
        edgeMaskShader = new EdgeMaskShader();
        GameResources.addShader("edgeMaskShader", edgeMaskShader);
        formShader = new FormShader();
        GameResources.addShader("formShader", formShader);
        sharpenShader = new SharpenShader();
        GameResources.addShader("sharpenShader", sharpenShader);
        whiteShader = new WhiteShader();
        GameResources.addShader("whiteShader", whiteShader);
        colorSettingShader = new ColorShader();
        GameResources.addShader("colorSettingShader", colorSettingShader);
        debugColorShader = new ColorShader();
        GameResources.addShader("debugColorShader", debugColorShader);
        brightnessShader = new ColorShader();
        GameResources.addShader("brightnessShader", brightnessShader);
        windowColorShader = new ColorShader();
        GameResources.addShader("windowColorShader", windowColorShader);
        horizontalGaussShader = new GameShader("vertHorizontalGaussBlur", "fragGaussBlur");
        GameResources.addShader("horizontalGaussShader", horizontalGaussShader);
        verticalGaussShader = new GameShader("vertVerticalGaussBlur", "fragGaussBlur");
        GameResources.addShader("verticalGaussShader", verticalGaussShader);
        pixelScalingShader = new PixelScalingShader();
        GameResources.addShader("pixelScalingShader", pixelScalingShader);
        darknessShader = new DarknessShader();
        GameResources.addShader("darknessShader", darknessShader);
        shockwaveShader = new ShockwaveShader(false);
        GameResources.addShader("shockwaveShader", shockwaveShader);
        shockwaveTestShader = new ShockwaveShader(true);
        GameResources.addShader("shockwaveTestShader", shockwaveTestShader);
        ascendedVoidShader = new AscendedVoidShader();
        GameResources.addShader("ascendedVoidShader", ascendedVoidShader);
    }

    public static void loadCursors() {
        GameTexture colorCursor;
        GameTexture loaded = GameTexture.fromFile("cursors");
        if (loaded.isFinal()) {
            loaded.restoreFinal();
            colorCursor = new GameTexture(loaded);
            loaded.makeFinal();
        } else {
            colorCursor = new GameTexture(loaded);
        }
        colorCursor.applyColor(Settings.cursorColor, (currentColor, mergeColor) -> {
            float saturation;
            int cMax = GameMath.max(currentColor.getRed(), currentColor.getGreen(), currentColor.getBlue());
            int cMin = GameMath.min(currentColor.getRed(), currentColor.getGreen(), currentColor.getBlue());
            float f = saturation = cMax != 0 ? (float)(cMax - cMin) / (float)cMax : 0.0f;
            if (saturation != 0.0f) {
                return currentColor;
            }
            int red = (int)((float)currentColor.getRed() / 255.0f * ((float)mergeColor.getRed() / 255.0f) * 255.0f);
            int green = (int)((float)currentColor.getGreen() / 255.0f * ((float)mergeColor.getGreen() / 255.0f) * 255.0f);
            int blue = (int)((float)currentColor.getBlue() / 255.0f * ((float)mergeColor.getBlue() / 255.0f) * 255.0f);
            return new Color(red, green, blue, currentColor.getAlpha());
        });
        for (GameWindow.CURSOR value : GameWindow.CURSOR.values()) {
            WindowManager.getWindow().loadCursor(value, colorCursor, Settings.cursorSize);
        }
    }

    public static void deleteShaders() {
        if (shaders == null) {
            return;
        }
        for (String s : shaders.keySet()) {
            shaders.get(s).delete();
        }
        shaders.clear();
    }

    private static void addShader(String name, GameShader shader) {
        if (shaders.containsKey(name)) {
            throw new NullPointerException("ERROR: Conflicted shader name: " + name);
        }
        shaders.put(name, shader);
    }

    public static GameShader getShader(String name) {
        return shaders.get(name);
    }

    public static HashMap<String, GameShader> getShaders() {
        return shaders;
    }

    static {
        birdAmbients = new GameSound[42];
        duckAmbients = new GameSound[5];
        zombieGroans = new GameSound[30];
        flagNoises = new GameSound[6];
    }
}

