/*
 * Decompiled with CFR 0.152.
 */
package necesse.inventory.lootTable;

import necesse.inventory.lootTable.LootTable;
import necesse.inventory.lootTable.lootItem.OneOfLootItems;
import necesse.inventory.lootTable.presets.AbandonedMineChestLootTable;
import necesse.inventory.lootTable.presets.AlchemistChestLootTable;
import necesse.inventory.lootTable.presets.AnglerChestLootTable;
import necesse.inventory.lootTable.presets.ArcanicChestLootTable;
import necesse.inventory.lootTable.presets.ArmorSetsLootTable;
import necesse.inventory.lootTable.presets.BearBarrelLootTable;
import necesse.inventory.lootTable.presets.BlacksmithChestLootTable;
import necesse.inventory.lootTable.presets.BodyArmorLootTable;
import necesse.inventory.lootTable.presets.BowAndArrowsLootTable;
import necesse.inventory.lootTable.presets.BowWeaponsLootTable;
import necesse.inventory.lootTable.presets.CarpenterChestLootTable;
import necesse.inventory.lootTable.presets.CaveChestLootTable;
import necesse.inventory.lootTable.presets.CaveCryptLootTable;
import necesse.inventory.lootTable.presets.CaveRuinsLootTable;
import necesse.inventory.lootTable.presets.ChefCoolingBoxLootTable;
import necesse.inventory.lootTable.presets.ChristmasChestLootTable;
import necesse.inventory.lootTable.presets.ChristmasPresentLootTable;
import necesse.inventory.lootTable.presets.CloseRangeWeaponsLootTable;
import necesse.inventory.lootTable.presets.CosmeticArmorLootTable;
import necesse.inventory.lootTable.presets.CosmeticSetArmorLootTable;
import necesse.inventory.lootTable.presets.CrateLootTable;
import necesse.inventory.lootTable.presets.DeadMerchantsLootTable;
import necesse.inventory.lootTable.presets.DeepCaveChestLootTable;
import necesse.inventory.lootTable.presets.DeepCaveRuinsLootTable;
import necesse.inventory.lootTable.presets.DeepCrateLootTable;
import necesse.inventory.lootTable.presets.DesertBiomeOldVinylsLootTable;
import necesse.inventory.lootTable.presets.DungeonBiomeOldVinylsLootTable;
import necesse.inventory.lootTable.presets.DungeonChestLootTable;
import necesse.inventory.lootTable.presets.FarmerChestLootTable;
import necesse.inventory.lootTable.presets.FeetArmorLootTable;
import necesse.inventory.lootTable.presets.FishianBarrelLootTable;
import necesse.inventory.lootTable.presets.ForestBiomeOldVinylsLootTable;
import necesse.inventory.lootTable.presets.GlaiveWeaponsLootTable;
import necesse.inventory.lootTable.presets.GlobalMobDropsLootTable;
import necesse.inventory.lootTable.presets.GreatbowWeaponsLootTable;
import necesse.inventory.lootTable.presets.GreatswordWeaponsLootTable;
import necesse.inventory.lootTable.presets.GunWeaponsLootTable;
import necesse.inventory.lootTable.presets.HeadArmorLootTable;
import necesse.inventory.lootTable.presets.HunterChestLootTable;
import necesse.inventory.lootTable.presets.HunterCookedFoodLootTable;
import necesse.inventory.lootTable.presets.IncursionArmorSetsLootTable;
import necesse.inventory.lootTable.presets.IncursionBodyArmorLootTable;
import necesse.inventory.lootTable.presets.IncursionBowWeaponsLootTable;
import necesse.inventory.lootTable.presets.IncursionCloseRangeWeaponsLootTable;
import necesse.inventory.lootTable.presets.IncursionCrateLootTable;
import necesse.inventory.lootTable.presets.IncursionFeetArmorLootTable;
import necesse.inventory.lootTable.presets.IncursionGlaiveWeaponsLootTable;
import necesse.inventory.lootTable.presets.IncursionGreatbowWeaponsLootTable;
import necesse.inventory.lootTable.presets.IncursionGreatswordWeaponsLootTable;
import necesse.inventory.lootTable.presets.IncursionGunWeaponsLootTable;
import necesse.inventory.lootTable.presets.IncursionHeadArmorLootTable;
import necesse.inventory.lootTable.presets.IncursionMagicWeaponsLootTable;
import necesse.inventory.lootTable.presets.IncursionSpearWeaponsLootTable;
import necesse.inventory.lootTable.presets.IncursionSummonWeaponsLootTable;
import necesse.inventory.lootTable.presets.IncursionThrowWeaponsLootTable;
import necesse.inventory.lootTable.presets.IncursionTrinketsLootTable;
import necesse.inventory.lootTable.presets.MagicWeaponsLootTable;
import necesse.inventory.lootTable.presets.OldVinylsLootTable;
import necesse.inventory.lootTable.presets.PetsLootTable;
import necesse.inventory.lootTable.presets.PirateChestLootTable;
import necesse.inventory.lootTable.presets.PirateDisplayStandLootTable;
import necesse.inventory.lootTable.presets.RareIncursionArmorSetsLootTable;
import necesse.inventory.lootTable.presets.RareIncursionTrinketsLootTable;
import necesse.inventory.lootTable.presets.RareIncursionWeaponsLootTable;
import necesse.inventory.lootTable.presets.RavenChestLootTable;
import necesse.inventory.lootTable.presets.RollingPinDisplayStandLootTable;
import necesse.inventory.lootTable.presets.RuneboundCosmeticArmorLootTable;
import necesse.inventory.lootTable.presets.RuneboundTombLootTable;
import necesse.inventory.lootTable.presets.SnowBiomeOldVinylsLootTable;
import necesse.inventory.lootTable.presets.SpearWeaponsLootTable;
import necesse.inventory.lootTable.presets.StartChestLootTable;
import necesse.inventory.lootTable.presets.StartDisplayStandLootTable;
import necesse.inventory.lootTable.presets.StringsVinyl1LootTable;
import necesse.inventory.lootTable.presets.StringsVinyl2LootTable;
import necesse.inventory.lootTable.presets.SummonWeaponsLootTable;
import necesse.inventory.lootTable.presets.SurfaceRuinsChestLootTable;
import necesse.inventory.lootTable.presets.SwampBiomeOldVinylsLootTable;
import necesse.inventory.lootTable.presets.TempleChestLootTable;
import necesse.inventory.lootTable.presets.ThrowWeaponsLootTable;
import necesse.inventory.lootTable.presets.ToolsLootTable;
import necesse.inventory.lootTable.presets.TrinketsLootTable;
import necesse.inventory.lootTable.presets.WitchCrateLootTable;

public class LootTablePresets {
    public static LootTable globalMobDrops = GlobalMobDropsLootTable.instance;
    public static LootTable christmasPresents = ChristmasPresentLootTable.instance;
    public static OneOfLootItems tools = ToolsLootTable.instance;
    public static OneOfLootItems armorSets = ArmorSetsLootTable.instance;
    public static OneOfLootItems headArmor = HeadArmorLootTable.instance;
    public static OneOfLootItems bodyArmor = BodyArmorLootTable.instance;
    public static OneOfLootItems feetArmor = FeetArmorLootTable.instance;
    public static OneOfLootItems trinkets = TrinketsLootTable.instance;
    public static OneOfLootItems closeRangeWeapons = CloseRangeWeaponsLootTable.instance;
    public static OneOfLootItems greatswordWeapons = GreatswordWeaponsLootTable.instance;
    public static OneOfLootItems spearWeapons = SpearWeaponsLootTable.instance;
    public static OneOfLootItems glaiveWeapons = GlaiveWeaponsLootTable.instance;
    public static OneOfLootItems bowWeapons = BowWeaponsLootTable.instance;
    public static OneOfLootItems greatBowWeapons = GreatbowWeaponsLootTable.instance;
    public static OneOfLootItems gunWeapons = GunWeaponsLootTable.instance;
    public static OneOfLootItems magicWeapons = MagicWeaponsLootTable.instance;
    public static OneOfLootItems throwWeapons = ThrowWeaponsLootTable.instance;
    public static OneOfLootItems summonWeapons = SummonWeaponsLootTable.instance;
    public static OneOfLootItems incursionArmorSets = IncursionArmorSetsLootTable.instance;
    public static OneOfLootItems incursionHeadArmor = IncursionHeadArmorLootTable.instance;
    public static OneOfLootItems incursionBodyArmor = IncursionBodyArmorLootTable.instance;
    public static OneOfLootItems incursionFeetArmor = IncursionFeetArmorLootTable.instance;
    public static OneOfLootItems incursionTrinkets = IncursionTrinketsLootTable.instance;
    public static OneOfLootItems incursionCloseRangeWeapons = IncursionCloseRangeWeaponsLootTable.instance;
    public static OneOfLootItems incursionGreatswordWeapons = IncursionGreatswordWeaponsLootTable.instance;
    public static OneOfLootItems incursionSpearWeapons = IncursionSpearWeaponsLootTable.instance;
    public static OneOfLootItems incursionGlaiveWeapons = IncursionGlaiveWeaponsLootTable.instance;
    public static OneOfLootItems incursionBowWeapons = IncursionBowWeaponsLootTable.instance;
    public static OneOfLootItems incursionGreatBowWeapons = IncursionGreatbowWeaponsLootTable.instance;
    public static OneOfLootItems incursionGunWeapons = IncursionGunWeaponsLootTable.instance;
    public static OneOfLootItems incursionMagicWeapons = IncursionMagicWeaponsLootTable.instance;
    public static OneOfLootItems incursionThrowWeapons = IncursionThrowWeaponsLootTable.instance;
    public static OneOfLootItems incursionSummonWeapons = IncursionSummonWeaponsLootTable.instance;
    public static OneOfLootItems rareIncursionWeapons = RareIncursionWeaponsLootTable.instance;
    public static OneOfLootItems rareIncursionArmorSets = RareIncursionArmorSetsLootTable.instance;
    public static OneOfLootItems rareIncursionTrinkets = RareIncursionTrinketsLootTable.instance;
    public static OneOfLootItems cosmeticArmor = CosmeticArmorLootTable.instance;
    public static OneOfLootItems cosmeticArmorSets = CosmeticSetArmorLootTable.instance;
    public static OneOfLootItems pets = PetsLootTable.instance;
    public static LootTable oldVinylsLootTable = OldVinylsLootTable.instance;
    public static LootTable forestBiomeOldVinylsLootTable = ForestBiomeOldVinylsLootTable.instance;
    public static LootTable snowBiomeOldVinylsLootTable = SnowBiomeOldVinylsLootTable.instance;
    public static LootTable swampBiomeOldVinylsLootTable = SwampBiomeOldVinylsLootTable.instance;
    public static LootTable desertBiomeOldVinylsLootTable = DesertBiomeOldVinylsLootTable.instance;
    public static LootTable dungeonBiomeOldVinylsLootTable = DungeonBiomeOldVinylsLootTable.instance;
    public static LootTable anglerChest = AnglerChestLootTable.instance;
    public static LootTable blacksmithChest = BlacksmithChestLootTable.instance;
    public static LootTable farmerChest = FarmerChestLootTable.instance;
    public static LootTable alchemistChest = AlchemistChestLootTable.instance;
    public static LootTable carpenterChest = CarpenterChestLootTable.instance;
    public static LootTable hunterChest = HunterChestLootTable.instance;
    public static LootTable startChest = StartChestLootTable.instance;
    public static LootTable startDisplayStand = StartDisplayStandLootTable.instance;
    public static LootTable surfaceRuinsChest = SurfaceRuinsChestLootTable.instance;
    public static LootTable stringsVinyls1LootTable = StringsVinyl1LootTable.instance;
    public static LootTable stringsVinyls2LootTable = StringsVinyl2LootTable.instance;
    public static LootTable witchCrate = WitchCrateLootTable.instance;
    public static LootTable hunterCookedFoodLootTable = HunterCookedFoodLootTable.instance;
    public static LootTable bowAndArrowsLootTable = BowAndArrowsLootTable.instance;
    public static LootTable christmasChestLootTable = ChristmasChestLootTable.instance;
    public static LootTable rollingPinDisplayStand = RollingPinDisplayStandLootTable.instance;
    public static LootTable deadMerchantsLoot = DeadMerchantsLootTable.instance;
    public static LootTable basicCrate = CrateLootTable.basicCrate;
    public static LootTable snowCrate = CrateLootTable.snowCrate;
    public static LootTable swampCrate = CrateLootTable.swampCrate;
    public static LootTable desertCrate = CrateLootTable.desertCrate;
    public static LootTable plainsCrate = CrateLootTable.plainsCrate;
    public static LootTable caveCryptUniqueItems = new LootTable(CaveCryptLootTable.uniqueItems);
    public static LootTable caveCryptCoffin = CaveCryptLootTable.instance;
    public static LootTable basicCaveRuinsChest = CaveRuinsLootTable.basicChest;
    public static LootTable snowCaveRuinsChest = CaveRuinsLootTable.snowChest;
    public static LootTable swampCaveRuinsChest = CaveRuinsLootTable.swampChest;
    public static LootTable desertCaveRuinsChest = CaveRuinsLootTable.desertChest;
    public static LootTable plainsCaveRuinsChest = CaveRuinsLootTable.plainsChest;
    public static LootTable runeboundCosmeticArmorLootTable = RuneboundCosmeticArmorLootTable.instance;
    public static LootTable basicCaveChest = CaveChestLootTable.basicChest;
    public static LootTable snowCaveChest = CaveChestLootTable.snowChest;
    public static LootTable swampCaveChest = CaveChestLootTable.swampChest;
    public static LootTable desertCaveChest = CaveChestLootTable.desertChest;
    public static LootTable plainsCaveChest = CaveChestLootTable.plainsChest;
    public static LootTable bearBarrel = BearBarrelLootTable.instance;
    public static LootTable fishianBarrel = FishianBarrelLootTable.instance;
    public static LootTable dungeonChest = DungeonChestLootTable.instance;
    public static LootTable evilWitchChest = WitchCrateLootTable.evilWitchChest;
    public static LootTable pirateChest = PirateChestLootTable.instance;
    public static LootTable pirateDisplayStand = PirateDisplayStandLootTable.instance;
    public static LootTable basicDeepCrate = DeepCrateLootTable.basicDeepCrate;
    public static LootTable snowDeepCrate = DeepCrateLootTable.snowDeepCrate;
    public static LootTable plainsDeepCrate = DeepCrateLootTable.plainsDeepCrate;
    public static LootTable swampDeepCrate = DeepCrateLootTable.swampDeepCrate;
    public static LootTable desertDeepCrate = DeepCrateLootTable.desertDeepCrate;
    public static LootTable deepCaveChest = DeepCaveChestLootTable.basicDeepCaveChest;
    public static LootTable deepSnowCaveChest = DeepCaveChestLootTable.snowDeepCaveChest;
    public static LootTable deepPlainsCaveChest = DeepCaveChestLootTable.plainsDeepCaveChest;
    public static LootTable runeboundTombCoffin = RuneboundTombLootTable.instance;
    public static LootTable deepSwampCaveChest = DeepCaveChestLootTable.swampDeepCaveChest;
    public static LootTable deepDesertCaveChest = DeepCaveChestLootTable.desertDeepCaveChest;
    public static LootTable abandonedMineChest = AbandonedMineChestLootTable.instance;
    public static LootTable templeChest = TempleChestLootTable.instance;
    public static LootTable basicDeepCaveRuinsChest = DeepCaveRuinsLootTable.basicDeepChest;
    public static LootTable snowDeepCaveRuinsChest = DeepCaveRuinsLootTable.snowDeepChest;
    public static LootTable plainsDeepCaveRuinsChest = DeepCaveRuinsLootTable.plainsDeepChest;
    public static LootTable swampDeepCaveRuinsChest = DeepCaveRuinsLootTable.swampDeepChest;
    public static LootTable desertDeepCaveRuinsChest = DeepCaveRuinsLootTable.desertDeepChest;
    public static LootTable incursionCrate = IncursionCrateLootTable.instance;
    public static LootTable ravenChest = RavenChestLootTable.instance;
    public static LootTable arcanicChest = ArcanicChestLootTable.instance;
    public static LootTable chefCoolingBox = ChefCoolingBoxLootTable.instance;
}

